-- Baseline foreign-key constraints. Applied after all key/check constraints.

ALTER TABLE ONLY public.bank_accounts ADD CONSTRAINT bank_accounts_connection_id_fkey FOREIGN KEY (connection_id) REFERENCES integration_connections(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.bank_reconciliation_items ADD CONSTRAINT bank_reconciliation_items_bank_transaction_id_fkey FOREIGN KEY (bank_transaction_id) REFERENCES bank_transactions(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.bank_reconciliation_items ADD CONSTRAINT bank_reconciliation_items_reconciliation_id_fkey FOREIGN KEY (reconciliation_id) REFERENCES bank_reconciliations(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.bank_transaction_postings ADD CONSTRAINT bank_transaction_postings_bank_transaction_id_fkey FOREIGN KEY (bank_transaction_id) REFERENCES bank_transactions(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.bank_transaction_postings ADD CONSTRAINT bank_transaction_postings_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES journal_entries(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.bank_transaction_splits ADD CONSTRAINT bank_transaction_splits_bank_transaction_id_fkey FOREIGN KEY (bank_transaction_id) REFERENCES bank_transactions(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.bank_transactions ADD CONSTRAINT bank_transactions_connection_id_fkey FOREIGN KEY (connection_id) REFERENCES integration_connections(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.credit_card_statement_transactions ADD CONSTRAINT credit_card_statement_transactions_statement_id_fkey FOREIGN KEY (statement_id) REFERENCES credit_card_statements(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.credit_card_statements ADD CONSTRAINT credit_card_statements_matched_bank_transaction_id_fkey FOREIGN KEY (matched_bank_transaction_id) REFERENCES bank_transactions(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.credit_card_statements ADD CONSTRAINT credit_card_statements_suggested_bank_transaction_id_fkey FOREIGN KEY (suggested_bank_transaction_id) REFERENCES bank_transactions(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.credit_card_transfer_matches ADD CONSTRAINT credit_card_transfer_matches_bank_transaction_id_fkey FOREIGN KEY (bank_transaction_id) REFERENCES bank_transactions(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.credit_card_transfer_matches ADD CONSTRAINT credit_card_transfer_matches_card_transaction_id_fkey FOREIGN KEY (card_transaction_id) REFERENCES bank_transactions(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.deli_wallboard_task_checks ADD CONSTRAINT deli_wallboard_task_checks_task_id_fkey FOREIGN KEY (task_id) REFERENCES deli_wallboard_tasks(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.direct_deposit_elections ADD CONSTRAINT direct_deposit_elections_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE ONLY public.employee_availability ADD CONSTRAINT employee_availability_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.employee_handbook_acknowledgments ADD CONSTRAINT employee_handbook_acknowledgments_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE ONLY public.employee_message_reads ADD CONSTRAINT employee_message_reads_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.employee_message_reads ADD CONSTRAINT employee_message_reads_message_id_fkey FOREIGN KEY (message_id) REFERENCES employee_messages(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.employee_messages ADD CONSTRAINT employee_messages_recipient_employee_id_fkey FOREIGN KEY (recipient_employee_id) REFERENCES employees(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.employee_messages ADD CONSTRAINT employee_messages_sender_employee_id_fkey FOREIGN KEY (sender_employee_id) REFERENCES employees(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.employment_form_events ADD CONSTRAINT employment_form_events_form_id_fkey FOREIGN KEY (form_id) REFERENCES employment_forms(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.employment_forms ADD CONSTRAINT employment_forms_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE ONLY public.integration_sync_runs ADD CONSTRAINT integration_sync_runs_connection_id_fkey FOREIGN KEY (connection_id) REFERENCES integration_connections(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.inventory_purchases ADD CONSTRAINT inventory_purchases_bill_id_fkey FOREIGN KEY (bill_id) REFERENCES vendor_bills(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.inventory_purchases ADD CONSTRAINT inventory_purchases_inventory_item_id_fkey FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.invoice_payment_allocations ADD CONSTRAINT invoice_payment_allocations_bank_transaction_id_fkey FOREIGN KEY (bank_transaction_id) REFERENCES bank_transactions(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.invoice_payment_allocations ADD CONSTRAINT invoice_payment_allocations_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.invoices ADD CONSTRAINT invoices_journal_entry_id_fkey FOREIGN KEY (journal_entry_id) REFERENCES journal_entries(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.invoices ADD CONSTRAINT invoices_template_id_fkey FOREIGN KEY (template_id) REFERENCES recurring_invoice_templates(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.journal_lines ADD CONSTRAINT journal_lines_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounting_accounts(id);
ALTER TABLE ONLY public.journal_lines ADD CONSTRAINT journal_lines_entry_id_fkey FOREIGN KEY (entry_id) REFERENCES journal_entries(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.manual_time_entry_audit ADD CONSTRAINT manual_time_entry_audit_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE ONLY public.missed_shift_cases ADD CONSTRAINT missed_shift_cases_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.missed_shift_cases ADD CONSTRAINT missed_shift_cases_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES schedule_shifts(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.ordering_call_sessions ADD CONSTRAINT ordering_call_sessions_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES ordering_customers(id);
ALTER TABLE ONLY public.ordering_call_sessions ADD CONSTRAINT ordering_call_sessions_order_id_fkey FOREIGN KEY (order_id) REFERENCES ordering_orders(id);
ALTER TABLE ONLY public.ordering_combo_groups ADD CONSTRAINT ordering_combo_groups_combo_id_fkey FOREIGN KEY (combo_id) REFERENCES ordering_combo_definitions(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.ordering_combo_options ADD CONSTRAINT ordering_combo_options_group_id_fkey FOREIGN KEY (group_id) REFERENCES ordering_combo_groups(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.ordering_combo_options ADD CONSTRAINT ordering_combo_options_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES ordering_menu_items(id);
ALTER TABLE ONLY public.ordering_customer_addresses ADD CONSTRAINT ordering_customer_addresses_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES ordering_customers(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.ordering_customer_phones ADD CONSTRAINT ordering_customer_phones_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES ordering_customers(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.ordering_loyalty_ledger ADD CONSTRAINT ordering_loyalty_ledger_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES ordering_customers(id);
ALTER TABLE ONLY public.ordering_loyalty_ledger ADD CONSTRAINT ordering_loyalty_ledger_order_id_fkey FOREIGN KEY (order_id) REFERENCES ordering_orders(id);
ALTER TABLE ONLY public.ordering_loyalty_ledger ADD CONSTRAINT ordering_loyalty_ledger_program_id_fkey FOREIGN KEY (program_id) REFERENCES ordering_loyalty_programs(id);
ALTER TABLE ONLY public.ordering_menu_item_combos ADD CONSTRAINT ordering_menu_item_combos_combo_id_fkey FOREIGN KEY (combo_id) REFERENCES ordering_combo_definitions(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.ordering_menu_item_combos ADD CONSTRAINT ordering_menu_item_combos_item_id_fkey FOREIGN KEY (item_id) REFERENCES ordering_menu_items(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.ordering_menu_item_modifier_defaults ADD CONSTRAINT ordering_menu_item_modifier_defaults_item_id_fkey FOREIGN KEY (item_id) REFERENCES ordering_menu_items(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.ordering_menu_item_modifier_defaults ADD CONSTRAINT ordering_menu_item_modifier_defaults_option_id_fkey FOREIGN KEY (option_id) REFERENCES ordering_modifier_options(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.ordering_menu_item_modifier_groups ADD CONSTRAINT ordering_menu_item_modifier_groups_group_id_fkey FOREIGN KEY (group_id) REFERENCES ordering_modifier_groups(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.ordering_menu_item_modifier_groups ADD CONSTRAINT ordering_menu_item_modifier_groups_item_id_fkey FOREIGN KEY (item_id) REFERENCES ordering_menu_items(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.ordering_menu_item_variants ADD CONSTRAINT ordering_menu_item_variants_item_id_fkey FOREIGN KEY (item_id) REFERENCES ordering_menu_items(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.ordering_menu_items ADD CONSTRAINT ordering_menu_items_category_id_fkey FOREIGN KEY (category_id) REFERENCES ordering_menu_categories(id);
ALTER TABLE ONLY public.ordering_menu_variant_aliases ADD CONSTRAINT ordering_menu_variant_aliases_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES ordering_menu_item_variants(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.ordering_menu_variant_modifier_prices ADD CONSTRAINT ordering_menu_variant_modifier_prices_option_id_fkey FOREIGN KEY (option_id) REFERENCES ordering_modifier_options(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.ordering_menu_variant_modifier_prices ADD CONSTRAINT ordering_menu_variant_modifier_prices_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES ordering_menu_item_variants(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.ordering_modifier_options ADD CONSTRAINT ordering_modifier_options_group_id_fkey FOREIGN KEY (group_id) REFERENCES ordering_modifier_groups(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.ordering_order_events ADD CONSTRAINT ordering_order_events_order_id_fkey FOREIGN KEY (order_id) REFERENCES ordering_orders(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.ordering_order_item_combo_selections ADD CONSTRAINT ordering_order_item_combo_selections_combo_id_fkey FOREIGN KEY (combo_id) REFERENCES ordering_combo_definitions(id);
ALTER TABLE ONLY public.ordering_order_item_combo_selections ADD CONSTRAINT ordering_order_item_combo_selections_group_id_fkey FOREIGN KEY (group_id) REFERENCES ordering_combo_groups(id);
ALTER TABLE ONLY public.ordering_order_item_combo_selections ADD CONSTRAINT ordering_order_item_combo_selections_option_id_fkey FOREIGN KEY (option_id) REFERENCES ordering_combo_options(id);
ALTER TABLE ONLY public.ordering_order_item_combo_selections ADD CONSTRAINT ordering_order_item_combo_selections_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES ordering_order_items(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.ordering_order_item_modifiers ADD CONSTRAINT ordering_order_item_modifiers_group_id_fkey FOREIGN KEY (group_id) REFERENCES ordering_modifier_groups(id);
ALTER TABLE ONLY public.ordering_order_item_modifiers ADD CONSTRAINT ordering_order_item_modifiers_option_id_fkey FOREIGN KEY (option_id) REFERENCES ordering_modifier_options(id);
ALTER TABLE ONLY public.ordering_order_item_modifiers ADD CONSTRAINT ordering_order_item_modifiers_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES ordering_order_items(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.ordering_order_items ADD CONSTRAINT ordering_order_items_item_id_fkey FOREIGN KEY (item_id) REFERENCES ordering_menu_items(id);
ALTER TABLE ONLY public.ordering_order_items ADD CONSTRAINT ordering_order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES ordering_orders(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.ordering_order_items ADD CONSTRAINT ordering_order_items_variant_id_fkey FOREIGN KEY (variant_id) REFERENCES ordering_menu_item_variants(id);
ALTER TABLE ONLY public.ordering_orders ADD CONSTRAINT ordering_orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES ordering_customers(id);
ALTER TABLE ONLY public.ordering_sms_verifications ADD CONSTRAINT ordering_sms_verifications_order_id_fkey FOREIGN KEY (order_id) REFERENCES ordering_orders(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.overtime_risk_alerts ADD CONSTRAINT overtime_risk_alerts_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.owner_message_reads ADD CONSTRAINT owner_message_reads_message_id_fkey FOREIGN KEY (message_id) REFERENCES employee_messages(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.payroll_run_versions ADD CONSTRAINT payroll_run_versions_reopened_from_id_fkey FOREIGN KEY (reopened_from_id) REFERENCES payroll_run_versions(id);
ALTER TABLE ONLY public.push_delivery_log ADD CONSTRAINT push_delivery_log_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES push_subscriptions(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.push_subscriptions ADD CONSTRAINT push_subscriptions_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.receipt_transaction_matches ADD CONSTRAINT receipt_transaction_matches_bank_transaction_id_fkey FOREIGN KEY (bank_transaction_id) REFERENCES bank_transactions(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.receipt_transaction_matches ADD CONSTRAINT receipt_transaction_matches_receipt_id_fkey FOREIGN KEY (receipt_id) REFERENCES receipt_documents(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.recipe_components ADD CONSTRAINT recipe_components_inventory_item_id_fkey FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.recipe_components ADD CONSTRAINT recipe_components_recipe_id_fkey FOREIGN KEY (recipe_id) REFERENCES recipes(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.rezku_inbound_reports ADD CONSTRAINT rezku_inbound_reports_email_id_fkey FOREIGN KEY (email_id) REFERENCES rezku_inbound_emails(email_id) ON DELETE CASCADE;
ALTER TABLE ONLY public.rezku_orders ADD CONSTRAINT rezku_orders_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES rezku_import_batches(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.rezku_product_sales ADD CONSTRAINT rezku_product_sales_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES rezku_product_sales_import_batches(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.rezku_shifts ADD CONSTRAINT rezku_shifts_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES rezku_import_batches(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.rezku_transactions ADD CONSTRAINT rezku_transactions_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES rezku_import_batches(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.rezku_void_events ADD CONSTRAINT rezku_void_events_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES rezku_void_import_batches(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.schedule_publication_deliveries ADD CONSTRAINT schedule_publication_deliveries_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.schedule_publication_deliveries ADD CONSTRAINT schedule_publication_deliveries_publication_id_fkey FOREIGN KEY (publication_id) REFERENCES schedule_publications(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.schedule_shifts ADD CONSTRAINT schedule_shifts_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.shift_change_log ADD CONSTRAINT shift_change_log_new_employee_id_fkey FOREIGN KEY (new_employee_id) REFERENCES employees(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.shift_change_log ADD CONSTRAINT shift_change_log_prior_employee_id_fkey FOREIGN KEY (prior_employee_id) REFERENCES employees(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.shift_change_log ADD CONSTRAINT shift_change_log_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES schedule_shifts(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.shift_requests ADD CONSTRAINT shift_requests_offered_shift_id_fkey FOREIGN KEY (offered_shift_id) REFERENCES schedule_shifts(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.shift_requests ADD CONSTRAINT shift_requests_requester_employee_id_fkey FOREIGN KEY (requester_employee_id) REFERENCES employees(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.shift_requests ADD CONSTRAINT shift_requests_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES schedule_shifts(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.shift_requests ADD CONSTRAINT shift_requests_target_employee_id_fkey FOREIGN KEY (target_employee_id) REFERENCES employees(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.sms_consent_events ADD CONSTRAINT sms_consent_events_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.square_catalog_objects ADD CONSTRAINT square_catalog_objects_connection_id_fkey FOREIGN KEY (connection_id) REFERENCES integration_connections(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.square_deposit_match_payments ADD CONSTRAINT square_deposit_match_payments_match_id_fkey FOREIGN KEY (match_id) REFERENCES square_deposit_matches(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.square_deposit_match_payments ADD CONSTRAINT square_deposit_match_payments_square_payment_id_fkey FOREIGN KEY (square_payment_id) REFERENCES square_payments(id) ON DELETE RESTRICT;
ALTER TABLE ONLY public.square_deposit_matches ADD CONSTRAINT square_deposit_matches_bank_transaction_id_fkey FOREIGN KEY (bank_transaction_id) REFERENCES bank_transactions(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.square_inventory_counts ADD CONSTRAINT square_inventory_counts_connection_id_fkey FOREIGN KEY (connection_id) REFERENCES integration_connections(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.square_order_lines ADD CONSTRAINT square_order_lines_square_order_id_fkey FOREIGN KEY (square_order_id) REFERENCES square_orders(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.square_orders ADD CONSTRAINT square_orders_connection_id_fkey FOREIGN KEY (connection_id) REFERENCES integration_connections(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.square_payments ADD CONSTRAINT square_payments_connection_id_fkey FOREIGN KEY (connection_id) REFERENCES integration_connections(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.time_correction_requests ADD CONSTRAINT time_correction_requests_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.time_entries ADD CONSTRAINT time_entries_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(id);
ALTER TABLE ONLY public.time_off_requests ADD CONSTRAINT time_off_requests_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.vendor_bill_lines ADD CONSTRAINT vendor_bill_lines_bill_id_fkey FOREIGN KEY (bill_id) REFERENCES vendor_bills(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.vendor_bill_lines ADD CONSTRAINT vendor_bill_lines_inventory_item_id_fkey FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.vendor_bills ADD CONSTRAINT vendor_bills_paid_bank_transaction_id_fkey FOREIGN KEY (paid_bank_transaction_id) REFERENCES bank_transactions(id) ON DELETE SET NULL;
