-- Baseline non-foreign-key constraints, part 1.

ALTER TABLE ONLY public.accounting_accounts ADD CONSTRAINT accounting_accounts_account_type_check CHECK (account_type = ANY (ARRAY['Asset'::text, 'Liability'::text, 'Equity'::text, 'Revenue'::text, 'Expense'::text]));
ALTER TABLE ONLY public.accounting_accounts ADD CONSTRAINT accounting_accounts_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.accounting_accounts ADD CONSTRAINT accounting_accounts_business_code_key UNIQUE (business, code);
ALTER TABLE ONLY public.accounting_accounts ADD CONSTRAINT accounting_accounts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.app_users ADD CONSTRAINT app_users_email_key UNIQUE (email);
ALTER TABLE ONLY public.app_users ADD CONSTRAINT app_users_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.app_users ADD CONSTRAINT app_users_role_check CHECK (role = ANY (ARRAY['Owner'::text, 'Co-Owner'::text, 'Accountant'::text, 'Manager'::text, 'Viewer'::text]));
ALTER TABLE ONLY public.application_key_material ADD CONSTRAINT application_key_material_pkey PRIMARY KEY (purpose);
ALTER TABLE ONLY public.audit_events ADD CONSTRAINT audit_events_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.audit_events ADD CONSTRAINT audit_events_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.bank_accounts ADD CONSTRAINT bank_accounts_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.bank_accounts ADD CONSTRAINT bank_accounts_external_account_id_key UNIQUE (external_account_id);
ALTER TABLE ONLY public.bank_accounts ADD CONSTRAINT bank_accounts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.bank_reconciliation_items ADD CONSTRAINT bank_reconciliation_items_pkey PRIMARY KEY (reconciliation_id, bank_transaction_id);
ALTER TABLE ONLY public.bank_reconciliations ADD CONSTRAINT bank_reconciliations_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.bank_reconciliations ADD CONSTRAINT bank_reconciliations_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.bank_reconciliations ADD CONSTRAINT bank_reconciliations_status_check CHECK (status = ANY (ARRAY['Draft'::text, 'Finalized'::text, 'Reopened'::text]));
ALTER TABLE ONLY public.bank_transaction_postings ADD CONSTRAINT bank_transaction_postings_bank_transaction_id_key UNIQUE (bank_transaction_id);
ALTER TABLE ONLY public.bank_transaction_postings ADD CONSTRAINT bank_transaction_postings_journal_entry_id_key UNIQUE (journal_entry_id);
ALTER TABLE ONLY public.bank_transaction_postings ADD CONSTRAINT bank_transaction_postings_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.bank_transaction_splits ADD CONSTRAINT bank_transaction_splits_amount_check CHECK (amount > 0::numeric);
ALTER TABLE ONLY public.bank_transaction_splits ADD CONSTRAINT bank_transaction_splits_bank_transaction_id_line_number_key UNIQUE (bank_transaction_id, line_number);
ALTER TABLE ONLY public.bank_transaction_splits ADD CONSTRAINT bank_transaction_splits_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.bank_transactions ADD CONSTRAINT bank_transactions_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.bank_transactions ADD CONSTRAINT bank_transactions_direction_check CHECK (direction = ANY (ARRAY['Inflow'::text, 'Outflow'::text]));
ALTER TABLE ONLY public.bank_transactions ADD CONSTRAINT bank_transactions_external_transaction_id_key UNIQUE (external_transaction_id);
ALTER TABLE ONLY public.bank_transactions ADD CONSTRAINT bank_transactions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.bank_transactions ADD CONSTRAINT bank_transactions_review_status_check CHECK (review_status = ANY (ARRAY['Needs Review'::text, 'Approved'::text, 'Ignored'::text]));
ALTER TABLE ONLY public.classification_rules ADD CONSTRAINT classification_rules_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.classification_rules ADD CONSTRAINT classification_rules_direction_check CHECK (direction = ANY (ARRAY['Any'::text, 'Inflow'::text, 'Outflow'::text]));
ALTER TABLE ONLY public.classification_rules ADD CONSTRAINT classification_rules_field_check CHECK (field = ANY (ARRAY['Merchant'::text, 'Description'::text, 'Either'::text]));
ALTER TABLE ONLY public.classification_rules ADD CONSTRAINT classification_rules_match_type_check CHECK (match_type = ANY (ARRAY['Contains'::text, 'Exact'::text]));
ALTER TABLE ONLY public.classification_rules ADD CONSTRAINT classification_rules_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.credential_reset_tokens ADD CONSTRAINT credential_reset_tokens_business_check CHECK (business IS NULL OR (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text])));
ALTER TABLE ONLY public.credential_reset_tokens ADD CONSTRAINT credential_reset_tokens_kind_check CHECK (kind = ANY (ARRAY['app-password'::text, 'employee-pin'::text]));
ALTER TABLE ONLY public.credential_reset_tokens ADD CONSTRAINT credential_reset_tokens_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.credential_reset_tokens ADD CONSTRAINT credential_reset_tokens_token_hash_key UNIQUE (token_hash);
ALTER TABLE ONLY public.credit_card_statement_transactions ADD CONSTRAINT credit_card_statement_transactions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.credit_card_statements ADD CONSTRAINT credit_card_statements_blob_url_key UNIQUE (blob_url);
ALTER TABLE ONLY public.credit_card_statements ADD CONSTRAINT credit_card_statements_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.credit_card_statements ADD CONSTRAINT credit_card_statements_extraction_status_check CHECK (extraction_status = ANY (ARRAY['Document Only'::text, 'Extracted'::text, 'No Rows'::text]));
ALTER TABLE ONLY public.credit_card_statements ADD CONSTRAINT credit_card_statements_match_status_check CHECK (match_status = ANY (ARRAY['Unmatched'::text, 'Suggested'::text, 'Matched'::text]));
ALTER TABLE ONLY public.credit_card_statements ADD CONSTRAINT credit_card_statements_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.credit_card_transfer_matches ADD CONSTRAINT credit_card_transfer_matches_bank_transaction_id_card_trans_key UNIQUE (bank_transaction_id, card_transaction_id);
ALTER TABLE ONLY public.credit_card_transfer_matches ADD CONSTRAINT credit_card_transfer_matches_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.credit_card_transfer_matches ADD CONSTRAINT credit_card_transfer_matches_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.credit_card_transfer_matches ADD CONSTRAINT credit_card_transfer_matches_status_check CHECK (status = ANY (ARRAY['Suggested'::text, 'Matched'::text, 'Ignored'::text]));
ALTER TABLE ONLY public.deli_wallboard_task_checks ADD CONSTRAINT deli_wallboard_task_checks_pkey PRIMARY KEY (task_id, work_date);
ALTER TABLE ONLY public.deli_wallboard_tasks ADD CONSTRAINT deli_wallboard_tasks_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.deli_wallboard_tasks ADD CONSTRAINT deli_wallboard_tasks_title_key UNIQUE (title);
ALTER TABLE ONLY public.direct_deposit_elections ADD CONSTRAINT direct_deposit_elections_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.direct_deposit_elections ADD CONSTRAINT direct_deposit_elections_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.direct_deposit_elections ADD CONSTRAINT direct_deposit_elections_status_check CHECK (status = ANY (ARRAY['Assigned'::text, 'Completed'::text, 'Superseded'::text]));
ALTER TABLE ONLY public.documents ADD CONSTRAINT documents_blob_url_key UNIQUE (blob_url);
ALTER TABLE ONLY public.documents ADD CONSTRAINT documents_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.documents ADD CONSTRAINT documents_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.documents ADD CONSTRAINT documents_status_check CHECK (status = ANY (ARRAY['Active'::text, 'Needs Review'::text, 'Archived'::text]));
ALTER TABLE ONLY public.employee_availability ADD CONSTRAINT employee_availability_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.employee_availability ADD CONSTRAINT employee_availability_employee_id_weekday_key UNIQUE (employee_id, weekday);
ALTER TABLE ONLY public.employee_availability ADD CONSTRAINT employee_availability_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.employee_availability ADD CONSTRAINT employee_availability_weekday_check CHECK (weekday >= 0 AND weekday <= 6);
ALTER TABLE ONLY public.employee_handbook_acknowledgments ADD CONSTRAINT employee_handbook_acknowledgments_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.employee_handbook_acknowledgments ADD CONSTRAINT employee_handbook_acknowledgments_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.employee_message_reads ADD CONSTRAINT employee_message_reads_pkey PRIMARY KEY (message_id, employee_id);
ALTER TABLE ONLY public.employee_messages ADD CONSTRAINT employee_messages_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.employee_messages ADD CONSTRAINT employee_messages_message_type_check CHECK (message_type = ANY (ARRAY['Team'::text, 'Direct'::text, 'Announcement'::text]));
ALTER TABLE ONLY public.employee_messages ADD CONSTRAINT employee_messages_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.employees ADD CONSTRAINT employees_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.employees ADD CONSTRAINT employees_business_pin_hash_key UNIQUE (business, pin_hash);
ALTER TABLE ONLY public.employees ADD CONSTRAINT employees_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.employees ADD CONSTRAINT employees_role_group_check CHECK (role_group = ANY (ARRAY['Driver'::text, 'In-House'::text, 'Ignore'::text]));
ALTER TABLE ONLY public.employment_form_events ADD CONSTRAINT employment_form_events_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.employment_form_profiles ADD CONSTRAINT employment_form_profiles_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.employment_form_profiles ADD CONSTRAINT employment_form_profiles_pkey PRIMARY KEY (business);
ALTER TABLE ONLY public.employment_forms ADD CONSTRAINT employment_forms_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.employment_forms ADD CONSTRAINT employment_forms_form_type_check CHECK (form_type = ANY (ARRAY['W4'::text, 'IT2104'::text, 'I9'::text, 'PAY_NOTICE'::text, 'MEAL_POLICY'::text]));
ALTER TABLE ONLY public.employment_forms ADD CONSTRAINT employment_forms_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.employment_forms ADD CONSTRAINT employment_forms_status_check CHECK (status = ANY (ARRAY['Assigned'::text, 'Employee Signed'::text, 'Employer Review'::text, 'Completed'::text, 'Superseded'::text]));
ALTER TABLE ONLY public.forecast_events ADD CONSTRAINT forecast_events_amount_check CHECK (amount > 0::numeric);
ALTER TABLE ONLY public.forecast_events ADD CONSTRAINT forecast_events_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.forecast_events ADD CONSTRAINT forecast_events_direction_check CHECK (direction = ANY (ARRAY['Inflow'::text, 'Outflow'::text]));
ALTER TABLE ONLY public.forecast_events ADD CONSTRAINT forecast_events_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.forecast_events ADD CONSTRAINT forecast_events_recurrence_check CHECK (recurrence = ANY (ARRAY['None'::text, 'Weekly'::text, 'Monthly'::text]));
ALTER TABLE ONLY public.integration_connections ADD CONSTRAINT integration_connections_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.integration_connections ADD CONSTRAINT integration_connections_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.integration_connections ADD CONSTRAINT integration_connections_provider_check CHECK (provider = ANY (ARRAY['Plaid'::text, 'Square'::text, 'CSV'::text]));
ALTER TABLE ONLY public.integration_connections ADD CONSTRAINT integration_connections_provider_external_item_id_key UNIQUE (provider, external_item_id);
ALTER TABLE ONLY public.integration_sync_runs ADD CONSTRAINT integration_sync_runs_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.integration_sync_runs ADD CONSTRAINT integration_sync_runs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.integration_sync_runs ADD CONSTRAINT integration_sync_runs_status_check CHECK (status = ANY (ARRAY['Running'::text, 'Success'::text, 'Failed'::text, 'Skipped'::text]));
ALTER TABLE ONLY public.inventory_items ADD CONSTRAINT inventory_items_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.inventory_items ADD CONSTRAINT inventory_items_business_name_key UNIQUE (business, name);
ALTER TABLE ONLY public.inventory_items ADD CONSTRAINT inventory_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.inventory_purchases ADD CONSTRAINT inventory_purchases_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.inventory_purchases ADD CONSTRAINT inventory_purchases_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.inventory_purchases ADD CONSTRAINT inventory_purchases_quantity_check CHECK (quantity > 0::numeric);
ALTER TABLE ONLY public.inventory_purchases ADD CONSTRAINT inventory_purchases_total_amount_check CHECK (total_amount >= 0::numeric);
ALTER TABLE ONLY public.inventory_purchases ADD CONSTRAINT inventory_purchases_unit_price_check CHECK (unit_price >= 0::numeric);
ALTER TABLE ONLY public.invoice_payment_allocations ADD CONSTRAINT invoice_payment_allocations_amount_check CHECK (amount > 0::numeric);
ALTER TABLE ONLY public.invoice_payment_allocations ADD CONSTRAINT invoice_payment_allocations_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.invoice_payment_allocations ADD CONSTRAINT invoice_payment_allocations_invoice_id_bank_transaction_id_key UNIQUE (invoice_id, bank_transaction_id);
ALTER TABLE ONLY public.invoice_payment_allocations ADD CONSTRAINT invoice_payment_allocations_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.invoices ADD CONSTRAINT invoices_amount_check CHECK (amount > 0::numeric);
ALTER TABLE ONLY public.invoices ADD CONSTRAINT invoices_balance_check CHECK (balance >= 0::numeric);
ALTER TABLE ONLY public.invoices ADD CONSTRAINT invoices_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.invoices ADD CONSTRAINT invoices_business_invoice_number_key UNIQUE (business, invoice_number);
ALTER TABLE ONLY public.invoices ADD CONSTRAINT invoices_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.invoices ADD CONSTRAINT invoices_status_check CHECK (status = ANY (ARRAY['Open'::text, 'Partially Paid'::text, 'Paid'::text, 'Void'::text]));
ALTER TABLE ONLY public.invoices ADD CONSTRAINT invoices_template_id_period_key_key UNIQUE (template_id, period_key);
ALTER TABLE ONLY public.journal_entries ADD CONSTRAINT journal_entries_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.journal_entries ADD CONSTRAINT journal_entries_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.journal_lines ADD CONSTRAINT journal_lines_check CHECK (debit >= 0::numeric AND credit >= 0::numeric);
ALTER TABLE ONLY public.journal_lines ADD CONSTRAINT journal_lines_check1 CHECK (NOT (debit > 0::numeric AND credit > 0::numeric));
ALTER TABLE ONLY public.journal_lines ADD CONSTRAINT journal_lines_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.manual_time_entry_audit ADD CONSTRAINT manual_time_entry_audit_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.manual_time_entry_audit ADD CONSTRAINT manual_time_entry_audit_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.manual_time_entry_audit ADD CONSTRAINT manual_time_entry_audit_source_type_check CHECK (source_type = ANY (ARRAY['Corner Ops'::text, 'Rezku'::text]));
ALTER TABLE ONLY public.missed_shift_cases ADD CONSTRAINT missed_shift_cases_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.missed_shift_cases ADD CONSTRAINT missed_shift_cases_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.missed_shift_cases ADD CONSTRAINT missed_shift_cases_shift_id_key UNIQUE (shift_id);
ALTER TABLE ONLY public.missed_shift_cases ADD CONSTRAINT missed_shift_cases_status_check CHECK (status = ANY (ARRAY['Awaiting Correction'::text, 'Submitted'::text, 'Approved'::text, 'Rejected'::text, 'Resolved'::text]));
ALTER TABLE ONLY public.oauth_state_nonces ADD CONSTRAINT oauth_state_nonces_pkey PRIMARY KEY (nonce_hash);
ALTER TABLE ONLY public.operation_issues ADD CONSTRAINT operation_issues_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.operation_issues ADD CONSTRAINT operation_issues_issue_key_key UNIQUE (issue_key);
ALTER TABLE ONLY public.operation_issues ADD CONSTRAINT operation_issues_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.operation_issues ADD CONSTRAINT operation_issues_severity_check CHECK (severity = ANY (ARRAY['Info'::text, 'Warning'::text, 'Error'::text]));
ALTER TABLE ONLY public.operation_issues ADD CONSTRAINT operation_issues_status_check CHECK (status = ANY (ARRAY['Open'::text, 'Resolved'::text, 'Ignored'::text]));
ALTER TABLE ONLY public.ordering_call_sessions ADD CONSTRAINT ordering_call_sessions_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.ordering_call_sessions ADD CONSTRAINT ordering_call_sessions_owner_type_check CHECK (owner_type = ANY (ARRAY['ai'::text, 'employee'::text, 'none'::text]));
ALTER TABLE ONLY public.ordering_call_sessions ADD CONSTRAINT ordering_call_sessions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ordering_call_sessions ADD CONSTRAINT ordering_call_sessions_state_check CHECK (state = ANY (ARRAY['ringing'::text, 'ai'::text, 'handoff_pending'::text, 'human'::text, 'ended'::text]));
ALTER TABLE ONLY public.ordering_call_sessions ADD CONSTRAINT ordering_call_sessions_three_cx_call_id_key UNIQUE (three_cx_call_id);
ALTER TABLE ONLY public.ordering_combo_definitions ADD CONSTRAINT ordering_combo_definitions_base_price_delta_cents_check CHECK (base_price_delta_cents >= 0);
ALTER TABLE ONLY public.ordering_combo_definitions ADD CONSTRAINT ordering_combo_definitions_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.ordering_combo_definitions ADD CONSTRAINT ordering_combo_definitions_business_name_key UNIQUE (business, name);
ALTER TABLE ONLY public.ordering_combo_definitions ADD CONSTRAINT ordering_combo_definitions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ordering_combo_groups ADD CONSTRAINT ordering_combo_groups_check CHECK (max_selections >= min_selections);
ALTER TABLE ONLY public.ordering_combo_groups ADD CONSTRAINT ordering_combo_groups_combo_id_name_key UNIQUE (combo_id, name);
ALTER TABLE ONLY public.ordering_combo_groups ADD CONSTRAINT ordering_combo_groups_max_selections_check CHECK (max_selections >= 1);
ALTER TABLE ONLY public.ordering_combo_groups ADD CONSTRAINT ordering_combo_groups_min_selections_check CHECK (min_selections >= 0);
ALTER TABLE ONLY public.ordering_combo_groups ADD CONSTRAINT ordering_combo_groups_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ordering_combo_options ADD CONSTRAINT ordering_combo_options_group_id_name_key UNIQUE (group_id, name);
ALTER TABLE ONLY public.ordering_combo_options ADD CONSTRAINT ordering_combo_options_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ordering_customer_addresses ADD CONSTRAINT ordering_customer_addresses_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ordering_customer_phones ADD CONSTRAINT ordering_customer_phones_customer_id_normalized_phone_key UNIQUE (customer_id, normalized_phone);
ALTER TABLE ONLY public.ordering_customer_phones ADD CONSTRAINT ordering_customer_phones_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ordering_customers ADD CONSTRAINT ordering_customers_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.ordering_customers ADD CONSTRAINT ordering_customers_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ordering_loyalty_ledger ADD CONSTRAINT ordering_loyalty_ledger_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.ordering_loyalty_ledger ADD CONSTRAINT ordering_loyalty_ledger_entry_type_check CHECK (entry_type = ANY (ARRAY['earn'::text, 'redeem'::text, 'reversal'::text, 'adjustment'::text, 'expire'::text]));
ALTER TABLE ONLY public.ordering_loyalty_ledger ADD CONSTRAINT ordering_loyalty_ledger_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ordering_loyalty_programs ADD CONSTRAINT ordering_loyalty_programs_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.ordering_loyalty_programs ADD CONSTRAINT ordering_loyalty_programs_business_name_key UNIQUE (business, name);
ALTER TABLE ONLY public.ordering_loyalty_programs ADD CONSTRAINT ordering_loyalty_programs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ordering_menu_categories ADD CONSTRAINT ordering_menu_categories_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.ordering_menu_categories ADD CONSTRAINT ordering_menu_categories_business_name_key UNIQUE (business, name);
ALTER TABLE ONLY public.ordering_menu_categories ADD CONSTRAINT ordering_menu_categories_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ordering_menu_item_combos ADD CONSTRAINT ordering_menu_item_combos_item_id_combo_id_key UNIQUE (item_id, combo_id);
ALTER TABLE ONLY public.ordering_menu_item_combos ADD CONSTRAINT ordering_menu_item_combos_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ordering_menu_item_modifier_defaults ADD CONSTRAINT ordering_menu_item_modifier_defaults_included_quantity_check CHECK (included_quantity >= 0);
ALTER TABLE ONLY public.ordering_menu_item_modifier_defaults ADD CONSTRAINT ordering_menu_item_modifier_defaults_item_id_option_id_key UNIQUE (item_id, option_id);
ALTER TABLE ONLY public.ordering_menu_item_modifier_defaults ADD CONSTRAINT ordering_menu_item_modifier_defaults_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ordering_menu_item_modifier_groups ADD CONSTRAINT ordering_menu_item_modifier_groups_item_id_group_id_key UNIQUE (item_id, group_id);
ALTER TABLE ONLY public.ordering_menu_item_modifier_groups ADD CONSTRAINT ordering_menu_item_modifier_groups_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ordering_menu_item_variants ADD CONSTRAINT ordering_menu_item_variants_base_price_cents_check CHECK (base_price_cents >= 0);
ALTER TABLE ONLY public.ordering_menu_item_variants ADD CONSTRAINT ordering_menu_item_variants_item_id_name_key UNIQUE (item_id, name);
ALTER TABLE ONLY public.ordering_menu_item_variants ADD CONSTRAINT ordering_menu_item_variants_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ordering_menu_items ADD CONSTRAINT ordering_menu_items_base_price_cents_check CHECK (base_price_cents >= 0);
ALTER TABLE ONLY public.ordering_menu_items ADD CONSTRAINT ordering_menu_items_business_category_id_name_key UNIQUE (business, category_id, name);
ALTER TABLE ONLY public.ordering_menu_items ADD CONSTRAINT ordering_menu_items_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.ordering_menu_items ADD CONSTRAINT ordering_menu_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ordering_menu_variant_aliases ADD CONSTRAINT ordering_menu_variant_aliases_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ordering_menu_variant_aliases ADD CONSTRAINT ordering_menu_variant_aliases_variant_id_normalized_alias_key UNIQUE (variant_id, normalized_alias);
ALTER TABLE ONLY public.ordering_menu_variant_modifier_prices ADD CONSTRAINT ordering_menu_variant_modifier_prices_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ordering_menu_variant_modifier_prices ADD CONSTRAINT ordering_menu_variant_modifier_prices_variant_id_option_id_key UNIQUE (variant_id, option_id);
ALTER TABLE ONLY public.ordering_modifier_groups ADD CONSTRAINT ordering_modifier_groups_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.ordering_modifier_groups ADD CONSTRAINT ordering_modifier_groups_business_name_key UNIQUE (business, name);
ALTER TABLE ONLY public.ordering_modifier_groups ADD CONSTRAINT ordering_modifier_groups_check CHECK (max_selections >= min_selections);
ALTER TABLE ONLY public.ordering_modifier_groups ADD CONSTRAINT ordering_modifier_groups_max_selections_check CHECK (max_selections >= 1);
ALTER TABLE ONLY public.ordering_modifier_groups ADD CONSTRAINT ordering_modifier_groups_min_selections_check CHECK (min_selections >= 0);
ALTER TABLE ONLY public.ordering_modifier_groups ADD CONSTRAINT ordering_modifier_groups_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ordering_modifier_options ADD CONSTRAINT ordering_modifier_options_group_id_name_key UNIQUE (group_id, name);
ALTER TABLE ONLY public.ordering_modifier_options ADD CONSTRAINT ordering_modifier_options_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ordering_order_events ADD CONSTRAINT ordering_order_events_actor_type_check CHECK (actor_type = ANY (ARRAY['ai'::text, 'employee'::text, 'customer'::text, 'system'::text, 'payment'::text, 'web'::text]));
ALTER TABLE ONLY public.ordering_order_events ADD CONSTRAINT ordering_order_events_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ordering_order_item_combo_selections ADD CONSTRAINT ordering_order_item_combo_sel_order_item_id_group_id_option_key UNIQUE (order_item_id, group_id, option_id);
ALTER TABLE ONLY public.ordering_order_item_combo_selections ADD CONSTRAINT ordering_order_item_combo_selections_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ordering_order_item_modifiers ADD CONSTRAINT ordering_order_item_modifiers_order_item_id_group_id_option_key UNIQUE (order_item_id, group_id, option_id);
ALTER TABLE ONLY public.ordering_order_item_modifiers ADD CONSTRAINT ordering_order_item_modifiers_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ordering_order_item_modifiers ADD CONSTRAINT ordering_order_item_modifiers_quantity_check CHECK (quantity > 0);
