-- Baseline secondary and partial indexes.

CREATE INDEX app_users_active_idx ON public.app_users USING btree (active, role, email);
CREATE INDEX audit_events_business_created_idx ON public.audit_events USING btree (business, created_at DESC);
CREATE INDEX audit_events_entity_idx ON public.audit_events USING btree (business, entity_type, entity_id, created_at DESC);
CREATE INDEX bank_accounts_business_idx ON public.bank_accounts USING btree (business, institution_name, active);
CREATE INDEX bank_reconciliation_items_transaction_idx ON public.bank_reconciliation_items USING btree (bank_transaction_id);
CREATE INDEX bank_reconciliations_business_idx ON public.bank_reconciliations USING btree (business, statement_end_date DESC);
CREATE INDEX bank_transaction_splits_transaction_idx ON public.bank_transaction_splits USING btree (bank_transaction_id);
CREATE INDEX bank_transactions_business_date_idx ON public.bank_transactions USING btree (business, transaction_date DESC);
CREATE INDEX bank_transactions_review_idx ON public.bank_transactions USING btree (business, review_status, transaction_date DESC);
CREATE INDEX classification_rules_business_idx ON public.classification_rules USING btree (business, active, priority);
CREATE INDEX credential_reset_active_idx ON public.credential_reset_tokens USING btree (kind, email, expires_at DESC) WHERE (used_at IS NULL);
CREATE INDEX credit_card_statement_transactions_statement_idx ON public.credit_card_statement_transactions USING btree (statement_id, transaction_date);
CREATE INDEX credit_card_statements_business_date_idx ON public.credit_card_statements USING btree (business, statement_end_date DESC);
CREATE UNIQUE INDEX card_transfer_active_bank_unique ON public.credit_card_transfer_matches USING btree (bank_transaction_id) WHERE (status <> 'Ignored'::text);
CREATE UNIQUE INDEX card_transfer_active_card_unique ON public.credit_card_transfer_matches USING btree (card_transaction_id) WHERE (status <> 'Ignored'::text);
CREATE INDEX deli_wallboard_checks_date_idx ON public.deli_wallboard_task_checks USING btree (work_date, completed);
CREATE INDEX direct_deposit_business_status_idx ON public.direct_deposit_elections USING btree (business, status, assigned_at DESC);
CREATE INDEX direct_deposit_employee_idx ON public.direct_deposit_elections USING btree (employee_id, assigned_at DESC);
CREATE INDEX documents_business_created_idx ON public.documents USING btree (business, created_at DESC);
CREATE INDEX documents_status_idx ON public.documents USING btree (status);
CREATE INDEX employee_handbook_ack_business_idx ON public.employee_handbook_acknowledgments USING btree (business, handbook_version, content_hash, acknowledged_at DESC);
CREATE UNIQUE INDEX employee_handbook_ack_employee_hash_unique ON public.employee_handbook_acknowledgments USING btree (employee_id, handbook_version, content_hash);
CREATE INDEX employee_message_reads_employee_idx ON public.employee_message_reads USING btree (employee_id, read_at DESC);
CREATE INDEX employee_messages_business_created_idx ON public.employee_messages USING btree (business, created_at DESC) WHERE (deleted_at IS NULL);
CREATE INDEX employees_business_active_idx ON public.employees USING btree (business, active, name);
CREATE UNIQUE INDEX employees_business_email_unique ON public.employees USING btree (business, lower(email)) WHERE (email <> ''::text);
CREATE UNIQUE INDEX employees_business_pin_fingerprint_unique ON public.employees USING btree (business, pin_fingerprint) WHERE (pin_fingerprint <> ''::text);
CREATE INDEX employment_form_events_form_idx ON public.employment_form_events USING btree (form_id, created_at);
CREATE INDEX employment_forms_business_status_idx ON public.employment_forms USING btree (business, status, assigned_at DESC);
CREATE INDEX employment_forms_employee_idx ON public.employment_forms USING btree (employee_id, assigned_at DESC);
CREATE INDEX forecast_events_business_date_idx ON public.forecast_events USING btree (business, event_date, active);
CREATE INDEX integration_connections_business_idx ON public.integration_connections USING btree (business, provider, status);
CREATE INDEX integration_sync_runs_created_idx ON public.integration_sync_runs USING btree (started_at DESC);
CREATE INDEX inventory_items_business_active_idx ON public.inventory_items USING btree (business, active, name);
CREATE INDEX inventory_purchases_business_vendor_idx ON public.inventory_purchases USING btree (business, vendor, purchase_date DESC);
CREATE INDEX inventory_purchases_item_date_idx ON public.inventory_purchases USING btree (inventory_item_id, purchase_date DESC);
CREATE INDEX invoice_payment_allocations_transaction_idx ON public.invoice_payment_allocations USING btree (bank_transaction_id);
CREATE INDEX invoices_business_status_idx ON public.invoices USING btree (business, status, due_date, invoice_date DESC);
CREATE INDEX journal_entries_business_date_idx ON public.journal_entries USING btree (business, entry_date DESC);
CREATE INDEX journal_lines_entry_idx ON public.journal_lines USING btree (entry_id);
CREATE INDEX manual_time_entry_audit_business_created_idx ON public.manual_time_entry_audit USING btree (business, created_at DESC);
CREATE INDEX manual_time_entry_audit_employee_idx ON public.manual_time_entry_audit USING btree (employee_id, created_at DESC);
CREATE INDEX missed_shift_business_status_idx ON public.missed_shift_cases USING btree (business, status, scheduled_start DESC);
CREATE INDEX missed_shift_employee_idx ON public.missed_shift_cases USING btree (employee_id, scheduled_start DESC);
CREATE INDEX oauth_state_nonces_active_idx ON public.oauth_state_nonces USING btree (purpose, expires_at) WHERE (used_at IS NULL);
CREATE INDEX operation_issues_status_idx ON public.operation_issues USING btree (status, severity, last_seen_at DESC);
CREATE INDEX ordering_call_sessions_active_idx ON public.ordering_call_sessions USING btree (business, state, updated_at DESC);
CREATE INDEX ordering_call_sessions_phone_idx ON public.ordering_call_sessions USING btree (caller_phone, started_at DESC);
CREATE INDEX ordering_combo_options_group_idx ON public.ordering_combo_options USING btree (group_id, active, available, sort_order);
CREATE INDEX ordering_customer_addresses_customer_idx ON public.ordering_customer_addresses USING btree (customer_id, active);
CREATE INDEX ordering_customer_phones_lookup_idx ON public.ordering_customer_phones USING btree (normalized_phone);
CREATE INDEX ordering_customers_business_name_idx ON public.ordering_customers USING btree (business, active, display_name);
CREATE INDEX ordering_loyalty_ledger_balance_idx ON public.ordering_loyalty_ledger USING btree (program_id, customer_id, created_at);
CREATE INDEX ordering_loyalty_ledger_order_idx ON public.ordering_loyalty_ledger USING btree (order_id) WHERE (order_id IS NOT NULL);
CREATE INDEX ordering_menu_categories_business_idx ON public.ordering_menu_categories USING btree (business, active, sort_order, name);
CREATE INDEX ordering_menu_item_combos_item_idx ON public.ordering_menu_item_combos USING btree (item_id, active, sort_order);
CREATE INDEX ordering_item_modifier_defaults_idx ON public.ordering_menu_item_modifier_defaults USING btree (item_id, active);
CREATE INDEX ordering_item_modifier_groups_item_idx ON public.ordering_menu_item_modifier_groups USING btree (item_id, sort_order);
CREATE UNIQUE INDEX ordering_menu_item_one_default_variant_idx ON public.ordering_menu_item_variants USING btree (item_id) WHERE ((default_variant = true) AND (active = true));
CREATE INDEX ordering_menu_item_variants_item_idx ON public.ordering_menu_item_variants USING btree (item_id, active, available, sort_order, name);
CREATE INDEX ordering_menu_items_business_category_idx ON public.ordering_menu_items USING btree (business, category_id, active, available, sort_order, name);
CREATE INDEX ordering_menu_variant_aliases_lookup_idx ON public.ordering_menu_variant_aliases USING btree (normalized_alias, active);
CREATE INDEX ordering_variant_modifier_prices_lookup_idx ON public.ordering_menu_variant_modifier_prices USING btree (variant_id, option_id, active);
CREATE INDEX ordering_modifier_options_group_idx ON public.ordering_modifier_options USING btree (group_id, active, available, sort_order, name);
CREATE INDEX ordering_order_events_order_idx ON public.ordering_order_events USING btree (order_id, order_version, created_at);
CREATE INDEX ordering_order_item_combo_idx ON public.ordering_order_item_combo_selections USING btree (order_item_id, group_id);
CREATE INDEX ordering_order_item_modifiers_item_idx ON public.ordering_order_item_modifiers USING btree (order_item_id, group_id);
CREATE INDEX ordering_order_items_order_idx ON public.ordering_order_items USING btree (order_id, sort_order, created_at);
CREATE INDEX ordering_orders_3cx_call_idx ON public.ordering_orders USING btree (three_cx_call_id) WHERE (three_cx_call_id <> ''::text);
CREATE INDEX ordering_orders_active_idx ON public.ordering_orders USING btree (business, status, updated_at DESC);
CREATE INDEX ordering_orders_business_created_idx ON public.ordering_orders USING btree (business, created_at DESC);
CREATE INDEX ordering_orders_customer_idx ON public.ordering_orders USING btree (customer_id, created_at DESC);
CREATE INDEX ordering_sms_verifications_order_idx ON public.ordering_sms_verifications USING btree (order_id, created_at DESC);
CREATE INDEX ordering_sms_verifications_phone_idx ON public.ordering_sms_verifications USING btree (phone, created_at DESC);
CREATE INDEX ordering_upsell_rules_business_idx ON public.ordering_upsell_rules USING btree (business, active, priority DESC);
CREATE INDEX overtime_risk_alerts_open_idx ON public.overtime_risk_alerts USING btree (business, status, week_start);
CREATE INDEX owner_message_reads_reader_idx ON public.owner_message_reads USING btree (reader_email, read_at DESC);
CREATE INDEX payroll_audit_events_business_idx ON public.payroll_audit_events USING btree (business, created_at DESC);
CREATE INDEX payroll_run_versions_week_idx ON public.payroll_run_versions USING btree (business, week_start DESC, version DESC);
CREATE INDEX push_delivery_log_created_idx ON public.push_delivery_log USING btree (created_at DESC);
CREATE INDEX push_subscriptions_employee_idx ON public.push_subscriptions USING btree (business, employee_id, active);
CREATE INDEX push_subscriptions_owner_idx ON public.push_subscriptions USING btree (owner_email, active);
CREATE INDEX receipt_documents_business_idx ON public.receipt_documents USING btree (business, receipt_date DESC, created_at DESC);
CREATE INDEX receipt_documents_status_idx ON public.receipt_documents USING btree (business, ocr_status, created_at DESC);
CREATE UNIQUE INDEX receipt_active_document_unique ON public.receipt_transaction_matches USING btree (receipt_id) WHERE (status <> 'Ignored'::text);
CREATE UNIQUE INDEX receipt_active_transaction_unique ON public.receipt_transaction_matches USING btree (bank_transaction_id) WHERE (status = 'Matched'::text);
CREATE INDEX recipe_components_recipe_idx ON public.recipe_components USING btree (recipe_id);
CREATE INDEX recipes_business_active_idx ON public.recipes USING btree (business, active, product_name);
CREATE INDEX recurring_invoice_templates_due_idx ON public.recurring_invoice_templates USING btree (business, active, next_issue_date);
CREATE INDEX rezku_import_batches_created_idx ON public.rezku_import_batches USING btree (imported_at DESC);
CREATE INDEX rezku_inbound_emails_received_idx ON public.rezku_inbound_emails USING btree (received_at DESC);
CREATE INDEX rezku_inbound_reports_email_idx ON public.rezku_inbound_reports USING btree (email_id, processed_at);
CREATE INDEX rezku_orders_opened_idx ON public.rezku_orders USING btree (opened_at);
CREATE INDEX rezku_orders_order_idx ON public.rezku_orders USING btree (order_id);
CREATE INDEX rezku_product_sales_category_idx ON public.rezku_product_sales USING btree (category, business_date DESC);
CREATE INDEX rezku_product_sales_date_idx ON public.rezku_product_sales USING btree (business_date DESC);
CREATE INDEX rezku_product_sales_product_idx ON public.rezku_product_sales USING btree (product, business_date DESC);
CREATE INDEX rezku_product_sales_batches_date_idx ON public.rezku_product_sales_import_batches USING btree (business_date DESC, imported_at DESC);
CREATE INDEX rezku_shifts_clock_idx ON public.rezku_shifts USING btree (clock_in, clock_out);
CREATE INDEX rezku_transactions_time_idx ON public.rezku_transactions USING btree (transaction_time);
CREATE INDEX rezku_void_events_order_idx ON public.rezku_void_events USING btree (order_id, transaction_id);
CREATE INDEX rezku_void_events_time_idx ON public.rezku_void_events USING btree (voided_at DESC);
CREATE INDEX rezku_void_events_type_idx ON public.rezku_void_events USING btree (void_type, voided_at DESC);
CREATE INDEX rezku_void_import_batches_created_idx ON public.rezku_void_import_batches USING btree (imported_at DESC);
CREATE INDEX schedule_publication_delivery_pending_idx ON public.schedule_publication_deliveries USING btree (status, next_attempt_at, created_at) WHERE (status <> 'Sent'::text);
CREATE INDEX schedule_publications_business_week_idx ON public.schedule_publications USING btree (business, week_start, published_at DESC);
CREATE UNIQUE INDEX schedule_publications_idempotency_idx ON public.schedule_publications USING btree (idempotency_key) WHERE (idempotency_key IS NOT NULL);
CREATE INDEX schedule_shifts_business_start_idx ON public.schedule_shifts USING btree (business, starts_at, status);
CREATE INDEX schedule_shifts_employee_idx ON public.schedule_shifts USING btree (employee_id, starts_at);
CREATE INDEX security_rate_limits_blocked_idx ON public.security_rate_limits USING btree (blocked_until) WHERE (blocked_until IS NOT NULL);
CREATE INDEX shift_change_log_business_created_idx ON public.shift_change_log USING btree (business, created_at DESC);
CREATE INDEX shift_requests_business_status_idx ON public.shift_requests USING btree (business, status, created_at DESC);
CREATE INDEX sms_consent_events_phone_idx ON public.sms_consent_events USING btree (phone, created_at DESC);
CREATE UNIQUE INDEX sms_consent_events_provider_message_unique ON public.sms_consent_events USING btree (provider_message_id) WHERE (provider_message_id <> ''::text);
CREATE INDEX square_catalog_type_idx ON public.square_catalog_objects USING btree (object_type, active, name);
CREATE INDEX square_inventory_location_idx ON public.square_inventory_counts USING btree (location_id, state, quantity);
CREATE INDEX square_order_lines_catalog_idx ON public.square_order_lines USING btree (catalog_object_id);
CREATE INDEX square_orders_date_idx ON public.square_orders USING btree (created_at_square DESC, state);
CREATE INDEX square_payments_date_idx ON public.square_payments USING btree (created_at_square DESC);
CREATE INDEX square_webhook_events_received_idx ON public.square_webhook_events USING btree (received_at DESC, status);
CREATE INDEX three_cx_cdr_ended_idx ON public.three_cx_cdr_records USING btree (ended_at DESC);
CREATE INDEX three_cx_cdr_event_at_idx ON public.three_cx_cdr_records USING btree (event_at);
CREATE INDEX three_cx_cdr_history_idx ON public.three_cx_cdr_records USING btree (history_id);
CREATE INDEX three_cx_cdr_phone_idx ON public.three_cx_cdr_records USING btree (from_no, to_no);
CREATE INDEX correction_business_status_idx ON public.time_correction_requests USING btree (business, status, created_at DESC);
CREATE UNIQUE INDEX one_open_time_entry_per_employee ON public.time_entries USING btree (employee_id) WHERE (clock_out IS NULL);
CREATE INDEX time_entries_business_clock_idx ON public.time_entries USING btree (business, clock_in DESC);
CREATE INDEX time_entry_adjustments_source_idx ON public.time_entry_adjustments USING btree (source_type, source_id, created_at DESC);
CREATE INDEX time_off_business_status_idx ON public.time_off_requests USING btree (business, status, starts_on);
CREATE INDEX tip_overrides_week_idx ON public.tip_overrides USING btree (business, week_start, created_at);
CREATE INDEX vendor_bill_lines_bill_idx ON public.vendor_bill_lines USING btree (bill_id, line_number);
CREATE INDEX vendor_bills_business_due_idx ON public.vendor_bills USING btree (business, status, due_date);
CREATE UNIQUE INDEX vendor_bills_invoice_unique ON public.vendor_bills USING btree (business, lower(vendor), invoice_number) WHERE ((invoice_number <> ''::text) AND (status <> 'Void'::text));
CREATE INDEX weather_daily_source_idx ON public.weather_daily USING btree (source_kind, weather_date);
