-- Baseline non-foreign-key constraints, part 2.

ALTER TABLE ONLY public.ordering_order_item_modifiers ADD CONSTRAINT ordering_order_item_modifiers_selection_state_check CHECK (selection_state = ANY (ARRAY['selected'::text, 'removed'::text, 'extra'::text]));
ALTER TABLE ONLY public.ordering_order_items ADD CONSTRAINT ordering_order_items_line_total_cents_check CHECK (line_total_cents >= 0);
ALTER TABLE ONLY public.ordering_order_items ADD CONSTRAINT ordering_order_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ordering_order_items ADD CONSTRAINT ordering_order_items_quantity_check CHECK (quantity > 0);
ALTER TABLE ONLY public.ordering_order_items ADD CONSTRAINT ordering_order_items_unit_price_cents_check CHECK (unit_price_cents >= 0);
ALTER TABLE ONLY public.ordering_orders ADD CONSTRAINT ordering_orders_amount_due_cents_check CHECK (amount_due_cents >= 0);
ALTER TABLE ONLY public.ordering_orders ADD CONSTRAINT ordering_orders_arrival_status_check CHECK (arrival_status = ANY (ARRAY['not_expected'::text, 'waiting'::text, 'arrived'::text, 'acknowledged'::text, 'completed'::text]));
ALTER TABLE ONLY public.ordering_orders ADD CONSTRAINT ordering_orders_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.ordering_orders ADD CONSTRAINT ordering_orders_discount_cents_check CHECK (discount_cents >= 0);
ALTER TABLE ONLY public.ordering_orders ADD CONSTRAINT ordering_orders_paid_cents_check CHECK (paid_cents >= 0);
ALTER TABLE ONLY public.ordering_orders ADD CONSTRAINT ordering_orders_payment_status_check CHECK (payment_status = ANY (ARRAY['unpaid'::text, 'pending'::text, 'partially_paid'::text, 'paid'::text, 'partially_refunded'::text, 'refunded'::text, 'failed'::text]));
ALTER TABLE ONLY public.ordering_orders ADD CONSTRAINT ordering_orders_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ordering_orders ADD CONSTRAINT ordering_orders_service_type_check CHECK (service_type = ANY (ARRAY['undecided'::text, 'pickup'::text, 'delivery'::text, 'no_contact_delivery'::text, 'dine_in'::text, 'curbside'::text, 'bar'::text]));
ALTER TABLE ONLY public.ordering_orders ADD CONSTRAINT ordering_orders_source_check CHECK (source = ANY (ARRAY['pos'::text, 'web'::text, 'ai_phone'::text, 'kiosk'::text, 'import'::text]));
ALTER TABLE ONLY public.ordering_orders ADD CONSTRAINT ordering_orders_status_check CHECK (status = ANY (ARRAY['draft'::text, 'confirmed'::text, 'sent_to_kitchen'::text, 'in_progress'::text, 'ready'::text, 'completed'::text, 'cancelled'::text]));
ALTER TABLE ONLY public.ordering_orders ADD CONSTRAINT ordering_orders_subtotal_cents_check CHECK (subtotal_cents >= 0);
ALTER TABLE ONLY public.ordering_orders ADD CONSTRAINT ordering_orders_tax_cents_check CHECK (tax_cents >= 0);
ALTER TABLE ONLY public.ordering_orders ADD CONSTRAINT ordering_orders_tip_cents_check CHECK (tip_cents >= 0);
ALTER TABLE ONLY public.ordering_orders ADD CONSTRAINT ordering_orders_total_cents_check CHECK (total_cents >= 0);
ALTER TABLE ONLY public.ordering_orders ADD CONSTRAINT ordering_orders_version_check CHECK (version >= 1);
ALTER TABLE ONLY public.ordering_sms_verifications ADD CONSTRAINT ordering_sms_verifications_attempt_count_check CHECK (attempt_count >= 0);
ALTER TABLE ONLY public.ordering_sms_verifications ADD CONSTRAINT ordering_sms_verifications_max_attempts_check CHECK (max_attempts > 0);
ALTER TABLE ONLY public.ordering_sms_verifications ADD CONSTRAINT ordering_sms_verifications_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ordering_sms_verifications ADD CONSTRAINT ordering_sms_verifications_purpose_check CHECK (purpose = 'unpaid_web_order'::text);
ALTER TABLE ONLY public.ordering_sms_verifications ADD CONSTRAINT ordering_sms_verifications_resend_count_check CHECK (resend_count >= 0);
ALTER TABLE ONLY public.ordering_sms_verifications ADD CONSTRAINT ordering_sms_verifications_status_check CHECK (status = ANY (ARRAY['pending'::text, 'verified'::text, 'expired'::text, 'locked'::text, 'invalidated'::text]));
ALTER TABLE ONLY public.ordering_upsell_rules ADD CONSTRAINT ordering_upsell_rules_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.ordering_upsell_rules ADD CONSTRAINT ordering_upsell_rules_business_name_key UNIQUE (business, name);
ALTER TABLE ONLY public.ordering_upsell_rules ADD CONSTRAINT ordering_upsell_rules_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.overtime_risk_alerts ADD CONSTRAINT overtime_risk_alerts_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.overtime_risk_alerts ADD CONSTRAINT overtime_risk_alerts_business_employee_id_week_start_key UNIQUE (business, employee_id, week_start);
ALTER TABLE ONLY public.overtime_risk_alerts ADD CONSTRAINT overtime_risk_alerts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.overtime_risk_alerts ADD CONSTRAINT overtime_risk_alerts_risk_level_check CHECK (risk_level = ANY (ARRAY['warning'::text, 'overtime'::text]));
ALTER TABLE ONLY public.overtime_risk_alerts ADD CONSTRAINT overtime_risk_alerts_status_check CHECK (status = ANY (ARRAY['Open'::text, 'Resolved'::text]));
ALTER TABLE ONLY public.owner_message_notification_state ADD CONSTRAINT owner_message_notification_state_pkey PRIMARY KEY (reader_email);
ALTER TABLE ONLY public.owner_message_reads ADD CONSTRAINT owner_message_reads_pkey PRIMARY KEY (message_id, reader_email);
ALTER TABLE ONLY public.payroll_audit_events ADD CONSTRAINT payroll_audit_events_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.payroll_audit_events ADD CONSTRAINT payroll_audit_events_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.payroll_run_versions ADD CONSTRAINT payroll_run_versions_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.payroll_run_versions ADD CONSTRAINT payroll_run_versions_business_week_start_version_key UNIQUE (business, week_start, version);
ALTER TABLE ONLY public.payroll_run_versions ADD CONSTRAINT payroll_run_versions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.payroll_run_versions ADD CONSTRAINT payroll_run_versions_status_check CHECK (status = ANY (ARRAY['Draft'::text, 'Locked'::text]));
ALTER TABLE ONLY public.payroll_runs ADD CONSTRAINT payroll_runs_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.payroll_runs ADD CONSTRAINT payroll_runs_business_week_start_key UNIQUE (business, week_start);
ALTER TABLE ONLY public.payroll_runs ADD CONSTRAINT payroll_runs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.payroll_runs ADD CONSTRAINT payroll_runs_status_check CHECK (status = ANY (ARRAY['Calculated'::text, 'Reviewed'::text, 'Locked'::text]));
ALTER TABLE ONLY public.push_delivery_log ADD CONSTRAINT push_delivery_log_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.push_delivery_log ADD CONSTRAINT push_delivery_log_status_check CHECK (status = ANY (ARRAY['Delivered'::text, 'Failed'::text, 'Expired'::text]));
ALTER TABLE ONLY public.push_subscriptions ADD CONSTRAINT push_subscriptions_audience_type_check CHECK (audience_type = ANY (ARRAY['owner'::text, 'employee'::text]));
ALTER TABLE ONLY public.push_subscriptions ADD CONSTRAINT push_subscriptions_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.push_subscriptions ADD CONSTRAINT push_subscriptions_check CHECK (audience_type = 'owner'::text AND owner_email <> ''::text AND employee_id IS NULL OR audience_type = 'employee'::text AND employee_id IS NOT NULL AND business IS NOT NULL);
ALTER TABLE ONLY public.push_subscriptions ADD CONSTRAINT push_subscriptions_endpoint_key UNIQUE (endpoint);
ALTER TABLE ONLY public.push_subscriptions ADD CONSTRAINT push_subscriptions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.receipt_documents ADD CONSTRAINT receipt_documents_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.receipt_documents ADD CONSTRAINT receipt_documents_ocr_status_check CHECK (ocr_status = ANY (ARRAY['Pending'::text, 'Processed'::text, 'Failed'::text, 'Needs Configuration'::text, 'Unsupported'::text]));
ALTER TABLE ONLY public.receipt_documents ADD CONSTRAINT receipt_documents_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.receipt_documents ADD CONSTRAINT receipt_documents_source_check CHECK (source = ANY (ARRAY['Upload'::text, 'Google Drive'::text]));
ALTER TABLE ONLY public.receipt_documents ADD CONSTRAINT receipt_documents_source_key_key UNIQUE (source_key);
ALTER TABLE ONLY public.receipt_transaction_matches ADD CONSTRAINT receipt_transaction_matches_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.receipt_transaction_matches ADD CONSTRAINT receipt_transaction_matches_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.receipt_transaction_matches ADD CONSTRAINT receipt_transaction_matches_receipt_id_bank_transaction_id_key UNIQUE (receipt_id, bank_transaction_id);
ALTER TABLE ONLY public.receipt_transaction_matches ADD CONSTRAINT receipt_transaction_matches_status_check CHECK (status = ANY (ARRAY['Suggested'::text, 'Matched'::text, 'Ignored'::text]));
ALTER TABLE ONLY public.recipe_components ADD CONSTRAINT recipe_components_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.recipe_components ADD CONSTRAINT recipe_components_quantity_check CHECK (quantity > 0::numeric);
ALTER TABLE ONLY public.recipe_components ADD CONSTRAINT recipe_components_recipe_id_inventory_item_id_key UNIQUE (recipe_id, inventory_item_id);
ALTER TABLE ONLY public.recipe_components ADD CONSTRAINT recipe_components_waste_percent_check CHECK (waste_percent >= 0::numeric AND waste_percent < 100::numeric);
ALTER TABLE ONLY public.recipes ADD CONSTRAINT recipes_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.recipes ADD CONSTRAINT recipes_business_product_name_key UNIQUE (business, product_name);
ALTER TABLE ONLY public.recipes ADD CONSTRAINT recipes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.recipes ADD CONSTRAINT recipes_selling_price_check CHECK (selling_price >= 0::numeric);
ALTER TABLE ONLY public.recipes ADD CONSTRAINT recipes_yield_quantity_check CHECK (yield_quantity > 0::numeric);
ALTER TABLE ONLY public.recurring_invoice_templates ADD CONSTRAINT recurring_invoice_templates_amount_check CHECK (amount > 0::numeric);
ALTER TABLE ONLY public.recurring_invoice_templates ADD CONSTRAINT recurring_invoice_templates_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.recurring_invoice_templates ADD CONSTRAINT recurring_invoice_templates_cadence_check CHECK (cadence = ANY (ARRAY['Monthly'::text, 'Quarterly'::text, 'Annual'::text]));
ALTER TABLE ONLY public.recurring_invoice_templates ADD CONSTRAINT recurring_invoice_templates_due_days_check CHECK (due_days >= 0 AND due_days <= 365);
ALTER TABLE ONLY public.recurring_invoice_templates ADD CONSTRAINT recurring_invoice_templates_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.rezku_data_migrations ADD CONSTRAINT rezku_data_migrations_pkey PRIMARY KEY (migration_key);
ALTER TABLE ONLY public.rezku_import_batches ADD CONSTRAINT rezku_import_batches_business_check CHECK (business = 'Corner Deli'::text);
ALTER TABLE ONLY public.rezku_import_batches ADD CONSTRAINT rezku_import_batches_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.rezku_import_batches ADD CONSTRAINT rezku_import_batches_report_type_check CHECK (report_type = ANY (ARRAY['shifts'::text, 'orders'::text, 'transactions'::text]));
ALTER TABLE ONLY public.rezku_inbound_emails ADD CONSTRAINT rezku_inbound_emails_pkey PRIMARY KEY (email_id);
ALTER TABLE ONLY public.rezku_inbound_emails ADD CONSTRAINT rezku_inbound_emails_status_check CHECK (status = ANY (ARRAY['Received'::text, 'Processing'::text, 'Processed'::text, 'Partial'::text, 'Failed'::text]));
ALTER TABLE ONLY public.rezku_inbound_reports ADD CONSTRAINT rezku_inbound_reports_email_id_file_name_key UNIQUE (email_id, file_name);
ALTER TABLE ONLY public.rezku_inbound_reports ADD CONSTRAINT rezku_inbound_reports_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.rezku_inbound_reports ADD CONSTRAINT rezku_inbound_reports_status_check CHECK (status = ANY (ARRAY['Processing'::text, 'Processed'::text, 'Failed'::text]));
ALTER TABLE ONLY public.rezku_orders ADD CONSTRAINT rezku_orders_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.rezku_orders ADD CONSTRAINT rezku_orders_source_key_key UNIQUE (source_key);
ALTER TABLE ONLY public.rezku_product_sales ADD CONSTRAINT rezku_product_sales_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.rezku_product_sales ADD CONSTRAINT rezku_product_sales_source_key_key UNIQUE (source_key);
ALTER TABLE ONLY public.rezku_product_sales_import_batches ADD CONSTRAINT rezku_product_sales_import_batches_business_check CHECK (business = 'Corner Deli'::text);
ALTER TABLE ONLY public.rezku_product_sales_import_batches ADD CONSTRAINT rezku_product_sales_import_batches_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.rezku_product_sales_import_batches ADD CONSTRAINT rezku_product_sales_import_batches_report_type_check CHECK (report_type = 'sales_by_product'::text);
ALTER TABLE ONLY public.rezku_shifts ADD CONSTRAINT rezku_shifts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.rezku_shifts ADD CONSTRAINT rezku_shifts_source_key_key UNIQUE (source_key);
ALTER TABLE ONLY public.rezku_transactions ADD CONSTRAINT rezku_transactions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.rezku_transactions ADD CONSTRAINT rezku_transactions_source_key_key UNIQUE (source_key);
ALTER TABLE ONLY public.rezku_void_events ADD CONSTRAINT rezku_void_events_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.rezku_void_events ADD CONSTRAINT rezku_void_events_source_key_key UNIQUE (source_key);
ALTER TABLE ONLY public.rezku_void_events ADD CONSTRAINT rezku_void_events_void_type_check CHECK (void_type = ANY (ARRAY['Product'::text, 'Transaction'::text]));
ALTER TABLE ONLY public.rezku_void_import_batches ADD CONSTRAINT rezku_void_import_batches_business_check CHECK (business = 'Corner Deli'::text);
ALTER TABLE ONLY public.rezku_void_import_batches ADD CONSTRAINT rezku_void_import_batches_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.rezku_void_import_batches ADD CONSTRAINT rezku_void_import_batches_report_type_check CHECK (report_type = ANY (ARRAY['product_voids'::text, 'transaction_voids'::text]));
ALTER TABLE ONLY public.schedule_publication_deliveries ADD CONSTRAINT schedule_publication_deliveri_publication_id_employee_id_ch_key UNIQUE (publication_id, employee_id, channel);
ALTER TABLE ONLY public.schedule_publication_deliveries ADD CONSTRAINT schedule_publication_deliveries_channel_check CHECK (channel = 'Email'::text);
ALTER TABLE ONLY public.schedule_publication_deliveries ADD CONSTRAINT schedule_publication_deliveries_idempotency_key_key UNIQUE (idempotency_key);
ALTER TABLE ONLY public.schedule_publication_deliveries ADD CONSTRAINT schedule_publication_deliveries_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.schedule_publication_deliveries ADD CONSTRAINT schedule_publication_deliveries_status_check CHECK (status = ANY (ARRAY['Pending'::text, 'Sending'::text, 'Sent'::text, 'Failed'::text, 'Waiting Configuration'::text]));
ALTER TABLE ONLY public.schedule_publications ADD CONSTRAINT schedule_publications_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.schedule_publications ADD CONSTRAINT schedule_publications_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.schedule_shifts ADD CONSTRAINT schedule_shifts_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.schedule_shifts ADD CONSTRAINT schedule_shifts_check CHECK (ends_at > starts_at);
ALTER TABLE ONLY public.schedule_shifts ADD CONSTRAINT schedule_shifts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.schedule_shifts ADD CONSTRAINT schedule_shifts_status_check CHECK (status = ANY (ARRAY['Draft'::text, 'Published'::text, 'Open'::text, 'Cancelled'::text]));
ALTER TABLE ONLY public.scheduler_runs ADD CONSTRAINT scheduler_runs_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.scheduler_runs ADD CONSTRAINT scheduler_runs_run_key_key UNIQUE (run_key);
ALTER TABLE ONLY public.scheduler_runs ADD CONSTRAINT scheduler_runs_status_check CHECK (status = ANY (ARRAY['Running'::text, 'Success'::text, 'Failed'::text, 'Skipped'::text]));
ALTER TABLE ONLY public.schema_migrations ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (migration_name);
ALTER TABLE ONLY public.security_rate_limits ADD CONSTRAINT security_rate_limits_attempts_check CHECK (attempts >= 0);
ALTER TABLE ONLY public.security_rate_limits ADD CONSTRAINT security_rate_limits_pkey PRIMARY KEY (scope, discriminator_hash);
ALTER TABLE ONLY public.shift_change_log ADD CONSTRAINT shift_change_log_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.shift_change_log ADD CONSTRAINT shift_change_log_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.shift_requests ADD CONSTRAINT shift_requests_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.shift_requests ADD CONSTRAINT shift_requests_employee_response_check CHECK (employee_response = ANY (ARRAY['Pending'::text, 'Accepted'::text, 'Declined'::text, 'Not Required'::text]));
ALTER TABLE ONLY public.shift_requests ADD CONSTRAINT shift_requests_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.shift_requests ADD CONSTRAINT shift_requests_request_type_check CHECK (request_type = ANY (ARRAY['Claim'::text, 'Offer'::text, 'Swap'::text]));
ALTER TABLE ONLY public.shift_requests ADD CONSTRAINT shift_requests_status_check CHECK (status = ANY (ARRAY['Pending'::text, 'Approved'::text, 'Rejected'::text, 'Cancelled'::text]));
ALTER TABLE ONLY public.sms_consent_events ADD CONSTRAINT sms_consent_events_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.sms_consent_events ADD CONSTRAINT sms_consent_events_event_type_check CHECK (event_type = ANY (ARRAY['Opt In'::text, 'Opt Out'::text, 'Help'::text]));
ALTER TABLE ONLY public.sms_consent_events ADD CONSTRAINT sms_consent_events_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.square_catalog_objects ADD CONSTRAINT square_catalog_objects_external_object_id_key UNIQUE (external_object_id);
ALTER TABLE ONLY public.square_catalog_objects ADD CONSTRAINT square_catalog_objects_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.square_deposit_match_payments ADD CONSTRAINT square_deposit_match_payments_pkey PRIMARY KEY (match_id, square_payment_id);
ALTER TABLE ONLY public.square_deposit_match_payments ADD CONSTRAINT square_deposit_match_payments_square_payment_id_key UNIQUE (square_payment_id);
ALTER TABLE ONLY public.square_deposit_matches ADD CONSTRAINT square_deposit_matches_bank_transaction_id_key UNIQUE (bank_transaction_id);
ALTER TABLE ONLY public.square_deposit_matches ADD CONSTRAINT square_deposit_matches_business_check CHECK (business = 'Tiki'::text);
ALTER TABLE ONLY public.square_deposit_matches ADD CONSTRAINT square_deposit_matches_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.square_deposit_matches ADD CONSTRAINT square_deposit_matches_status_check CHECK (status = ANY (ARRAY['Suggested'::text, 'Matched'::text, 'Ignored'::text]));
ALTER TABLE ONLY public.square_inventory_counts ADD CONSTRAINT square_inventory_counts_catalog_object_id_location_id_state_key UNIQUE (catalog_object_id, location_id, state);
ALTER TABLE ONLY public.square_inventory_counts ADD CONSTRAINT square_inventory_counts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.square_order_lines ADD CONSTRAINT square_order_lines_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.square_order_lines ADD CONSTRAINT square_order_lines_square_order_id_external_line_id_key UNIQUE (square_order_id, external_line_id);
ALTER TABLE ONLY public.square_orders ADD CONSTRAINT square_orders_external_order_id_key UNIQUE (external_order_id);
ALTER TABLE ONLY public.square_orders ADD CONSTRAINT square_orders_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.square_payments ADD CONSTRAINT square_payments_business_check CHECK (business = 'Tiki'::text);
ALTER TABLE ONLY public.square_payments ADD CONSTRAINT square_payments_external_payment_id_key UNIQUE (external_payment_id);
ALTER TABLE ONLY public.square_payments ADD CONSTRAINT square_payments_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.square_webhook_events ADD CONSTRAINT square_webhook_events_event_id_key UNIQUE (event_id);
ALTER TABLE ONLY public.square_webhook_events ADD CONSTRAINT square_webhook_events_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.square_webhook_events ADD CONSTRAINT square_webhook_events_status_check CHECK (status = ANY (ARRAY['Received'::text, 'Processed'::text, 'Ignored'::text, 'Failed'::text]));
ALTER TABLE ONLY public.three_cx_cdr_records ADD CONSTRAINT three_cx_cdr_records_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.three_cx_cdr_records ADD CONSTRAINT three_cx_cdr_records_record_key_key UNIQUE (record_key);
ALTER TABLE ONLY public.three_cx_missed_call_notifications ADD CONSTRAINT three_cx_missed_call_notifications_history_id_key UNIQUE (history_id);
ALTER TABLE ONLY public.three_cx_missed_call_notifications ADD CONSTRAINT three_cx_missed_call_notifications_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.time_correction_requests ADD CONSTRAINT time_correction_requests_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.time_correction_requests ADD CONSTRAINT time_correction_requests_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.time_correction_requests ADD CONSTRAINT time_correction_requests_source_type_check CHECK (source_type = ANY (ARRAY['Corner Ops'::text, 'Rezku'::text]));
ALTER TABLE ONLY public.time_correction_requests ADD CONSTRAINT time_correction_requests_status_check CHECK (status = ANY (ARRAY['Pending'::text, 'Approved'::text, 'Rejected'::text, 'Cancelled'::text]));
ALTER TABLE ONLY public.time_entries ADD CONSTRAINT time_entries_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.time_entries ADD CONSTRAINT time_entries_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.time_entries ADD CONSTRAINT time_entries_role_group_check CHECK (role_group = ANY (ARRAY['Driver'::text, 'In-House'::text, 'Ignore'::text]));
ALTER TABLE ONLY public.time_entries ADD CONSTRAINT time_entries_status_check CHECK (status = ANY (ARRAY['Open'::text, 'Complete'::text, 'Needs Review'::text, 'Corrected'::text]));
ALTER TABLE ONLY public.time_entry_adjustments ADD CONSTRAINT time_entry_adjustments_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.time_entry_adjustments ADD CONSTRAINT time_entry_adjustments_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.time_entry_adjustments ADD CONSTRAINT time_entry_adjustments_source_type_check CHECK (source_type = ANY (ARRAY['Tiki'::text, 'Rezku'::text]));
ALTER TABLE ONLY public.time_off_requests ADD CONSTRAINT time_off_requests_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.time_off_requests ADD CONSTRAINT time_off_requests_check CHECK (ends_on >= starts_on);
ALTER TABLE ONLY public.time_off_requests ADD CONSTRAINT time_off_requests_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.time_off_requests ADD CONSTRAINT time_off_requests_status_check CHECK (status = ANY (ARRAY['Pending'::text, 'Approved'::text, 'Rejected'::text, 'Cancelled'::text]));
ALTER TABLE ONLY public.tip_overrides ADD CONSTRAINT tip_overrides_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.tip_overrides ADD CONSTRAINT tip_overrides_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.vendor_bill_lines ADD CONSTRAINT vendor_bill_lines_bill_id_line_number_key UNIQUE (bill_id, line_number);
ALTER TABLE ONLY public.vendor_bill_lines ADD CONSTRAINT vendor_bill_lines_line_total_check CHECK (line_total >= 0::numeric);
ALTER TABLE ONLY public.vendor_bill_lines ADD CONSTRAINT vendor_bill_lines_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.vendor_bill_lines ADD CONSTRAINT vendor_bill_lines_quantity_check CHECK (quantity > 0::numeric);
ALTER TABLE ONLY public.vendor_bill_lines ADD CONSTRAINT vendor_bill_lines_unit_price_check CHECK (unit_price >= 0::numeric);
ALTER TABLE ONLY public.vendor_bills ADD CONSTRAINT vendor_bills_business_check CHECK (business = ANY (ARRAY['Corner Deli'::text, 'Tiki'::text]));
ALTER TABLE ONLY public.vendor_bills ADD CONSTRAINT vendor_bills_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.vendor_bills ADD CONSTRAINT vendor_bills_status_check CHECK (status = ANY (ARRAY['Draft'::text, 'Open'::text, 'Paid'::text, 'Void'::text]));
ALTER TABLE ONLY public.vendor_bills ADD CONSTRAINT vendor_bills_total_amount_check CHECK (total_amount >= 0::numeric);
ALTER TABLE ONLY public.weather_daily ADD CONSTRAINT weather_daily_pkey PRIMARY KEY (weather_date);
ALTER TABLE ONLY public.weather_daily ADD CONSTRAINT weather_daily_source_kind_check CHECK (source_kind = ANY (ARRAY['Historical'::text, 'Forecast'::text]));
