import { randomUUID, timingSafeEqual } from "node:crypto";
import OpenAI from "openai";
import WebSocket from "ws";
import { ensureOrderingAiSchema } from "@/lib/ordering-ai-schema";
import { getSql } from "@/lib/db";

export const OPENAI_PHONE_MODEL=process.env.OPENAI_REALTIME_MODEL||"gpt-realtime-1.5";
export const OPENAI_PHONE_GREETING="Hello, thank you for calling Corner Deli. Will this be for pickup or delivery?";
const required=()=>({apiKey:Boolean(process.env.OPENAI_API_KEY),webhookSecret:Boolean(process.env.OPENAI_WEBHOOK_SECRET),mcpUrl:Boolean(process.env.OPENAI_ORDERING_MCP_URL),mcpToken:Boolean(process.env.OPENAI_ORDERING_MCP_TOKEN),testDids:testDids().length>0,handoffTarget:Boolean(process.env.OPENAI_PHONE_HANDOFF_TARGET)});
const digits=(value:string)=>value.replace(/\D/g,"").replace(/^1(?=\d{10}$)/,"").slice(-10);
export function testDids(){return (process.env.OPENAI_PHONE_TEST_DIDS||"").split(",").map(digits).filter(value=>value.length===10)}
export function calledDidFromSipHeaders(headers:Array<{name:string;value:string}>){for(const name of ["x-corner-ops-did","x-original-to","p-called-party-id","diversion","to","request-uri"]){const value=headers.find(row=>row.name.toLowerCase()===name)?.value||"",match=value.match(/(?:\+?1)?(\d{10})(?:\D|$)/);if(match)return match[1]}return""}
export function testDidAllowed(did:string){return Boolean(did)&&testDids().includes(digits(did))}
export function lineForDid(did:string){const normalized=digits(did),entries=(process.env.OPENAI_PHONE_DID_LINES||"").split(",");for(const entry of entries){const [number,label]=entry.split("=");if(digits(number||"")===normalized)return String(label||"").trim()}return"TEST"}
export function openAiPhoneReadiness(){const configured=required();return{enabled:process.env.OPENAI_PHONE_ORDERING_ENABLED==="true",testMode:true,configured,ready:Object.values(configured).every(Boolean)&&process.env.OPENAI_PHONE_ORDERING_ENABLED==="true",model:OPENAI_PHONE_MODEL,testDidsConfigured:testDids().length};}
export function openAiClient(){return new OpenAI({apiKey:process.env.OPENAI_API_KEY||"missing",webhookSecret:process.env.OPENAI_WEBHOOK_SECRET});}
export function startOpenAiGreeting(callId:string){const apiKey=process.env.OPENAI_API_KEY||"";if(!apiKey)throw new Error("OpenAI API key is not configured.");const socket=new WebSocket(`wss://api.openai.com/v1/realtime?call_id=${encodeURIComponent(callId)}`,{headers:{Authorization:`Bearer ${apiKey}`}});const timeout=setTimeout(()=>socket.terminate(),15_000);socket.once("open",()=>socket.send(JSON.stringify({type:"response.create",response:{instructions:`Speak in English. Say exactly: \"${OPENAI_PHONE_GREETING}\" Do not add any other words.`,output_modalities:["audio"]}})));socket.on("message",data=>{try{const event=JSON.parse(String(data));if(event.type==="response.done"||event.type==="error"){clearTimeout(timeout);if(event.type==="error")console.error("OpenAI realtime greeting failed.",{callId,error:event.error?.message||"unknown error"});socket.close()}}catch{}});socket.once("error",error=>{clearTimeout(timeout);console.error("OpenAI realtime greeting socket failed.",{callId,error:error.message})});socket.once("close",()=>clearTimeout(timeout));}
export function mcpAuthorized(request:Request){const expected=process.env.OPENAI_ORDERING_MCP_TOKEN||"",supplied=(request.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");const a=Buffer.from(expected),b=Buffer.from(supplied);return Boolean(expected)&&a.length===b.length&&timingSafeEqual(a,b)}
export function callerFromSipHeaders(headers:Array<{name:string;value:string}>){const preferred=["p-asserted-identity","remote-party-id","from"];for(const name of preferred){const value=headers.find(row=>row.name.toLowerCase()===name)?.value||"";const match=value.match(/\+?1?(\d{10})(?:\D|$)/);if(match)return match[1]}return""}
export async function registerOpenAiCall(callId:string,callerPhone:string,calledDid="",lineLabel="TEST"){await ensureOrderingAiSchema();const id=randomUUID();await getSql()`INSERT INTO ordering_call_sessions(id,business,three_cx_call_id,caller_phone,called_did,line_label,state,owner_type,owner_id)VALUES(${id},'Corner Deli',${callId},${callerPhone},${calledDid},${lineLabel},'ai','ai',${`openai:${callId}`})ON CONFLICT(three_cx_call_id)DO UPDATE SET caller_phone=EXCLUDED.caller_phone,called_did=EXCLUDED.called_did,line_label=EXCLUDED.line_label,state='ai',owner_type='ai',owner_id=EXCLUDED.owner_id,updated_at=NOW()`;return id}
export async function requestOpenAiHandoff(callId:string,reason:string){await ensureOrderingAiSchema();const target=process.env.OPENAI_PHONE_HANDOFF_TARGET||"";if(!target)throw new Error("Human handoff target is not configured.");const updated=await getSql()`UPDATE ordering_call_sessions SET state='handoff_pending',handoff_reason=${reason.slice(0,500)},owner_type='none',owner_id='',updated_at=NOW() WHERE business='Corner Deli' AND three_cx_call_id=${callId} AND state='ai' RETURNING id`;if(!updated[0])throw new Error("The active AI call could not be handed off.");try{await openAiClient().realtime.calls.refer(callId,{target_uri:target})}catch(error){await getSql()`UPDATE ordering_call_sessions SET state='ai',handoff_reason='',owner_type='ai',owner_id=${`openai:${callId}`},updated_at=NOW() WHERE three_cx_call_id=${callId}`;throw error}return{handoff:true,target:"configured_3cx_destination"}}
export const PHONE_INSTRUCTIONS=`You answer Corner Deli ordering calls. Always speak English unless the caller explicitly asks for another language. Be warm, confident, brief, and easy to interrupt. Begin each call by greeting the caller and asking whether the order is for pickup or delivery. Use Corner Ops tools for every menu fact, price, availability, customer match, delivery fee, and order change. Never invent an item, ingredient, allergen claim, price, address validation, or delivery promise. The caller ID is context, not proof of identity. Before SEND, call HOLD, read back every item and the authoritative total, obtain an explicit yes from the customer, then call SEND. If a tool fails twice, the customer disputes the order, an allergen question cannot be answered from tool data, or the caller requests a person, explain that you are transferring them and call request_human_handoff with a concise operational reason. Stop changing the order after requesting handoff. Every tool call must include the exact callId supplied in this session.`;
