import { randomUUID, timingSafeEqual } from "node:crypto";
import OpenAI from "openai";
import { ensureOrderingAiSchema } from "@/lib/ordering-ai-schema";
import { getSql } from "@/lib/db";

export const OPENAI_PHONE_MODEL=process.env.OPENAI_REALTIME_MODEL||"gpt-realtime-1.5";
const required=()=>({apiKey:Boolean(process.env.OPENAI_API_KEY),webhookSecret:Boolean(process.env.OPENAI_WEBHOOK_SECRET),mcpUrl:Boolean(process.env.OPENAI_ORDERING_MCP_URL),mcpToken:Boolean(process.env.OPENAI_ORDERING_MCP_TOKEN)});
export function openAiPhoneReadiness(){const configured=required();return{enabled:process.env.OPENAI_PHONE_ORDERING_ENABLED==="true",configured,ready:Object.values(configured).every(Boolean)&&process.env.OPENAI_PHONE_ORDERING_ENABLED==="true",model:OPENAI_PHONE_MODEL};}
export function openAiClient(){return new OpenAI({apiKey:process.env.OPENAI_API_KEY||"missing",webhookSecret:process.env.OPENAI_WEBHOOK_SECRET});}
export function mcpAuthorized(request:Request){const expected=process.env.OPENAI_ORDERING_MCP_TOKEN||"",supplied=(request.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");const a=Buffer.from(expected),b=Buffer.from(supplied);return Boolean(expected)&&a.length===b.length&&timingSafeEqual(a,b)}
export function callerFromSipHeaders(headers:Array<{name:string;value:string}>){const preferred=["p-asserted-identity","remote-party-id","from"];for(const name of preferred){const value=headers.find(row=>row.name.toLowerCase()===name)?.value||"";const match=value.match(/\+?1?(\d{10})(?:\D|$)/);if(match)return match[1]}return""}
export async function registerOpenAiCall(callId:string,callerPhone:string){await ensureOrderingAiSchema();const id=randomUUID();await getSql()`INSERT INTO ordering_call_sessions(id,business,three_cx_call_id,caller_phone,state,owner_type,owner_id)VALUES(${id},'Corner Deli',${callId},${callerPhone},'ai','ai',${`openai:${callId}`})ON CONFLICT(three_cx_call_id)DO UPDATE SET caller_phone=EXCLUDED.caller_phone,state='ai',owner_type='ai',owner_id=EXCLUDED.owner_id,updated_at=NOW()`;return id}
export const PHONE_INSTRUCTIONS=`You answer Corner Deli ordering calls. Be warm, brief, and easy to interrupt. Use Corner Ops tools for every menu fact, price, availability, customer match, delivery fee, and order change. Never invent an item, ingredient, allergen claim, price, address validation, or delivery promise. The caller ID is context, not proof of identity. Ask pickup or delivery at a natural break. Before SEND, call HOLD, read back every item and the authoritative total, obtain an explicit yes from the customer, then call SEND. If a tool fails twice, the customer disputes the order, an allergen question cannot be answered from tool data, or the caller requests a person, explain the handoff and stop changing the order. Every tool call must include the exact callId supplied in this session.`;
