import { createHash } from "node:crypto";
import type { OrderingBusiness } from "@/lib/ordering-core";
import type { OrderingActor } from "@/lib/ordering-route-auth";
import { canManagePos } from "@/lib/ordering-route-auth";
import { activateGiftCard } from "@/lib/ordering-gift-cards";
import { getSql } from "@/lib/db";
import { ensureOrderingGiftCardSchema } from "@/lib/ordering-gift-card-schema";
export type GiftCardImportRow={sourceReference:string;cardNumber:string;balanceCents:number};
export async function importGiftCards(input:{business:OrderingBusiness;rows:GiftCardImportRow[];dryRun:boolean;batchKey:string;actor:OrderingActor}){if(!canManagePos(input.actor))throw new Error('Manager or owner authorization is required.');if(!input.batchKey.trim())throw new Error('Import batch key is required.');if(!Array.isArray(input.rows)||input.rows.length>5000)throw new Error('Import must contain at most 5,000 rows.');await ensureOrderingGiftCardSchema();const seen=new Set<string>(),report:{row:number;sourceReference:string;status:string;message?:string}[]=[];for(let index=0;index<input.rows.length;index++){const row=input.rows[index],source=String(row.sourceReference||'').trim(),card=String(row.cardNumber||'').replace(/[^A-Za-z0-9]/g,'').toUpperCase(),balance=Number(row.balanceCents);const fingerprint=createHash('sha256').update(`${input.business}:${source}`).digest('hex');if(!source||card.length<8||!Number.isSafeInteger(balance)||balance<=0){report.push({row:index+1,sourceReference:source,status:'invalid',message:'Source reference, card number, and positive integer-cent balance are required.'});continue}if(seen.has(source)){report.push({row:index+1,sourceReference:source,status:'duplicate_in_file'});continue}seen.add(source);const existing=await getSql()`SELECT id FROM ordering_gift_cards WHERE business=${input.business} AND (source_reference=${source} OR card_number_hash=${createHash('sha256').update(`corner-ops-gift-card:${card}`).digest('hex')})`;if(existing[0]){report.push({row:index+1,sourceReference:source,status:'already_imported'});continue}if(input.dryRun){report.push({row:index+1,sourceReference:source,status:'ready'});continue}await activateGiftCard({business:input.business,initialLoadCents:balance,operationKey:`import:${input.batchKey}:${fingerprint}`,actor:input.actor,cardNumber:card,sourceReference:source});report.push({row:index+1,sourceReference:source,status:'imported'})}return {dryRun:input.dryRun,total:input.rows.length,ready:report.filter(r=>r.status==='ready').length,imported:report.filter(r=>r.status==='imported').length,duplicates:report.filter(r=>r.status.includes('duplicate')||r.status==='already_imported').length,invalid:report.filter(r=>r.status==='invalid').length,rows:report}}
