import {randomUUID} from "node:crypto";
import {getSql,withTransaction} from "@/lib/db";
import {ensureOrderingInventorySchema} from "@/lib/ordering-inventory-schema";
import {canManagePos,type OrderingActor} from "@/lib/ordering-route-auth";

export class InventoryError extends Error{}
const quantity=(value:unknown,label="Quantity")=>{const n=Number(value);if(!Number.isFinite(n)||n<=0)throw new InventoryError(`${label} must be greater than zero.`);return Math.round(n*1000)/1000};
const nonnegativeQuantity=(value:unknown,label="Quantity")=>{const n=Number(value);if(!Number.isFinite(n)||n<0)throw new InventoryError(`${label} cannot be negative.`);return Math.round(n*1000)/1000};
const required=(value:unknown,label:string)=>{const text=String(value||"").trim();if(!text)throw new InventoryError(`${label} is required.`);return text};
function manager(actor:OrderingActor){if(!canManagePos(actor))throw new InventoryError("Manager or owner approval is required.")}

export async function inventoryDashboard(){await ensureOrderingInventorySchema();const sql=getSql();const [locations,items,links,menuItems,modifierOptions,suppliers,supplierItems,purchaseOrders,movements]=await Promise.all([
 sql`SELECT * FROM ordering_inventory_locations WHERE business='Corner Deli' ORDER BY active DESC,sort_order,name`,
 sql`SELECT item.*,COALESCE(stock.on_hand,0)::numeric on_hand,(item.reorder_point IS NOT NULL AND COALESCE(stock.on_hand,0)<=item.reorder_point) low_stock FROM ordering_inventory_items item LEFT JOIN(SELECT inventory_item_id,SUM(delta_quantity) on_hand FROM ordering_inventory_movements WHERE business='Corner Deli' GROUP BY inventory_item_id)stock ON stock.inventory_item_id=item.id WHERE item.business='Corner Deli' ORDER BY item.active DESC,item.category,item.name`,
 sql`SELECT link.*,item.name menu_item_name,option.name modifier_option_name,inventory.name inventory_name FROM ordering_menu_inventory_links link LEFT JOIN ordering_menu_items item ON item.id=link.menu_item_id LEFT JOIN ordering_modifier_options option ON option.id=link.modifier_option_id JOIN ordering_inventory_items inventory ON inventory.id=link.inventory_item_id WHERE link.business='Corner Deli' ORDER BY inventory.name`,
 sql`SELECT id,name FROM ordering_menu_items WHERE business='Corner Deli' AND active=TRUE ORDER BY name`,
 sql`SELECT option.id,option.name,grp.name group_name FROM ordering_modifier_options option JOIN ordering_modifier_groups grp ON grp.id=option.group_id WHERE grp.business='Corner Deli' AND option.active=TRUE ORDER BY grp.name,option.name`,
 sql`SELECT * FROM ordering_inventory_suppliers WHERE business='Corner Deli' ORDER BY active DESC,name`,
 sql`SELECT supplier_item.*,supplier.name supplier_name,item.name inventory_name FROM ordering_inventory_supplier_items supplier_item JOIN ordering_inventory_suppliers supplier ON supplier.id=supplier_item.supplier_id JOIN ordering_inventory_items item ON item.id=supplier_item.inventory_item_id WHERE supplier.business='Corner Deli' ORDER BY supplier.name,item.name`,
 sql`SELECT po.*,supplier.name supplier_name,COALESCE(SUM(line.quantity_cases*line.case_price_cents),0)::integer total_cents,COUNT(line.id)::integer line_count FROM ordering_inventory_purchase_orders po JOIN ordering_inventory_suppliers supplier ON supplier.id=po.supplier_id LEFT JOIN ordering_inventory_purchase_order_lines line ON line.purchase_order_id=po.id WHERE po.business='Corner Deli' GROUP BY po.id,supplier.name ORDER BY po.created_at DESC LIMIT 50`,
 sql`SELECT movement.*,item.name inventory_name,location.name location_name FROM ordering_inventory_movements movement JOIN ordering_inventory_items item ON item.id=movement.inventory_item_id LEFT JOIN ordering_inventory_locations location ON location.id=movement.location_id WHERE movement.business='Corner Deli' ORDER BY movement.created_at DESC LIMIT 100`
]);return{locations,items,links,menuItems,modifierOptions,suppliers,supplierItems,purchaseOrders,movements};}

export async function inventoryAction(body:Record<string,unknown>,actor:OrderingActor){await ensureOrderingInventorySchema();const sql=getSql(),action=String(body.action||"");
 if(action==="save_location"){manager(actor);const name=required(body.name,"Location name"),id=String(body.id||randomUUID());return(await sql`INSERT INTO ordering_inventory_locations(id,business,name,sort_order,active)VALUES(${id},'Corner Deli',${name},${Number(body.sortOrder||0)},${body.active!==false}) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,sort_order=EXCLUDED.sort_order,active=EXCLUDED.active,updated_at=NOW() RETURNING *`)[0]}
 if(action==="save_item"){manager(actor);const name=required(body.name,"Item name"),id=String(body.id||randomUUID()),unit=required(body.baseUnit,"Base unit");return(await sql`INSERT INTO ordering_inventory_items(id,business,name,sku,category,base_unit,estimated_unit_cost_cents,reorder_point,par_quantity,case_pack_quantity,preferred_supplier,track_quantity,allow_negative,active)VALUES(${id},'Corner Deli',${name},${String(body.sku||"").trim()},${String(body.category||"").trim()},${unit},${body.unitCostCents==null?null:Number(body.unitCostCents)},${body.reorderPoint==null||body.reorderPoint===""?null:Number(body.reorderPoint)},${body.parQuantity==null||body.parQuantity===""?null:Number(body.parQuantity)},${body.casePackQuantity==null||body.casePackQuantity===""?null:Number(body.casePackQuantity)},${String(body.preferredSupplier||"").trim()},${body.trackQuantity!==false},${body.allowNegative===true},${body.active!==false}) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,sku=EXCLUDED.sku,category=EXCLUDED.category,base_unit=EXCLUDED.base_unit,estimated_unit_cost_cents=EXCLUDED.estimated_unit_cost_cents,reorder_point=EXCLUDED.reorder_point,par_quantity=EXCLUDED.par_quantity,case_pack_quantity=EXCLUDED.case_pack_quantity,preferred_supplier=EXCLUDED.preferred_supplier,track_quantity=EXCLUDED.track_quantity,allow_negative=EXCLUDED.allow_negative,active=EXCLUDED.active,updated_at=NOW() RETURNING *`)[0]}
 if(action==="movement"){const itemId=required(body.itemId,"Inventory item"),amount=quantity(body.quantity),reason=required(body.reason,"Reason"),direction=["received","return_to_stock","transfer_in"].includes(reason)?1:-1;if(reason==="received")manager(actor);return(await sql`INSERT INTO ordering_inventory_movements(id,business,inventory_item_id,location_id,delta_quantity,unit,reason,employee_id,note,source,created_by,details) SELECT ${randomUUID()},'Corner Deli',id,${body.locationId?String(body.locationId):null},${amount*direction},base_unit,${reason},${actor.id},${String(body.note||"").trim()},'inventory',${actor.id},'{}'::jsonb FROM ordering_inventory_items WHERE id=${itemId} AND business='Corner Deli' RETURNING *`)[0]}
 if(action==="count")return withTransaction(async()=>{const itemId=required(body.itemId,"Inventory item"),counted=nonnegativeQuantity(body.countedQuantity,"Counted quantity"),locationId=body.locationId?String(body.locationId):null;const current=(await sql`SELECT COALESCE(SUM(delta_quantity),0)::numeric quantity FROM ordering_inventory_movements WHERE business='Corner Deli' AND inventory_item_id=${itemId} AND location_id IS NOT DISTINCT FROM ${locationId}`)[0],expected=Number(current.quantity),variance=Math.round((counted-expected)*1000)/1000,movementId=variance?randomUUID():null;if(variance)await sql`INSERT INTO ordering_inventory_movements(id,business,inventory_item_id,location_id,delta_quantity,unit,reason,employee_id,note,source,created_by,details) SELECT ${movementId},'Corner Deli',id,${locationId},${variance},base_unit,'count_correction',${actor.id},${String(body.note||"")},'inventory_count',${actor.id},'{}'::jsonb FROM ordering_inventory_items WHERE id=${itemId}`;return(await sql`INSERT INTO ordering_inventory_counts(id,business,inventory_item_id,location_id,expected_quantity,counted_quantity,variance_quantity,adjustment_movement_id,counted_by,note)VALUES(${randomUUID()},'Corner Deli',${itemId},${locationId},${expected},${counted},${variance},${movementId},${actor.id},${String(body.note||"")}) RETURNING *`)[0]});
 if(action==="transfer")return withTransaction(async()=>{const itemId=required(body.itemId,"Inventory item"),from=required(body.fromLocationId,"From location"),to=required(body.toLocationId,"To location"),amount=quantity(body.quantity);if(from===to)throw new InventoryError("Choose two different locations.");const out=randomUUID(),incoming=randomUUID(),unit=String((await sql`SELECT base_unit FROM ordering_inventory_items WHERE id=${itemId} AND business='Corner Deli'`)[0]?.base_unit||"");if(!unit)throw new InventoryError("Inventory item was not found.");await sql`INSERT INTO ordering_inventory_movements(id,business,inventory_item_id,location_id,delta_quantity,unit,reason,employee_id,related_movement_id,note,source,created_by)VALUES(${out},'Corner Deli',${itemId},${from},${-amount},${unit},'transfer_out',${actor.id},${incoming},${String(body.note||"")},'inventory',${actor.id}),(${incoming},'Corner Deli',${itemId},${to},${amount},${unit},'transfer_in',${actor.id},${out},${String(body.note||"")},'inventory',${actor.id})`;return{ok:true}});
 if(action==="save_link"){manager(actor);const inventoryItemId=required(body.inventoryItemId,"Inventory item"),targetType=String(body.targetType),targetId=required(body.targetId,"Menu item or modifier"),id=String(body.id||randomUUID());if(!["menu_item","modifier_option"].includes(targetType))throw new InventoryError("Choose a menu item or modifier.");return(await sql`INSERT INTO ordering_menu_inventory_links(id,business,menu_item_id,modifier_option_id,inventory_item_id,quantity_used,unit,active)VALUES(${id},'Corner Deli',${targetType==='menu_item'?targetId:null},${targetType==='modifier_option'?targetId:null},${inventoryItemId},${quantity(body.quantityUsed,"Usage quantity")},${required(body.unit,"Usage unit")},TRUE) ON CONFLICT(id) DO UPDATE SET inventory_item_id=EXCLUDED.inventory_item_id,quantity_used=EXCLUDED.quantity_used,unit=EXCLUDED.unit,active=TRUE RETURNING *`)[0]}
 if(action==="save_supplier"){manager(actor);const id=String(body.id||randomUUID()),name=required(body.name,"Supplier name");return(await sql`INSERT INTO ordering_inventory_suppliers(id,business,name,contact_name,email,phone,minimum_order_cents,delivery_fee_cents,active)VALUES(${id},'Corner Deli',${name},${String(body.contactName||"")},${String(body.email||"")},${String(body.phone||"")},${Number(body.minimumOrderCents||0)},${Number(body.deliveryFeeCents||0)},TRUE) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,contact_name=EXCLUDED.contact_name,email=EXCLUDED.email,phone=EXCLUDED.phone,minimum_order_cents=EXCLUDED.minimum_order_cents,delivery_fee_cents=EXCLUDED.delivery_fee_cents,updated_at=NOW() RETURNING *`)[0]}
 if(action==="save_supplier_item"){manager(actor);const supplierId=required(body.supplierId,"Supplier"),itemId=required(body.itemId,"Inventory item");return(await sql`INSERT INTO ordering_inventory_supplier_items(id,supplier_id,inventory_item_id,vendor_sku,case_quantity,case_unit,case_price_cents,last_quoted_at)VALUES(${randomUUID()},${supplierId},${itemId},${String(body.vendorSku||"")},${quantity(body.caseQuantity,"Case quantity")},${required(body.caseUnit,"Case unit")},${Number(body.casePriceCents||0)},NOW()) ON CONFLICT(supplier_id,inventory_item_id) DO UPDATE SET vendor_sku=EXCLUDED.vendor_sku,case_quantity=EXCLUDED.case_quantity,case_unit=EXCLUDED.case_unit,case_price_cents=EXCLUDED.case_price_cents,last_quoted_at=NOW(),updated_at=NOW() RETURNING *`)[0]}
 if(action==="create_po"){manager(actor);const supplierId=required(body.supplierId,"Supplier"),lines=Array.isArray(body.lines)?body.lines as Array<Record<string,unknown>>:[];if(!lines.length)throw new InventoryError("Add at least one purchase-order line.");return withTransaction(async()=>{const id=randomUUID();await sql`INSERT INTO ordering_inventory_purchase_orders(id,business,supplier_id,status,created_by,notes)VALUES(${id},'Corner Deli',${supplierId},'draft',${actor.id},${String(body.notes||"")})`;for(const line of lines)await sql`INSERT INTO ordering_inventory_purchase_order_lines(id,purchase_order_id,inventory_item_id,quantity_cases,case_quantity,case_unit,case_price_cents)VALUES(${randomUUID()},${id},${required(line.itemId,"Inventory item")},${quantity(line.quantityCases,"Cases")},${quantity(line.caseQuantity,"Case quantity")},${required(line.caseUnit,"Case unit")},${Number(line.casePriceCents||0)})`;return{id}})}
 if(action==="po_status"){manager(actor);const id=required(body.id,"Purchase order"),status=String(body.status);if(!["ordered","cancelled"].includes(status))throw new InventoryError("Invalid purchase-order status.");return(await sql`UPDATE ordering_inventory_purchase_orders SET status=${status},ordered_at=CASE WHEN ${status}='ordered' THEN NOW() ELSE ordered_at END,updated_at=NOW() WHERE id=${id} AND business='Corner Deli' AND status='draft' RETURNING *`)[0]}
 if(action==="receive_po"){manager(actor);const id=required(body.id,"Purchase order"),locationId=body.locationId?String(body.locationId):null;return withTransaction(async()=>{const po=(await sql`SELECT * FROM ordering_inventory_purchase_orders WHERE id=${id} AND business='Corner Deli' AND status IN('draft','ordered','partially_received') FOR UPDATE`)[0];if(!po)throw new InventoryError("This purchase order cannot be received.");const lines=await sql`SELECT line.*,item.base_unit FROM ordering_inventory_purchase_order_lines line JOIN ordering_inventory_items item ON item.id=line.inventory_item_id WHERE line.purchase_order_id=${id}`;for(const line of lines){const cases=Number(line.quantity_cases)-Number(line.received_cases);if(cases<=0)continue;const units=cases*Number(line.case_quantity);await sql`INSERT INTO ordering_inventory_movements(id,business,inventory_item_id,location_id,delta_quantity,unit,reason,employee_id,estimated_unit_cost_cents,note,source,created_by,details)VALUES(${randomUUID()},'Corner Deli',${line.inventory_item_id},${locationId},${units},${line.base_unit},'received',${actor.id},${Math.round(Number(line.case_price_cents)/Number(line.case_quantity))},${`PO ${id}`},'purchase_order',${actor.id},${JSON.stringify({purchaseOrderId:id,purchaseOrderLineId:line.id,cases})}::jsonb)`;await sql`UPDATE ordering_inventory_purchase_order_lines SET received_cases=quantity_cases WHERE id=${line.id}`;await sql`UPDATE ordering_inventory_items SET estimated_unit_cost_cents=${Math.round(Number(line.case_price_cents)/Number(line.case_quantity))},updated_at=NOW() WHERE id=${line.inventory_item_id}`;}return(await sql`UPDATE ordering_inventory_purchase_orders SET status='received',received_at=NOW(),updated_at=NOW() WHERE id=${id} RETURNING *`)[0]})}
 throw new InventoryError("Unknown inventory action.");}

export async function depleteInventoryForOrder(orderId:string,business:string,actor:OrderingActor){await ensureOrderingInventorySchema();const sql=getSql();await sql`INSERT INTO ordering_inventory_movements(id,business,inventory_item_id,location_id,delta_quantity,unit,reason,order_id,order_item_id,inventory_link_id,employee_id,estimated_unit_cost_cents,note,source,created_by,details) SELECT gen_random_uuid(),${business},link.inventory_item_id,location.location_id,-(link.quantity_used*line.quantity),link.unit,'sale',line.order_id,line.id,link.id,${actor.id},inventory.estimated_unit_cost_cents,line.item_name_snapshot,'order_submit',${actor.id},jsonb_build_object('menuItemId',line.item_id) FROM ordering_order_items line JOIN ordering_menu_inventory_links link ON link.business=${business} AND link.menu_item_id=line.item_id AND link.active=TRUE JOIN ordering_inventory_items inventory ON inventory.id=link.inventory_item_id AND inventory.active=TRUE LEFT JOIN LATERAL(SELECT location_id FROM ordering_inventory_item_locations WHERE inventory_item_id=inventory.id AND active=TRUE ORDER BY is_default DESC,created_at LIMIT 1)location ON TRUE WHERE line.order_id=${orderId} ON CONFLICT DO NOTHING`;await sql`INSERT INTO ordering_inventory_movements(id,business,inventory_item_id,location_id,delta_quantity,unit,reason,order_id,order_item_id,inventory_link_id,employee_id,estimated_unit_cost_cents,note,source,created_by,details) SELECT gen_random_uuid(),${business},link.inventory_item_id,location.location_id,-(link.quantity_used*modifier.quantity*line.quantity),link.unit,'sale',line.order_id,line.id,link.id,${actor.id},inventory.estimated_unit_cost_cents,modifier.option_name_snapshot,'order_submit',${actor.id},jsonb_build_object('modifierOptionId',modifier.option_id) FROM ordering_order_items line JOIN ordering_order_item_modifiers modifier ON modifier.order_item_id=line.id AND modifier.selection_state IN('selected','extra') JOIN ordering_menu_inventory_links link ON link.business=${business} AND link.modifier_option_id=modifier.option_id AND link.active=TRUE JOIN ordering_inventory_items inventory ON inventory.id=link.inventory_item_id AND inventory.active=TRUE LEFT JOIN LATERAL(SELECT location_id FROM ordering_inventory_item_locations WHERE inventory_item_id=inventory.id AND active=TRUE ORDER BY is_default DESC,created_at LIMIT 1)location ON TRUE WHERE line.order_id=${orderId} ON CONFLICT DO NOTHING`;}
