import { randomUUID } from "node:crypto";
import { getSql, withTransaction } from "@/lib/db";
import type { OrderingBusiness } from "@/lib/ordering-core";
import type { OrderingActor } from "@/lib/ordering-route-auth";
import { canManagePos } from "@/lib/ordering-route-auth";
import { ensureOrderingHardwareSchema } from "@/lib/ordering-hardware-schema";

export type DeviceStatus = "online" | "offline" | "unknown";
export interface HardwareAdapter { readonly key:string; readonly kind:"printer"|"payment_terminal"|"barcode_scanner"; probe(config:Record<string,unknown>):Promise<{status:DeviceStatus;message:string}> }
export class UnconfiguredAdapter implements HardwareAdapter { readonly key:string="unconfigured"; constructor(readonly kind:HardwareAdapter["kind"]){ } async probe(){return {status:"unknown" as const,message:"No hardware adapter is configured."}} }
export class MockDeviceAdapter implements HardwareAdapter { readonly key:string="mock"; constructor(readonly kind:HardwareAdapter["kind"]){ } async probe(config:Record<string,unknown>){const requested=config.mockStatus;const status:DeviceStatus=requested==="online"||requested==="offline"?requested:"unknown";return {status,message:status==="unknown"?"Mock status was not explicitly configured.":`Mock adapter explicitly reports ${status}.`}} }
export class PaymentTerminalPlaceholderAdapter extends UnconfiguredAdapter { readonly key="payment-placeholder"; constructor(){super("payment_terminal")} }
export function hardwareAdapter(key:string,kind:HardwareAdapter["kind"]):HardwareAdapter { if(key==="mock")return new MockDeviceAdapter(kind);if(key==="payment-placeholder"&&kind==="payment_terminal")return new PaymentTerminalPlaceholderAdapter();return new UnconfiguredAdapter(kind) }

function manager(actor:OrderingActor){if(!canManagePos(actor))throw new Error("Manager or owner authorization is required.")}
function safeConfig(value:unknown):Record<string,unknown>{const config=value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};if(Object.keys(config).some(key=>/secret|password|token|credential|api.?key/i.test(key)))throw new Error("Credentials and secrets cannot be stored in device configuration.");return config}
export function effectiveDeviceStatus(row:{active:boolean;reported_status:DeviceStatus;last_seen_at?:string|Date|null}):DeviceStatus {if(!row.active)return "offline";if(!row.last_seen_at)return "unknown";if(Date.now()-new Date(row.last_seen_at).getTime()>120_000)return "offline";return row.reported_status}

export async function hardwareDashboard(business:OrderingBusiness){await ensureOrderingHardwareSchema();const sql=getSql();const [locations,devices,routes,jobs]=await Promise.all([
 sql`SELECT * FROM ordering_hardware_locations WHERE business=${business} ORDER BY active DESC,name`,
 sql`SELECT device.*,location.name location_name FROM ordering_hardware_devices device JOIN ordering_hardware_locations location ON location.id=device.location_id WHERE device.business=${business} ORDER BY device.active DESC,location.name,device.name`,
 sql`SELECT route.*,device.name printer_name,location.name location_name FROM ordering_printer_routes route JOIN ordering_hardware_devices device ON device.id=route.printer_id JOIN ordering_hardware_locations location ON location.id=route.location_id WHERE route.business=${business} ORDER BY route.priority DESC,route.created_at`,
 sql`SELECT job.id,job.order_id,job.purpose,job.event_subtype,job.status,job.is_reprint,job.retry_count,job.error_message,job.queued_at,job.attempted_at,job.completed_at,job.device_id,device.name device_name FROM ordering_print_jobs job LEFT JOIN ordering_hardware_devices device ON device.id=job.device_id WHERE job.business=${business} ORDER BY job.created_at DESC LIMIT 100`
 ]);return {locations,devices:devices.map((row:any)=>({...row,effective_status:effectiveDeviceStatus(row)})),routes,jobs}}

export async function saveHardware(input:{business:OrderingBusiness;action:string;body:Record<string,unknown>;actor:OrderingActor}):Promise<any>{manager(input.actor);await ensureOrderingHardwareSchema();const sql=getSql(),body=input.body;
 if(input.action==="save_location"){const id=String(body.id||randomUUID()),name=String(body.name||"").trim(),key=String(body.locationKey||"").trim().toLowerCase();if(!name||!key)throw new Error("Location name and key are required.");await sql`INSERT INTO ordering_hardware_locations(id,business,name,location_key,active) VALUES(${id},${input.business},${name},${key},${body.active!==false}) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,location_key=EXCLUDED.location_key,active=EXCLUDED.active,updated_at=NOW() WHERE ordering_hardware_locations.business=${input.business}`;return {id}}
 if(input.action==="save_device"){const id=String(body.id||randomUUID()),name=String(body.name||"").trim(),deviceKey=String(body.deviceKey||"").trim().toLowerCase(),locationId=String(body.locationId||""),deviceType=String(body.deviceType||""),role=String(body.role||""),adapterKey=String(body.adapterKey||"unconfigured");if(!name||!deviceKey||!locationId)throw new Error("Device name, key, and location are required.");if(!["printer","payment_terminal","barcode_scanner"].includes(deviceType))throw new Error("Unknown device type.");const expected={printer:["receipt_printer","kitchen_printer"],payment_terminal:["payment_terminal"],barcode_scanner:["barcode_scanner"]}[deviceType]!;if(!expected.includes(role))throw new Error("Device role does not match its type.");if(!["unconfigured","mock","payment-placeholder"].includes(adapterKey)||(adapterKey==="payment-placeholder"&&deviceType!=="payment_terminal"))throw new Error("Unsupported adapter.");const config=safeConfig(body.adapterConfig);const rows=await sql`INSERT INTO ordering_hardware_devices(id,business,location_id,name,device_key,device_type,role,station_key,adapter_key,adapter_config,active,created_by,updated_by) SELECT ${id},${input.business},id,${name},${deviceKey},${deviceType},${role},${String(body.stationKey||"").trim()},${adapterKey},${JSON.stringify(config)}::jsonb,${body.active!==false},${input.actor.id},${input.actor.id} FROM ordering_hardware_locations WHERE id=${locationId} AND business=${input.business} ON CONFLICT(id) DO UPDATE SET location_id=EXCLUDED.location_id,name=EXCLUDED.name,device_key=EXCLUDED.device_key,device_type=EXCLUDED.device_type,role=EXCLUDED.role,station_key=EXCLUDED.station_key,adapter_key=EXCLUDED.adapter_key,adapter_config=EXCLUDED.adapter_config,active=EXCLUDED.active,updated_by=EXCLUDED.updated_by,updated_at=NOW() WHERE ordering_hardware_devices.business=${input.business} RETURNING id`;if(!rows.length)throw new Error("Hardware location was not found in this business.");return {id}}
 if(input.action==="probe_device"){const id=String(body.id||"");const device=(await sql`SELECT * FROM ordering_hardware_devices WHERE id=${id} AND business=${input.business}`)[0];if(!device)throw new Error("Device not found.");const result=await hardwareAdapter(device.adapter_key,device.device_type).probe(device.adapter_config);await sql`UPDATE ordering_hardware_devices SET reported_status=${result.status},last_seen_at=NOW(),status_message=${result.message},updated_by=${input.actor.id},updated_at=NOW() WHERE id=${id}`;return result}
 if(input.action==="save_route"){const id=String(body.id||randomUUID()),locationId=String(body.locationId||""),printerId=String(body.printerId||""),targetType=String(body.targetType||"all"),targetId=String(body.targetId||"").trim();if(!["all","item","category","station"].includes(targetType)||((targetType!=="all")!==Boolean(targetId)))throw new Error("A valid route target is required.");const printer=(await sql`SELECT id FROM ordering_hardware_devices WHERE id=${printerId} AND business=${input.business} AND location_id=${locationId} AND device_type='printer' AND role='kitchen_printer'`)[0];if(!printer)throw new Error("Kitchen printer was not found in this business/location.");await sql`INSERT INTO ordering_printer_routes(id,business,location_id,printer_id,target_type,target_id,priority,active,created_by,updated_by) VALUES(${id},${input.business},${locationId},${printerId},${targetType},${targetId},${Number(body.priority||0)},${body.active!==false},${input.actor.id},${input.actor.id}) ON CONFLICT(id) DO UPDATE SET location_id=EXCLUDED.location_id,printer_id=EXCLUDED.printer_id,target_type=EXCLUDED.target_type,target_id=EXCLUDED.target_id,priority=EXCLUDED.priority,active=EXCLUDED.active,updated_by=EXCLUDED.updated_by,updated_at=NOW() WHERE ordering_printer_routes.business=${input.business}`;return {id}}
 throw new Error("Unknown hardware configuration action.")}

export async function controlPrintJob(input:{business:OrderingBusiness;jobId:string;action:"retry"|"reprint";reason:string;actor:OrderingActor}){manager(input.actor);await ensureOrderingHardwareSchema();const reason=input.reason.trim();if(!reason)throw new Error("A reason is required.");return withTransaction(async()=>{const sql=getSql();const job=(await sql`SELECT * FROM ordering_print_jobs WHERE id=${input.jobId} AND business=${input.business} FOR UPDATE`)[0];if(!job)throw new Error("Print job not found.");if(input.action==="retry"){if(!["failed","not_configured"].includes(job.status))throw new Error("Only failed or unconfigured jobs can be retried.");await sql`UPDATE ordering_print_jobs SET status='queued',queued_at=NOW(),next_attempt_at=NOW(),retry_count=retry_count+1,error_message='',actor_type=${input.actor.type},actor_id=${input.actor.id} WHERE id=${job.id}`;return {id:job.id,status:"queued"}}
 const id=randomUUID(),key=`reprint:${job.id}:${id}`;await sql`INSERT INTO ordering_print_jobs(id,business,order_id,check_id,payment_transaction_id,purpose,event_subtype,status,is_reprint,actor_type,actor_id,error_message,payload,location_id,device_id,idempotency_key,parent_job_id) VALUES(${id},${input.business},${job.order_id},${job.check_id},${job.payment_transaction_id},${job.purpose},'authorized_reprint','queued',TRUE,${input.actor.type},${input.actor.id},'',${JSON.stringify({...job.payload,reprintReason:reason})}::jsonb,${job.location_id},${job.device_id},${key},${job.id})`;return {id,status:"queued"}})}
