import { randomUUID } from "node:crypto";
import { getSql } from "@/lib/db";
import type { OrderingActor } from "@/lib/ordering-route-auth";
import { canManagePos } from "@/lib/ordering-route-auth";

let schemaPromise:Promise<void>|null=null;
export async function ensureRestaurantPlatformSchema(){
  if(!schemaPromise)schemaPromise=(async()=>{const sql=getSql();
    await sql`CREATE TABLE IF NOT EXISTS restaurant_concepts(id UUID PRIMARY KEY,concept_key TEXT NOT NULL UNIQUE,display_name TEXT NOT NULL,legacy_business TEXT NOT NULL CHECK(legacy_business IN('Corner Deli','Tiki')),service_model TEXT NOT NULL CHECK(service_model IN('quick_service','bar','table_service')),active BOOLEAN NOT NULL DEFAULT TRUE,branding JSONB NOT NULL DEFAULT '{}'::jsonb,features JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
    await sql`CREATE TABLE IF NOT EXISTS restaurant_locations(id UUID PRIMARY KEY,concept_id UUID NOT NULL REFERENCES restaurant_concepts(id),location_key TEXT NOT NULL,name TEXT NOT NULL,timezone TEXT NOT NULL DEFAULT 'America/New_York',active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(concept_id,location_key))`;
    await sql`CREATE TABLE IF NOT EXISTS restaurant_floor_plans(id UUID PRIMARY KEY,location_id UUID NOT NULL REFERENCES restaurant_locations(id),name TEXT NOT NULL,width INTEGER NOT NULL DEFAULT 1200 CHECK(width BETWEEN 320 AND 4000),height INTEGER NOT NULL DEFAULT 800 CHECK(height BETWEEN 320 AND 4000),active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(location_id,name))`;
    await sql`CREATE TABLE IF NOT EXISTS restaurant_sections(id UUID PRIMARY KEY,floor_plan_id UUID NOT NULL REFERENCES restaurant_floor_plans(id) ON DELETE CASCADE,name TEXT NOT NULL,color TEXT NOT NULL DEFAULT '#355c7d',sort_order INTEGER NOT NULL DEFAULT 0,active BOOLEAN NOT NULL DEFAULT TRUE,UNIQUE(floor_plan_id,name))`;
    await sql`CREATE TABLE IF NOT EXISTS restaurant_tables(id UUID PRIMARY KEY,floor_plan_id UUID NOT NULL REFERENCES restaurant_floor_plans(id) ON DELETE CASCADE,section_id UUID REFERENCES restaurant_sections(id),table_number TEXT NOT NULL,label TEXT NOT NULL,seats INTEGER NOT NULL DEFAULT 4 CHECK(seats BETWEEN 1 AND 50),shape TEXT NOT NULL DEFAULT 'rectangle' CHECK(shape IN('rectangle','round','booth','bar_seat')),x INTEGER NOT NULL DEFAULT 40,y INTEGER NOT NULL DEFAULT 40,width INTEGER NOT NULL DEFAULT 120,height INTEGER NOT NULL DEFAULT 80,active BOOLEAN NOT NULL DEFAULT TRUE,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(floor_plan_id,table_number))`;
    await sql`CREATE TABLE IF NOT EXISTS restaurant_table_sessions(id UUID PRIMARY KEY,table_id UUID NOT NULL REFERENCES restaurant_tables(id),order_id UUID REFERENCES ordering_orders(id),server_id TEXT NOT NULL,server_name TEXT NOT NULL,guest_count INTEGER NOT NULL CHECK(guest_count BETWEEN 1 AND 99),status TEXT NOT NULL DEFAULT 'open' CHECK(status IN('open','ordering','sent','paying','closed','transferred')),opened_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),closed_at TIMESTAMPTZ,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;
    await sql`CREATE UNIQUE INDEX IF NOT EXISTS restaurant_table_one_open_session_idx ON restaurant_table_sessions(table_id) WHERE status IN('open','ordering','sent','paying')`;
    await sql`CREATE TABLE IF NOT EXISTS restaurant_course_fires(id UUID PRIMARY KEY,order_id UUID NOT NULL REFERENCES ordering_orders(id),course_number INTEGER NOT NULL CHECK(course_number BETWEEN 1 AND 20),status TEXT NOT NULL CHECK(status IN('held','fired')),fired_by TEXT,fired_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(order_id,course_number))`;
    await sql`INSERT INTO restaurant_concepts(id,concept_key,display_name,legacy_business,service_model,features)VALUES('10000000-0000-4000-8000-000000000001','corner-deli','Corner Deli','Corner Deli','quick_service','{"kiosk":true,"customerDisplay":true}'::jsonb),('10000000-0000-4000-8000-000000000002','tiki','Tiki','Tiki','bar','{"tabs":true}'::jsonb),('10000000-0000-4000-8000-000000000003','new-restaurant','New Restaurant','Tiki','table_service','{"tables":true,"seats":true,"courses":true}'::jsonb)ON CONFLICT(concept_key)DO NOTHING`;
    await sql`INSERT INTO restaurant_locations(id,concept_id,location_key,name)VALUES('20000000-0000-4000-8000-000000000003','10000000-0000-4000-8000-000000000003','main','Main Dining Room')ON CONFLICT(concept_id,location_key)DO NOTHING`;
    await sql`INSERT INTO restaurant_floor_plans(id,location_id,name)VALUES('30000000-0000-4000-8000-000000000003','20000000-0000-4000-8000-000000000003','Main Floor')ON CONFLICT(location_id,name)DO NOTHING`;
  })().catch(error=>{schemaPromise=null;throw error});return schemaPromise;
}

export async function restaurantPlatform(conceptKey="new-restaurant"){
  await ensureRestaurantPlatformSchema();const sql=getSql();
  const concept=(await sql`SELECT * FROM restaurant_concepts WHERE concept_key=${conceptKey} AND active=TRUE`)[0];if(!concept)throw new Error("Restaurant concept was not found.");
  const locations=await sql`SELECT * FROM restaurant_locations WHERE concept_id=${concept.id} AND active=TRUE ORDER BY name`;
  const floors=await sql`SELECT floor.* FROM restaurant_floor_plans floor JOIN restaurant_locations location ON location.id=floor.location_id WHERE location.concept_id=${concept.id} AND floor.active=TRUE ORDER BY floor.name`;
  const tables=await sql`SELECT table_row.*,section.name section_name,section.color,session.id session_id,session.order_id,session.server_name,session.guest_count,session.status session_status,orders.display_number,orders.total_cents,orders.amount_due_cents FROM restaurant_tables table_row LEFT JOIN restaurant_sections section ON section.id=table_row.section_id LEFT JOIN restaurant_table_sessions session ON session.table_id=table_row.id AND session.status IN('open','ordering','sent','paying') LEFT JOIN ordering_orders orders ON orders.id=session.order_id WHERE table_row.floor_plan_id=ANY(${floors.map(row=>row.id)}) AND table_row.active=TRUE ORDER BY table_row.table_number`;
  const sections=await sql`SELECT section.* FROM restaurant_sections section WHERE section.floor_plan_id=ANY(${floors.map(row=>row.id)}) AND section.active=TRUE ORDER BY section.sort_order,section.name`;
  return{concept,locations,floors,sections,tables};
}

export async function configureRestaurant(input:{action:string;body:Record<string,unknown>;actor:OrderingActor}){
  await ensureRestaurantPlatformSchema();if(!canManagePos(input.actor))throw new Error("Manager or owner authorization is required.");const sql=getSql(),b=input.body;
  if(input.action==="rename_concept"){const name=String(b.name||"").trim();if(name.length<2||name.length>80)throw new Error("Enter a restaurant name.");await sql`UPDATE restaurant_concepts SET display_name=${name},updated_at=NOW() WHERE concept_key='new-restaurant'`;return{id:"new-restaurant",name}}
  if(input.action==="save_section"){const id=String(b.id||randomUUID()),name=String(b.name||"").trim(),floorId=String(b.floorPlanId||"");if(!name||!floorId)throw new Error("Floor and section name are required.");await sql`INSERT INTO restaurant_sections(id,floor_plan_id,name,color)VALUES(${id},${floorId},${name},${String(b.color||"#355c7d")})ON CONFLICT(id)DO UPDATE SET name=EXCLUDED.name,color=EXCLUDED.color`;return{id}}
  if(input.action==="save_table"){const id=String(b.id||randomUUID()),floorId=String(b.floorPlanId||""),number=String(b.tableNumber||"").trim(),label=String(b.label||number).trim(),seats=Math.trunc(Number(b.seats||4));if(!floorId||!number||!label||seats<1||seats>50)throw new Error("Floor, table number, label, and valid seats are required.");await sql`INSERT INTO restaurant_tables(id,floor_plan_id,section_id,table_number,label,seats,shape,x,y,width,height)VALUES(${id},${floorId},${b.sectionId?String(b.sectionId):null},${number},${label},${seats},${String(b.shape||"rectangle")},${Math.trunc(Number(b.x||40))},${Math.trunc(Number(b.y||40))},${Math.trunc(Number(b.width||120))},${Math.trunc(Number(b.height||80))})ON CONFLICT(id)DO UPDATE SET section_id=EXCLUDED.section_id,table_number=EXCLUDED.table_number,label=EXCLUDED.label,seats=EXCLUDED.seats,shape=EXCLUDED.shape,x=EXCLUDED.x,y=EXCLUDED.y,width=EXCLUDED.width,height=EXCLUDED.height,updated_at=NOW()`;return{id}}
  throw new Error("Unknown restaurant configuration action.");
}

export async function openTableSession(input:{tableId:string;guestCount:number;actor:OrderingActor}){
  await ensureRestaurantPlatformSchema();const sql=getSql(),table=(await sql`SELECT table_row.id FROM restaurant_tables table_row JOIN restaurant_floor_plans floor ON floor.id=table_row.floor_plan_id JOIN restaurant_locations location ON location.id=floor.location_id JOIN restaurant_concepts concept ON concept.id=location.concept_id WHERE table_row.id=${input.tableId} AND concept.concept_key='new-restaurant' AND table_row.active=TRUE`)[0];if(!table)throw new Error("Table was not found.");const existing=(await sql`SELECT * FROM restaurant_table_sessions WHERE table_id=${input.tableId} AND status IN('open','ordering','sent','paying')`)[0];if(existing)return existing;const guests=Math.trunc(input.guestCount);if(guests<1||guests>99)throw new Error("Enter a valid guest count.");return(await sql`INSERT INTO restaurant_table_sessions(id,table_id,server_id,server_name,guest_count,status)VALUES(${randomUUID()},${input.tableId},${input.actor.id},${input.actor.name},${guests},'open')RETURNING *`)[0];
}
