import { randomUUID } from "node:crypto";
import { ensureSchema, getSql } from "@/lib/db";
import { ensureOrderingCustomerSchema } from "@/lib/ordering-customer-schema";
import { ensureThreeCxCdrSchema } from "@/lib/three-cx-cdr";

export type ThreeCxLiveEvent={callId:string;callerNumber:string;queue?:string;line?:string;status?:string;startedAt?:string};
let schemaPromise:Promise<void>|null=null;
export async function ensureThreeCxLiveCallSchema(){if(!schemaPromise)schemaPromise=(async()=>{await ensureSchema();const sql=getSql();await sql`CREATE TABLE IF NOT EXISTS three_cx_live_calls(id UUID PRIMARY KEY,event_key TEXT NOT NULL UNIQUE,call_id TEXT NOT NULL,caller_phone TEXT NOT NULL,queue_number TEXT NOT NULL DEFAULT '',line_number TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'ringing',started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),acknowledged_at TIMESTAMPTZ,acknowledged_by TEXT,raw JSONB NOT NULL DEFAULT '{}'::jsonb)`;await sql`CREATE INDEX IF NOT EXISTS three_cx_live_calls_active_idx ON three_cx_live_calls(status,updated_at DESC)`})().catch(error=>{schemaPromise=null;throw error});await schemaPromise}
function phone(value:string){let digits=value.replace(/\D/g,"");if(digits.length===11&&digits[0]==="1")digits=digits.slice(1);return digits.slice(-10)}
export async function ingestThreeCxLiveCall(event:ThreeCxLiveEvent){await ensureThreeCxLiveCallSchema();const caller=phone(String(event.callerNumber||"")),callId=String(event.callId||"").trim(),queue=String(event.queue||"").replace(/\D/g,""),expected=String(process.env.THREE_CX_DELI_QUEUE||"90").replace(/\D/g,"");if(!callId||caller.length!==10)throw new Error("A call ID and valid caller number are required.");if(expected&&queue&&queue!==expected)return{accepted:false,reason:"not_deli_queue"};const status=["ringing","answered","ended","dismissed"].includes(String(event.status).toLowerCase())?String(event.status).toLowerCase():"ringing",key=`${callId}:${status}`;await getSql()`INSERT INTO three_cx_live_calls(id,event_key,call_id,caller_phone,queue_number,line_number,status,started_at,raw)VALUES(${randomUUID()},${key},${callId},${caller},${queue},${String(event.line||"")},${status},${event.startedAt||new Date().toISOString()},${JSON.stringify(event)}::jsonb)ON CONFLICT(event_key)DO UPDATE SET updated_at=NOW(),raw=EXCLUDED.raw`;if(status==="ended")await getSql()`UPDATE three_cx_live_calls SET status='ended',updated_at=NOW() WHERE call_id=${callId}`;return{accepted:true}}
export async function activeDeliCalls(){await ensureThreeCxLiveCallSchema();await Promise.all([ensureOrderingCustomerSchema(),ensureThreeCxCdrSchema()]);return getSql()`SELECT call.id,call.call_id,call.caller_phone,call.line_number,call.started_at,customer.id customer_id,customer.display_name,open_order.id open_order_id,open_order.display_number open_order_number,open_order.status open_order_status,history.recent_orders,last_call.last_call_at FROM three_cx_live_calls call LEFT JOIN LATERAL(SELECT c.id,c.display_name FROM ordering_customer_phones p JOIN ordering_customers c ON c.id=p.customer_id AND c.business='Corner Deli' WHERE RIGHT(regexp_replace(p.normalized_phone,'\\D','','g'),10)=call.caller_phone ORDER BY p.is_primary DESC,p.last_used_at DESC NULLS LAST LIMIT 1)customer ON TRUE LEFT JOIN LATERAL(SELECT o.id,o.display_number,o.status FROM ordering_orders o WHERE o.business='Corner Deli' AND RIGHT(regexp_replace(o.phone_snapshot,'\\D','','g'),10)=call.caller_phone AND o.status IN('draft','sent_to_kitchen','in_progress','ready') ORDER BY o.created_at DESC LIMIT 1)open_order ON TRUE LEFT JOIN LATERAL(SELECT COALESCE(jsonb_agg(jsonb_build_object('id',orders.id,'displayNumber',orders.display_number,'createdAt',orders.created_at,'serviceType',orders.service_type,'status',orders.status,'totalCents',orders.total_cents) ORDER BY orders.created_at DESC),'[]'::jsonb)recent_orders FROM(SELECT id,display_number,created_at,service_type,status,total_cents FROM ordering_orders WHERE business='Corner Deli' AND RIGHT(regexp_replace(phone_snapshot,'\\D','','g'),10)=call.caller_phone ORDER BY created_at DESC LIMIT 5)orders)history ON TRUE LEFT JOIN LATERAL(SELECT MAX(COALESCE(ended_at,started_at))last_call_at FROM three_cx_cdr_records WHERE RIGHT(regexp_replace(from_no,'\\D','','g'),10)=call.caller_phone)last_call ON TRUE WHERE call.status='ringing' AND call.acknowledged_at IS NULL AND call.updated_at>NOW()-INTERVAL '10 minutes' ORDER BY call.started_at DESC`}
export async function acknowledgeDeliCall(id:string,actorId:string){await ensureThreeCxLiveCallSchema();const rows=await getSql()`UPDATE three_cx_live_calls SET acknowledged_at=NOW(),acknowledged_by=${actorId},updated_at=NOW() WHERE id=${id} AND acknowledged_at IS NULL RETURNING id`;return Boolean(rows[0])}

export async function callerFromLivePosFeed(lineNumber = "") {
  await ensureThreeCxLiveCallSchema();
  const label=String(lineNumber),labelNumber=label.match(/\bline\s*([12])\b/i)?.[1],line=labelNumber==="1"?"95":labelNumber==="2"?"96":label.replace(/\D/g, "");
  const rows = await getSql()`
    SELECT DISTINCT ON (call_id) call_id,caller_phone,line_number,started_at
    FROM three_cx_live_calls
    WHERE status IN ('ringing','answered')
      AND updated_at > NOW()-INTERVAL '3 minutes'
      AND (${line}='' OR regexp_replace(line_number,'[^0-9]','','g')=${line})
    ORDER BY call_id,updated_at DESC
  `;
  if (rows.length !== 1) return "";
  return phone(String(rows[0].caller_phone || ""));
}
