"use client";
import { useEffect,useMemo,useState } from "react";

type Category={id:string;name:string;display_name:string;sort_order:number;active:boolean};
type Item={id:string;category_id:string;name:string;description:string;base_price_cents:number;available:boolean;active:boolean;sort_order:number};
type Variant={id:string;item_id:string;name:string;base_price_cents:number;available:boolean;active:boolean;sort_order:number};
type Group={id:string;name:string;prompt:string;min_selections:number;max_selections:number;active:boolean;sort_order:number};
type Option={id:string;group_id:string;name:string;price_delta_cents:number;available:boolean;active:boolean;sort_order:number};
type Data={categories:Category[];items:Item[];variants:Variant[];groups:Group[];options:Option[];links:{item_id:string;group_id:string;sort_order:number}[];localFields:{entity_type:string;entity_id:string;field_name:string}[]};
const dollars=(c:number)=>(c/100).toFixed(2),parseMoney=(v:string)=>{if(!/^\d+(\.\d{1,2})?$/.test(v.trim()))throw new Error("Enter a valid non-negative dollar amount.");return Math.round(Number(v)*100)};

export default function CatalogEditor({onChanged}:{onChanged:()=>void}){
 const[data,setData]=useState<Data|null>(null),[selectedCategory,setSelectedCategory]=useState(""),[selectedItem,setSelectedItem]=useState(""),[query,setQuery]=useState(""),[mode,setMode]=useState<"catalog"|"modifiers">("catalog"),[error,setError]=useState(""),[dirty,setDirty]=useState(false),[draft,setDraft]=useState<any>({});
 async function load(){const response=await fetch("/api/ordering/settings/menu/catalog?business=Corner%20Deli",{cache:"no-store"}),payload=await response.json();if(!response.ok){setError(payload.error);return}setData(payload);setSelectedCategory(value=>value||payload.categories.find((c:Category)=>c.active)?.id||"");}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{const warn=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue=""}};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn)},[dirty]);
 const post=async(body:any)=>{const response=await fetch("/api/ordering/settings/menu/catalog?business=Corner%20Deli",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),payload=await response.json();if(!response.ok)throw new Error(payload.error);if(payload.requiresConfirmation){const names=[...payload.dependencies.promotions,...payload.dependencies.loyalty].map((x:any)=>x.name).join(", ");if(!confirm(`This record is used by: ${names}. Archive it anyway?`))return null;return post({...body,confirmDependencies:true})}await load();onChanged();return payload};
 const selectItem=(item:Item)=>{if(dirty&&!confirm("Discard unsaved item changes?"))return;setSelectedItem(item.id);setDraft({name:item.name,description:item.description,price:dollars(item.base_price_cents),categoryId:item.category_id,available:item.available,active:item.active,sortOrder:item.sort_order});setDirty(false)};
 const matches=useMemo(()=>{if(!data)return[];const q=query.toLowerCase().trim();if(!q)return data.items.filter(i=>i.category_id===selectedCategory);const optionItemIds=new Set(data.links.filter(l=>data.options.some(o=>o.group_id===l.group_id&&o.name.toLowerCase().includes(q))).map(l=>l.item_id));const variantItemIds=new Set(data.variants.filter(v=>v.name.toLowerCase().includes(q)).map(v=>v.item_id));return data.items.filter(i=>i.name.toLowerCase().includes(q)||data.categories.find(c=>c.id===i.category_id)?.name.toLowerCase().includes(q)||optionItemIds.has(i.id)||variantItemIds.has(i.id))},[data,query,selectedCategory]);
 if(!data)return <p>{error||"Loading catalog…"}</p>;const current=data.items.find(i=>i.id===selectedItem),variants=data.variants.filter(v=>v.item_id===selectedItem),linked=data.links.filter(l=>l.item_id===selectedItem).map(l=>data.groups.find(g=>g.id===l.group_id)).filter(Boolean) as Group[];
 const edit=(key:string,value:any)=>{setDraft((old:any)=>({...old,[key]:value}));setDirty(true)};
 async function saveItem(){try{await post({action:"update",entity:"item",id:selectedItem,patch:{name:draft.name,description:draft.description,basePriceCents:parseMoney(draft.price),categoryId:draft.categoryId,available:draft.available,active:draft.active,sortOrder:Number(draft.sortOrder)}});setDirty(false);setError("")}catch(e){setError(e instanceof Error?e.message:"Save failed")}}
 return <section className="catalogEditor"><div className="catalogTools"><button className={mode==="catalog"?"selected":""} onClick={()=>setMode("catalog")}>CATALOG</button><button className={mode==="modifiers"?"selected":""} onClick={()=>setMode("modifiers")}>MODIFIERS</button><input aria-label="Search menu" placeholder="Search items, variants, modifiers…" value={query} onChange={e=>setQuery(e.target.value)}/></div>{error&&<p role="alert">{error}</p>}
 {mode==="catalog"?<div className="threePane"><aside><h2>Categories</h2><button onClick={async()=>{const name=prompt("New category name");if(name)await post({action:"create_category",name})}}>+ Category</button>{data.categories.map(c=><button key={c.id} className={selectedCategory===c.id?"selected":""} onClick={()=>setSelectedCategory(c.id)}>{c.display_name||c.name}{!c.active&&" (Archived)"}</button>)}</aside><div><h2>Items</h2><button onClick={async()=>{const name=prompt("New item name");if(name){const result=await post({action:"create_item",categoryId:selectedCategory,name,basePriceCents:0});if(result)selectItem({...data.items[0],id:result.id,category_id:selectedCategory,name,description:"",base_price_cents:0,available:true,active:true,sort_order:0})}}}>+ Item</button>{matches.map(i=><button key={i.id} className={selectedItem===i.id?"selected":""} onClick={()=>selectItem(i)}>{i.name}<small>${dollars(i.base_price_cents)}{!i.active&&" · Archived"}</small></button>)}</div><article>{current?<><h2>Edit item</h2>{dirty&&<strong className="dirty">Unsaved changes</strong>}<label>Name<input value={draft.name} onChange={e=>edit("name",e.target.value)}/></label><label>Description<textarea value={draft.description} onChange={e=>edit("description",e.target.value)}/></label><label>Base price ($)<input inputMode="decimal" value={draft.price} onChange={e=>edit("price",e.target.value)}/></label><label>Category<select value={draft.categoryId} onChange={e=>edit("categoryId",e.target.value)}>{data.categories.filter(c=>c.active).map(c=><option key={c.id} value={c.id}>{c.display_name||c.name}</option>)}</select></label><label><input type="checkbox" checked={draft.available} onChange={e=>edit("available",e.target.checked)}/> Available</label><label><input type="checkbox" checked={draft.active} onChange={e=>edit("active",e.target.checked)}/> Active</label><div><button disabled={!dirty} onClick={()=>void saveItem()}>SAVE</button><button onClick={()=>void post({action:"duplicate_item",entity:"item",id:current.id,name:`${current.name} Copy`})}>Duplicate Item</button><button onClick={()=>void post({action:"archive",entity:"item",id:current.id})}>Archive</button></div><h3>Variants</h3>{variants.map(v=><VariantRow key={v.id} value={v} post={post}/>) }<button onClick={async()=>{const name=prompt("Variant name");if(name)await post({action:"create_variant",itemId:current.id,name,basePriceCents:current.base_price_cents})}}>+ Variant</button><h3>Modifier groups</h3>{linked.map(g=><span key={g.id} className="pill">{g.name}</span>)}</>:<p>Select an item.</p>}</article></div>:
 <div className="modifierGrid"><div><h2>Modifier groups</h2><button onClick={async()=>{const name=prompt("New modifier group name");if(name)await post({action:"create_modifier_group",name,minSelections:0,maxSelections:1})}}>+ Group</button>{data.groups.map(g=><details key={g.id}><summary>{g.name} · {g.min_selections}–{g.max_selections}</summary><GroupEditor group={g} post={post}/><h3>Options</h3>{data.options.filter(o=>o.group_id===g.id).map(o=><OptionRow key={o.id} option={o} post={post}/>) }<button onClick={async()=>{const name=prompt("New option name");if(name)await post({action:"create_modifier_option",groupId:g.id,name,priceDeltaCents:0})}}>+ Option</button></details>)}</div></div>}
 <style jsx>{`.catalogTools{display:flex;gap:8px;margin:12px 0}.catalogTools input{flex:1}.threePane{display:grid;grid-template-columns:220px 300px 1fr;gap:12px}.threePane>aside,.threePane>div,.threePane>article,.modifierGrid>div{background:#fff;padding:12px;border-radius:10px;min-height:520px}.threePane aside button,.threePane>div>button{display:flex;width:100%;justify-content:space-between;text-align:left;margin:4px 0}.threePane small{display:block}.threePane article{display:block}.threePane article label{margin:9px 0}.threePane article input:not([type=checkbox]),.threePane article textarea,.threePane article select{width:100%}.dirty{color:#9b4700}.pill{display:inline-block;padding:6px 9px;background:#e8eee9;border-radius:99px;margin:3px}details{background:#fff;padding:12px;margin:8px 0;border-radius:9px}summary{font-weight:800;cursor:pointer}@media(max-width:900px){.threePane{grid-template-columns:1fr}.threePane>aside,.threePane>div{min-height:auto;max-height:280px;overflow:auto}}`}</style></section>
}

function VariantRow({value,post}:{value:Variant;post:(b:any)=>Promise<any>}){const[price,setPrice]=useState(dollars(value.base_price_cents)),[name,setName]=useState(value.name);return <div className="row"><input aria-label="Variant name" value={name} onChange={e=>setName(e.target.value)}/><input aria-label="Variant price" value={price} onChange={e=>setPrice(e.target.value)}/><button onClick={()=>void post({action:"update",entity:"variant",id:value.id,patch:{name,basePriceCents:parseMoney(price)}})}>Save</button><button onClick={()=>void post({action:"archive",entity:"variant",id:value.id})}>Archive</button></div>}
function GroupEditor({group,post}:{group:Group;post:(b:any)=>Promise<any>}){const[min,setMin]=useState(group.min_selections),[max,setMax]=useState(group.max_selections),[name,setName]=useState(group.name);return <div className="row"><input value={name} onChange={e=>setName(e.target.value)}/><label>Min<input type="number" min="0" value={min} onChange={e=>setMin(Number(e.target.value))}/></label><label>Max<input type="number" min="1" value={max} onChange={e=>setMax(Number(e.target.value))}/></label><button onClick={()=>void post({action:"update",entity:"modifier_group",id:group.id,patch:{name,minSelections:min,maxSelections:max}})}>Save</button></div>}
function OptionRow({option,post}:{option:Option;post:(b:any)=>Promise<any>}){const[name,setName]=useState(option.name),[price,setPrice]=useState(dollars(option.price_delta_cents));return <div className="row"><input value={name} onChange={e=>setName(e.target.value)}/><input aria-label={`${option.name} price`} value={price} onChange={e=>setPrice(e.target.value)}/><button onClick={()=>void post({action:"update",entity:"modifier_option",id:option.id,patch:{name,priceDeltaCents:parseMoney(price)}})}>Save</button><button onClick={()=>void post({action:"archive",entity:"modifier_option",id:option.id})}>Archive</button></div>}
