"use client";

import { useCallback, useEffect, useState } from "react";

type Category = { id:string; imported_name:string; imported_display_name:string; imported_parent_id:string|null; imported_sort_order:number; display_name:string|null; parent_id:string|null; parent_id_overridden:boolean|null; sort_order:number|null; visible:boolean|null };
type Item = { id:string; imported_name:string; imported_category_id:string; imported_sort_order:number; display_name:string|null; category_id:string|null; sort_order:number|null; visible:boolean|null };
type Modifier = { item_id:string; item_name:string; group_id:string; group_name:string; context:string|null; sort_order:number|null };
type Data = { categories:Category[]; items:Item[]; modifiers:Modifier[] };

export default function MenuSettingsClient() {
  const [data,setData]=useState<Data|null>(null); const [error,setError]=useState(""); const [section,setSection]=useState<"categories"|"items"|"modifiers">("categories");
  const load=useCallback(()=>fetch("/api/ordering/settings/menu",{cache:"no-store"}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error);setData(p);setError("");}).catch(e=>setError(e.message)),[]);
  useEffect(()=>{load();},[load]);
  async function update(targetType:string,targetId:string,field:string,value:unknown,itemId?:string,reset=false){setError("");const response=await fetch("/api/ordering/settings/menu",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({targetType,targetId,itemId,field,value,reset})});const payload=await response.json();if(!response.ok){setError(payload.error||"Update failed.");return;}await load();}
  if(!data)return <main className="posSettings"><h1>Corner Deli Menu Settings</h1><p>{error||"Loading…"}</p></main>;
  return <main className="posSettings"><header><div><a href="/pos/deli">← Cashier POS</a><h1>Menu presentation</h1><p>Imported Rezku values stay intact. Each local override can be reset independently.</p></div></header>
    {error&&<p role="alert">{error}</p>}<nav>{(["categories","items","modifiers"] as const).map(value=><button key={value} className={section===value?"selected":""} onClick={()=>setSection(value)}>{value.toUpperCase()}</button>)}</nav>
    {section==="categories"&&<section><h2>Categories</h2>{data.categories.map(row=><article key={row.id}><strong>{row.display_name||row.imported_display_name||row.imported_name}</strong><small>{row.display_name!==null||row.parent_id!==null||row.sort_order!==null||row.visible!==null?"Overridden":"Imported"}</small><label>Label <input defaultValue={row.display_name??row.imported_display_name??row.imported_name} onBlur={e=>void update("category",row.id,"display_name",e.currentTarget.value)}/></label><label>Parent <select value={row.parent_id??row.imported_parent_id??""} onChange={e=>void update("category",row.id,"parent_id",e.target.value)}><option value="">Top level</option>{data.categories.filter(c=>c.id!==row.id).map(c=><option key={c.id} value={c.id}>{c.display_name||c.imported_display_name||c.imported_name}</option>)}</select></label><label>Sort <input type="number" value={row.sort_order??row.imported_sort_order} onChange={e=>void update("category",row.id,"sort_order",Number(e.target.value))}/></label><button onClick={()=>void update("category",row.id,"visible",row.visible===false)}>{row.visible===false?"SHOW":"HIDE"}</button><button onClick={()=>void update("category",row.id,"display_name",null,undefined,true)}>RESET LABEL</button><button onClick={()=>void update("category",row.id,"parent_id",null,undefined,true)}>RESET PARENT</button><button onClick={()=>void update("category",row.id,"sort_order",null,undefined,true)}>RESET SORT</button>{row.visible!==null&&<button onClick={()=>void update("category",row.id,"visible",null,undefined,true)}>RESET VISIBILITY</button>}</article>)}</section>}
    {section==="items"&&<section><h2>Items</h2>{data.items.map(row=><article key={row.id}><strong>{row.display_name||row.imported_name}</strong><small>{row.display_name!==null||row.category_id!==null||row.sort_order!==null||row.visible!==null?"Overridden":"Imported"}</small><label>Label <input defaultValue={row.display_name??row.imported_name} onBlur={e=>void update("item",row.id,"display_name",e.currentTarget.value)}/></label><label>Category <select value={row.category_id??row.imported_category_id} onChange={e=>void update("item",row.id,"category_id",e.target.value)}>{data.categories.map(c=><option key={c.id} value={c.id}>{c.display_name||c.imported_display_name||c.imported_name}</option>)}</select></label><label>Sort <input type="number" value={row.sort_order??row.imported_sort_order} onChange={e=>void update("item",row.id,"sort_order",Number(e.target.value))}/></label><button onClick={()=>void update("item",row.id,"visible",row.visible===false)}>{row.visible===false?"SHOW":"HIDE"}</button><button onClick={()=>void update("item",row.id,"display_name",null,undefined,true)}>RESET LABEL</button><button onClick={()=>void update("item",row.id,"category_id",null,undefined,true)}>RESET CATEGORY</button><button onClick={()=>void update("item",row.id,"sort_order",null,undefined,true)}>RESET SORT</button>{row.visible!==null&&<button onClick={()=>void update("item",row.id,"visible",null,undefined,true)}>RESET VISIBILITY</button>}</article>)}</section>}
    {section==="modifiers"&&<section><h2>Modifier / combo presentation</h2><p>Contexts and ordering change presentation only; imported price and availability remain authoritative.</p>{data.modifiers.map(row=><article key={`${row.item_id}-${row.group_id}`}><strong>{row.item_name}</strong><span>{row.group_name}</span><small>{row.context||row.sort_order!==null?"Overridden":"Imported"}</small><label>Context <select value={row.context||"ordinary"} onChange={e=>void update("modifier",row.group_id,"context",e.target.value,row.item_id)}><option value="ordinary">Ordinary item modifier</option><option value="combo_trigger">Combo side choice</option><option value="dependent">Dependent combo option</option><option value="hidden">Hidden</option></select></label><label>Sort <input type="number" value={row.sort_order??0} onChange={e=>void update("modifier",row.group_id,"sort_order",Number(e.target.value),row.item_id)}/></label><button onClick={()=>void update("modifier",row.group_id,"context",null,row.item_id,true)}>RESET CONTEXT</button>{row.sort_order!==null&&<button onClick={()=>void update("modifier",row.group_id,"sort_order",null,row.item_id,true)}>RESET SORT</button>}</article>)}</section>}
    <style jsx>{`.posSettings{font-family:system-ui;max-width:1200px;margin:auto;padding:24px;background:#f6f3ed;min-height:100vh}.posSettings nav{display:flex;gap:8px;position:sticky;top:0;background:#f6f3ed;padding:12px 0}.posSettings button,.posSettings input,.posSettings select{min-height:44px;font:inherit}.selected{background:#173f35;color:white}section article{display:grid;grid-template-columns:minmax(180px,1fr) repeat(6,auto);gap:10px;align-items:center;background:white;margin:8px 0;padding:12px;border-radius:8px}label{display:flex;gap:5px;align-items:center}small{color:#666}@media(max-width:900px){section article{grid-template-columns:1fr 1fr}}`}</style>
  </main>;
}
