"use client";
import{useCallback,useEffect,useState}from"react";
import MediaManager from"./media-manager";
type Row={id:string;imported_name:string;effective_name:string;imported_parent_id?:string|null;imported_category_id?:string;imported_sort_order:number;display_name:string|null;parent_id?:string|null;parent_id_overridden?:boolean;category_id?:string|null;sort_order:number|null;visible:boolean|null;media_id?:string|null;alt_text?:string|null};
type Data={channel:"pos"|"web";categories:Row[];items:Row[];modifiers:Array<{item_id:string;item_name:string;group_id:string;group_name:string;context:string|null;sort_order:number|null}>};
export default function MenuSettingsClient(){
 const[channel,setChannel]=useState<"pos"|"web">("pos"),[section,setSection]=useState<"categories"|"items"|"modifiers">("categories"),[data,setData]=useState<Data|null>(null),[error,setError]=useState("");
 const load=useCallback(async()=>{try{const r=await fetch(`/api/ordering/settings/menu?channel=${channel}`,{cache:"no-store"}),p=await r.json();if(!r.ok)throw new Error(p.error);setData(p);setError("")}catch(e){setError(e instanceof Error?e.message:"Load failed")}},[channel]);useEffect(()=>{void load()},[load]);
 async function update(type:string,id:string,field:string,value:unknown,reset=false,itemId?:string){const r=await fetch("/api/ordering/settings/menu",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({targetType:type,targetId:id,itemId,field,value,reset,channel})});const p=await r.json();if(!r.ok){setError(p.error);return}await load()}
 async function move(type:"category"|"item",rows:Row[],index:number,delta:number){const other=index+delta;if(other<0||other>=rows.length)return;await Promise.all([[rows[index],other],[rows[other],index]].map(([row,order])=>update(type,(row as Row).id,"sort_order",order)))}
 if(!data)return <main className="posSettings"><h1>Menu presentation</h1><p>{error||"Loading…"}</p></main>;
 const rows=section==="categories"?data.categories:data.items;
 return <main className="posSettings"><header><a href="/pos/deli">← Cashier POS</a><h1>Menu presentation</h1><p>Imported values remain unchanged. Channel overrides inherit shared/imported values until set.</p></header>
 <div className="channel" role="group" aria-label="Presentation channel"><button className={channel==="pos"?"selected":""} onClick={()=>setChannel("pos")}>POS</button><button className={channel==="web"?"selected":""} onClick={()=>setChannel("web")}>WEBSITE</button><button onClick={async()=>{if(!confirm("Copy the complete POS presentation to Website?"))return;const r=await fetch("/api/ordering/settings/menu",{method:"POST"});if(!r.ok){setError("Could not copy POS presentation.");return}setChannel("web")}}>COPY POS PRESENTATION TO WEBSITE</button></div>
 <nav>{(["categories","items","modifiers"]as const).map(v=><button className={section===v?"selected":""} key={v} onClick={()=>setSection(v)}>{v.toUpperCase()}</button>)}</nav>{error&&<p role="alert">{error}</p>}
 {section!=="modifiers"&&<section><h2>{section} · effective {channel} order</h2>{rows.map((row,index)=><article key={row.id}><strong>{row.effective_name}</strong><label>Name <input defaultValue={row.display_name??row.effective_name} onBlur={e=>void update(section==="categories"?"category":"item",row.id,"display_name",e.currentTarget.value)}/></label><label>Sort <input type="number" value={row.sort_order??row.imported_sort_order} onChange={e=>void update(section==="categories"?"category":"item",row.id,"sort_order",Number(e.target.value))}/></label>{section==="categories"?<label>Parent <select value={row.parent_id_overridden?(row.parent_id||""):(row.imported_parent_id||"")} onChange={e=>void update("category",row.id,"parent_id",e.target.value)}><option value="">Top level</option>{data.categories.filter(c=>c.id!==row.id).map(c=><option value={c.id} key={c.id}>{c.effective_name}</option>)}</select></label>:<label>Category <select value={row.category_id??row.imported_category_id} onChange={e=>void update("item",row.id,"category_id",e.target.value)}>{data.categories.map(c=><option value={c.id} key={c.id}>{c.effective_name}</option>)}</select></label>}<button onClick={()=>void move(section==="categories"?"category":"item",rows,index,-1)}>Move Up</button><button onClick={()=>void move(section==="categories"?"category":"item",rows,index,1)}>Move Down</button><button onClick={()=>void update(section==="categories"?"category":"item",row.id,"visible",row.visible===false)}>{row.visible===false?"Show":"Hide"}</button><button onClick={()=>void update(section==="categories"?"category":"item",row.id,"sort_order",null,true)}>Reset Sort</button>{section==="items"&&<a href={`/api/ordering/settings/menu/media?itemId=${row.id}`}>{row.media_id?"Replace / remove image":"Upload image"}</a>}</article>)}</section>}
 {section==="modifiers"&&<section><h2>Modifier / combo presentation</h2>{data.modifiers.map(row=><article key={`${row.item_id}-${row.group_id}`}><strong>{row.item_name} · {row.group_name}</strong><label>Context <select value={row.context||"ordinary"} onChange={e=>void update("modifier",row.group_id,"context",e.target.value,false,row.item_id)}><option value="ordinary">Ordinary</option><option value="combo_trigger">Combo trigger</option><option value="dependent">Dependent</option><option value="hidden">Hidden</option></select></label></article>)}</section>}
 {section==="items"&&<MediaManager items={data.items} onDone={()=>void load()}/>}<style jsx>{`.posSettings{font-family:system-ui;max-width:1300px;margin:auto;padding:24px;background:#f6f3ed;min-height:100vh}.channel,nav{display:flex;gap:8px;position:sticky;top:0;background:#f6f3ed;padding:8px;z-index:2}button,input,select{min-height:44px;font:inherit}.selected{background:#173f35;color:#fff}article{display:grid;grid-template-columns:minmax(220px,1fr) repeat(7,auto);gap:8px;align-items:center;background:#fff;margin:7px 0;padding:10px;border-radius:8px}label{display:flex;gap:4px;align-items:center}@media(max-width:900px){article{grid-template-columns:1fr 1fr}}`}</style></main>
}
