"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import MediaManager from "./media-manager";
import CatalogEditor from "./catalog-editor";

type Row={id:string;imported_name:string;effective_name:string;imported_description?:string;effective_description?:string;effective_print_name?:string|null;imported_parent_id?:string|null;imported_category_id?:string;imported_sort_order:number;display_name:string|null;description?:string|null;parent_id?:string|null;parent_id_overridden?:boolean;category_id?:string|null;sort_order:number|null;visible:boolean|null;media_id?:string|null};
type Variant={id:string;item_id:string;imported_name:string;effective_print_name:string;print_name:string|null};
type Group={item_id:string;item_name:string;group_id:string;group_name:string;min_selections:number;max_selections:number;context:string|null;parent_group_id:string|null;parent_option_ids:string[]|null;sort_order:number|null;print_order:number|null;header_modifier:boolean|null;suppress_default_on_ticket:boolean|null;presentation_style:string|null;component_key:string|null;component_label:string|null;component_order:number|null;dependency_scope:string|null};
type Option={item_id:string;group_id:string;id:string;imported_name:string;effective_print_name:string;print_name:string|null;print_order:number;print_section:string|null;suppress_when_default:boolean|null;print_only_when_changed:boolean|null;default_selected:boolean};
type Availability={target_type:string;target_id:string;enabled:boolean;days_of_week:number[];starts_at:string|null;ends_at:string|null;valid_from:string|null;valid_through:string|null};
type Data={channel:"pos"|"web";categories:Row[];items:Row[];modifiers:Group[];variants:Variant[];modifierOptions:Option[];availability:Availability[]};
type Section="catalog"|"presentation"|"layout"|"availability"|"media";
const weekdays=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];

export default function MenuSettingsClient(){
 const[channel,setChannel]=useState<"pos"|"web">("pos"),[section,setSection]=useState<Section>("catalog"),[data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[preview,setPreview]=useState("");
 const load=useCallback(async()=>{try{const response=await fetch(`/api/ordering/settings/menu?channel=${channel}`,{cache:"no-store"}),payload=await response.json();if(!response.ok)throw new Error(payload.error);setData(payload);setError("")}catch(reason){setError(reason instanceof Error?reason.message:"Load failed")}},[channel]);
 useEffect(()=>{void load()},[load]);
 async function update(type:string,id:string,field:string,value:unknown,reset=false,itemId?:string){const response=await fetch("/api/ordering/settings/menu",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({targetType:type,targetId:id,itemId,field,value,reset,channel})}),payload=await response.json();if(!response.ok){setError(payload.error);return}await load()}
 async function availability(targetType:string,targetId:string,patch:Partial<Availability>){const current=data?.availability.find(rule=>rule.target_type===targetType&&rule.target_id===targetId),next={...current,...patch};const response=await fetch("/api/ordering/settings/operations",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({action:"upsert_menu_availability",targetType,targetId,enabled:next.enabled!==false,daysOfWeek:next.days_of_week||[],startsAt:next.starts_at||null,endsAt:next.ends_at||null,validFrom:next.valid_from||null,validThrough:next.valid_through||null})}),payload=await response.json();if(!response.ok){setError(payload.error);return}await load()}
 async function showPreview(itemId:string){const item=data?.items.find(row=>row.id===itemId),variant=data?.variants.find(row=>row.item_id===itemId),ids=data?.modifierOptions.filter(row=>row.item_id===itemId).slice(0,4).map(row=>row.id)||[];const response=await fetch("/api/ordering/settings/menu/print-preview",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({itemId,variantId:variant?.id,modifierOptionIds:ids})}),payload=await response.json();setPreview(response.ok?payload.preview:payload.error)}
 const itemMap=useMemo(()=>new Map(data?.items.map(item=>[item.id,item])||[]),[data]);
 if(!data)return <main className="menuAdmin"><h1>Menu configuration</h1><p>{error||"Loading…"}</p></main>;
 return <main className="menuAdmin"><header><a href="/pos/deli">← Cashier POS</a><h1>Menu configuration</h1><p>Stable-ID overrides survive imports. All changes are manager-audited.</p></header>
 <div className="toolbar"><div role="group" aria-label="Presentation channel"><button className={channel==="pos"?"selected":""} onClick={()=>setChannel("pos")}>POS</button><button className={channel==="web"?"selected":""} onClick={()=>setChannel("web")}>WEBSITE</button></div><nav>{(["catalog","presentation","layout","availability","media"]as Section[]).map(value=><button className={section===value?"selected":""} key={value} onClick={()=>setSection(value)}>{value.toUpperCase()}</button>)}</nav></div>{error&&<p role="alert">{error}</p>}
 {section==="catalog"&&<CatalogEditor onChanged={()=>void load()} printing={data} updatePrint={update} showPreview={showPreview} preview={preview}/>}
 {section==="media"&&<MediaManager items={data.items} onDone={()=>void load()}/>}
 {section==="presentation"&&<section><h2>{channel.toUpperCase()} names, descriptions, and visibility</h2>{data.categories.map(row=><article key={row.id}><strong>Category · {row.effective_name}</strong><label>Display name<input defaultValue={row.display_name??row.effective_name} onBlur={event=>void update("category",row.id,"display_name",event.currentTarget.value)}/></label><label>Visible<input type="checkbox" checked={row.visible!==false} onChange={event=>void update("category",row.id,"visible",event.target.checked)}/></label></article>)}{data.items.map(row=><article key={row.id}><strong>{row.effective_name}</strong><label>Display name<input defaultValue={row.display_name??row.effective_name} onBlur={event=>void update("item",row.id,"display_name",event.currentTarget.value)}/></label><label>Description<textarea defaultValue={row.description??row.effective_description??""} onBlur={event=>void update("item",row.id,"description",event.currentTarget.value)}/></label><label>Visible<input type="checkbox" checked={row.visible!==false} onChange={event=>void update("item",row.id,"visible",event.target.checked)}/></label></article>)}</section>}
 {section==="layout"&&<section><h2>Complex modifier layout and dependencies</h2><p>Component keys scope dependent choices to the Universal, Salad, Side 1/2/3, or any future component instance.</p>{data.modifiers.map(group=><article key={`${group.item_id}-${group.group_id}`}><strong>{group.item_name} · {group.group_name}</strong><label>Presentation<select value={group.presentation_style||"grid"} onChange={event=>void update("modifier",group.group_id,"presentation_style",event.target.value,false,group.item_id)}><option value="grid">Grid</option><option value="list">List</option><option value="staged">Staged</option><option value="component_columns">Component column</option><option value="universal">Universal</option></select></label><label>Component key<input value={group.component_key||""} onChange={event=>void update("modifier",group.group_id,"component_key",event.target.value,false,group.item_id)}/></label><label>Label<input value={group.component_label||""} onChange={event=>void update("modifier",group.group_id,"component_label",event.target.value,false,group.item_id)}/></label><label>Order<input type="number" value={group.component_order??0} onChange={event=>void update("modifier",group.group_id,"component_order",Number(event.target.value),false,group.item_id)}/></label><label>Context<select value={group.context||"ordinary"} onChange={event=>void update("modifier",group.group_id,"context",event.target.value,false,group.item_id)}><option value="ordinary">Always</option><option value="combo_trigger">Staged trigger</option><option value="dependent">Hidden until triggered</option><option value="hidden">Hidden</option></select></label>{group.context==="dependent"&&<><label>Parent group<select value={group.parent_group_id||""} onChange={event=>void update("modifier",group.group_id,"parent_group_id",event.target.value,false,group.item_id)}><option value="">Choose parent</option>{data.modifiers.filter(candidate=>candidate.item_id===group.item_id&&candidate.group_id!==group.group_id).map(candidate=><option key={candidate.group_id} value={candidate.group_id}>{candidate.group_name}</option>)}</select></label><label>Trigger options<select multiple value={group.parent_option_ids||[]} onChange={event=>void update("modifier",group.group_id,"parent_option_ids",Array.from(event.target.selectedOptions,option=>option.value),false,group.item_id)}>{data.modifierOptions.filter(option=>option.item_id===group.item_id&&option.group_id===group.parent_group_id).map(option=><option key={option.id} value={option.id}>{option.imported_name}</option>)}</select></label></>}</article>)}</section>}
 {section==="availability"&&<section><h2>Scheduled availability</h2><p>Rules use America/New_York and the order’s scheduled fulfillment time.</p>{[...data.items.map(item=>({type:"item",id:item.id,label:item.effective_name})),...data.variants.map(row=>({type:"variant",id:row.id,label:`${itemMap.get(row.item_id)?.effective_name} · ${row.imported_name}`})),...data.modifierOptions.map(row=>({type:"modifier_option",id:row.id,label:`${itemMap.get(row.item_id)?.effective_name} · ${row.imported_name}`}))].map(target=>{const rule=data.availability.find(candidate=>candidate.target_type===target.type&&candidate.target_id===target.id);return <article key={`${target.type}-${target.id}`}><strong>{target.label}</strong><span>{target.type.replace("_"," ")}</span><div className="days">{weekdays.map((day,index)=><label key={day}><input type="checkbox" checked={rule?.days_of_week.includes(index)||false} onChange={event=>{const days=new Set(rule?.days_of_week||[]);event.target.checked?days.add(index):days.delete(index);void availability(target.type,target.id,{days_of_week:[...days]})}}/>{day}</label>)}</div><label>Start<input type="time" defaultValue={rule?.starts_at?.slice(0,5)||""} onBlur={event=>void availability(target.type,target.id,{starts_at:event.currentTarget.value||null})}/></label><label>End<input type="time" defaultValue={rule?.ends_at?.slice(0,5)||""} onBlur={event=>void availability(target.type,target.id,{ends_at:event.currentTarget.value||null})}/></label><label>From<input type="date" defaultValue={rule?.valid_from?.slice(0,10)||""} onBlur={event=>void availability(target.type,target.id,{valid_from:event.currentTarget.value||null})}/></label><label>Through<input type="date" defaultValue={rule?.valid_through?.slice(0,10)||""} onBlur={event=>void availability(target.type,target.id,{valid_through:event.currentTarget.value||null})}/></label></article>})}</section>}
 <style jsx>{`.menuAdmin{font-family:system-ui;max-width:1440px;margin:auto;padding:24px;background:#f6f3ed;min-height:100vh}.toolbar,.toolbar>div,nav,.days{display:flex;gap:8px;flex-wrap:wrap}.toolbar{position:sticky;top:0;background:#f6f3ed;padding:8px;z-index:3;justify-content:space-between}button,input,select,textarea{min-height:42px;font:inherit}.selected{background:#173f35;color:#fff}article{display:grid;grid-template-columns:minmax(220px,1fr) repeat(4,minmax(120px,auto));gap:10px;align-items:center;background:#fff;margin:8px 0;padding:12px;border-radius:9px}label{display:grid;gap:3px;font-size:12px;font-weight:700}.optionList{grid-column:1/-1}.optionList>div{display:grid;grid-template-columns:1fr 2fr 100px 1fr auto auto;gap:7px;margin:5px 0}pre{background:#15201d;color:#fff;padding:20px;font-size:18px;white-space:pre-wrap}@media(max-width:900px){article{grid-template-columns:1fr 1fr}.optionList>div{grid-template-columns:1fr 1fr}}`}</style></main>
}
