"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import type { Business, SessionView } from "@/lib/types";
import "../control-center.css";

type PayrollRow={employee:string;hours:number;regularHours:number;overtimeHours:number;driverTipHours:number;tips:number;pickupTips:number;deliveryTips:number;manualTips?:number};
type Punch={id:string;employeeName:string;position:string;clockIn:string;clockOut:string|null;status:string;notes:string;source:string};
type Version={id:string;weekStart:string;weekEnd:string;version:number;status:string;generatedBy:string;generatedAt:string;lockedBy:string|null;lockedAt:string|null};
type Dashboard={summary:{source:string;weekStart:string;weekEnd:string;rows:PayrollRow[];overrides:Array<any>;unmatchedTips:Array<any>};punches:Punch[];versions:Version[];adjustments:Array<any>;auditEvents:Array<any>};
const dollars=(v:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(v||0);const hours=(v:number)=>Number(v||0).toFixed(2);
function monday(){const d=new Date();const x=(d.getDay()+6)%7;d.setDate(d.getDate()-x-7);return d.toISOString().slice(0,10);}async function err(r:Response){const p=await r.json().catch(()=>null) as {error?:string}|null;return p?.error||`Request failed (${r.status}).`;}
export default function PayrollControlPage(){
 const [session,setSession]=useState<SessionView|null>(null),[business,setBusiness]=useState<Business>("Corner Deli"),[weekStart,setWeekStart]=useState(monday()),[data,setData]=useState<Dashboard|null>(null),[notice,setNotice]=useState(""),[busy,setBusy]=useState(false),[editing,setEditing]=useState<Punch|null>(null);
 useEffect(()=>{fetch("/api/auth/session",{cache:"no-store"}).then(r=>r.json()).then(setSession)},[]);
 async function load(){const r=await fetch(`/api/payroll-control?business=${encodeURIComponent(business)}&weekStart=${weekStart}`,{cache:"no-store"});if(!r.ok)throw new Error(await err(r));setData(await r.json());}
 useEffect(()=>{if(session?.authenticated)load().catch(e=>setNotice(e.message));},[session?.authenticated,business,weekStart]);
 async function post(body:Record<string,unknown>){setBusy(true);setNotice("");try{const r=await fetch("/api/payroll-control",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw new Error(await err(r));const result=await r.json();await load();return result;}catch(e){setNotice(e instanceof Error?e.message:String(e));throw e;}finally{setBusy(false)}}
 const totals=useMemo(()=>data?.summary.rows.reduce((a,r)=>({hours:a.hours+r.hours,ot:a.ot+r.overtimeHours,tips:a.tips+r.tips}),{hours:0,ot:0,tips:0})||{hours:0,ot:0,tips:0},[data]);
 async function correct(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;const f=new FormData(e.currentTarget);await post({action:"punch-correct",business,sourceType:business==="Tiki"?"Tiki":"Rezku",sourceId:editing.id,employeeName:f.get("employeeName"),position:f.get("position"),clockIn:new Date(String(f.get("clockIn"))).toISOString(),clockOut:f.get("clockOut")?new Date(String(f.get("clockOut"))).toISOString():null,reason:f.get("reason")});setEditing(null);setNotice("Punch corrected with before-and-after audit history.")}
 async function tipOverride(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await post({action:"tip-override-create",business,weekStart,sourceTransactionId:f.get("sourceTransactionId"),employeeName:f.get("employeeName"),amount:Number(f.get("amount")||0),reason:f.get("reason")});e.currentTarget.reset();setNotice("Tip override applied.")}
 if(!session)return <main className="controlPage">Loading…</main>;if(!session.authenticated)return <main className="controlPage"><a href="/signin">Sign in to Corner Ops</a></main>;
 return <main className="controlPage"><header className="controlHeader"><div><p className="eyebrow">Payroll control</p><h1>{business} payroll</h1><p>Correct punches, allocate exceptions, version payroll, lock it, and preserve the paper trail humans insist on generating.</p></div><div className="controlActions"><div className="businessPills">{(["Corner Deli","Tiki"] as Business[]).map(b=><button key={b} className={business===b?"active":""} onClick={()=>setBusiness(b)}>{b}</button>)}</div><label>Week <input type="date" value={weekStart} onChange={e=>setWeekStart(e.target.value)}/></label><button onClick={()=>load()} disabled={busy}>Recalculate</button><a href="/ops">Operations</a></div></header>{notice&&<div className="noticeBar">{notice}</div>}<div className="controlGrid">
 <section className="controlCard"><div className="metricGrid"><div className="metric"><span>Total hours</span><strong>{hours(totals.hours)}</strong></div><div className="metric"><span>Overtime</span><strong>{hours(totals.ot)}</strong></div><div className="metric"><span>Tips</span><strong>{dollars(totals.tips)}</strong></div><div className="metric"><span>Unmatched tips</span><strong>{data?.summary.unmatchedTips.length||0}</strong></div></div></section>
 <section className="controlCard"><div className="controlActions"><button className="primary" onClick={()=>post({action:"draft-create",business,weekStart}).then(r=>setNotice(`Payroll draft version ${r.version} created.`))} disabled={busy}>Create payroll draft</button></div><p className="eyebrow">Calculated summary</p><h2>{data?.summary.source}</h2><div className="tableWrap"><table className="controlTable"><thead><tr><th>Employee</th><th>Total</th><th>Regular</th><th>OT</th><th>Driver tipped</th><th>Pickup tips</th><th>Delivery tips</th><th>Manual</th><th>Total tips</th></tr></thead><tbody>{data?.summary.rows.map(r=><tr key={r.employee}><td><strong>{r.employee}</strong></td><td>{hours(r.hours)}</td><td>{hours(r.regularHours)}</td><td>{hours(r.overtimeHours)}</td><td>{hours(r.driverTipHours)}</td><td>{dollars(r.pickupTips)}</td><td>{dollars(r.deliveryTips)}</td><td>{dollars(r.manualTips||0)}</td><td><strong>{dollars(r.tips)}</strong></td></tr>)}</tbody></table></div></section>
 <section className="controlCard"><p className="eyebrow">Time audit</p><h2>Punches for this payroll week</h2><div className="tableWrap"><table className="controlTable"><thead><tr><th>Employee</th><th>Clock in</th><th>Clock out</th><th>Source</th><th>Status</th><th></th></tr></thead><tbody>{data?.punches.map(p=><tr key={p.id}><td><strong>{p.employeeName}</strong><small>{p.position}</small></td><td>{new Date(p.clockIn).toLocaleString()}</td><td>{p.clockOut?new Date(p.clockOut).toLocaleString():"Open"}</td><td>{p.source}</td><td><span className={`badge ${p.status==="Complete"?"good":"warn"}`}>{p.status}</span></td><td><button onClick={()=>setEditing(p)}>Correct</button></td></tr>)}</tbody></table></div></section>
 {editing&&<section className="controlCard modalish"><p className="eyebrow">Punch correction</p><h2>{editing.employeeName}</h2><form className="controlForm" onSubmit={correct}><label>Employee<input name="employeeName" defaultValue={editing.employeeName}/></label><label>Position<input name="position" defaultValue={editing.position}/></label><label>Clock in<input name="clockIn" type="datetime-local" defaultValue={editing.clockIn.slice(0,16)}/></label><label>Clock out<input name="clockOut" type="datetime-local" defaultValue={editing.clockOut?.slice(0,16)||""}/></label><label className="wide">Reason<textarea name="reason" required/></label><div className="controlActions wide"><button className="primary" disabled={busy}>Save correction</button><button type="button" onClick={()=>setEditing(null)}>Cancel</button></div></form></section>}
 <section className="controlCard half"><p className="eyebrow">Exceptions</p><h2>Unmatched tips</h2><div className="list">{data?.summary.unmatchedTips.map((t:any)=><div className="listItem" key={t.id}><div><strong>{dollars(t.tip)} · {t.source}</strong><span>{t.orderId||t.transactionId} · {new Date(t.time).toLocaleString()}</span></div><button onClick={()=>{const f=document.querySelector<HTMLFormElement>("#tipOverrideForm");if(f){(f.elements.namedItem("sourceTransactionId") as HTMLInputElement).value=String(t.transactionId||"");(f.elements.namedItem("amount") as HTMLInputElement).value=String(t.tip)}}}>Assign</button></div>)}{!data?.summary.unmatchedTips.length&&<div className="emptyState">No unmatched tips for this week.</div>}</div></section>
 <section className="controlCard half"><p className="eyebrow">Manual allocation</p><h2>Add tip override</h2><form id="tipOverrideForm" className="controlForm" onSubmit={tipOverride}><label>Source transaction<input name="sourceTransactionId"/></label><label>Employee<select name="employeeName" required><option value="">Choose employee</option>{data?.summary.rows.map(r=><option key={r.employee}>{r.employee}</option>)}</select></label><label>Amount<input name="amount" type="number" step="0.01" required/></label><label>Reason<input name="reason" required/></label><button className="primary" disabled={busy}>Apply override</button></form><div className="list">{data?.summary.overrides.map((o:any)=><div className="listItem" key={o.id}><div><strong>{o.employeeName} · {dollars(o.amount)}</strong><span>{o.reason}</span></div><button onClick={()=>post({action:"tip-override-delete",business,id:o.id})}>Remove</button></div>)}</div></section>
 <section className="controlCard"><p className="eyebrow">Append-only payroll history</p><h2>Versions</h2><div className="tableWrap"><table className="controlTable"><thead><tr><th>Week</th><th>Version</th><th>Status</th><th>Generated</th><th>Locked</th><th>Actions</th></tr></thead><tbody>{data?.versions.map(v=><tr key={v.id}><td>{v.weekStart}</td><td>v{v.version}</td><td><span className={`badge ${v.status==="Locked"?"good":"warn"}`}>{v.status}</span></td><td>{v.generatedBy}<small>{new Date(v.generatedAt).toLocaleString()}</small></td><td>{v.lockedBy||"—"}</td><td><a href={`/api/payroll-control?export=${v.id}`}>CSV</a> {v.status==="Draft"?<button onClick={()=>post({action:"run-lock",business,id:v.id})}>Lock</button>:<button onClick={()=>post({action:"run-reopen",business,id:v.id})}>Reopen as new version</button>}</td></tr>)}</tbody></table></div></section>
 <section className="controlCard half"><p className="eyebrow">Punch changes</p><h2>Correction audit</h2><div className="list">{data?.adjustments.slice(0,15).map((a:any)=><div className="listItem" key={a.id}><div><strong>{a.sourceType} punch corrected</strong><span>{a.reason} · {a.actor}</span></div><small>{new Date(a.createdAt).toLocaleString()}</small></div>)}</div></section><section className="controlCard half"><p className="eyebrow">Payroll actions</p><h2>Audit events</h2><div className="list">{data?.auditEvents.slice(0,15).map((a:any)=><div className="listItem" key={a.id}><div><strong>{a.eventType}</strong><span>{a.actor}</span></div><small>{new Date(a.createdAt).toLocaleString()}</small></div>)}</div></section>
 </div></main>
}
