"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import type { Business, SessionView } from "@/lib/types";

type Tab = "overview" | "time" | "payroll" | "accounting";
type Employee = { id:string; business:Business; name:string; position:string; roleGroup:"Driver"|"In-House"|"Ignore"; countsForTips:boolean; hourlyRate:number; tippedRate:number; active:boolean };
type TimeEntry = { id:string; employeeName:string; position:string; clockIn:string; clockOut:string|null; source:string; status:string; clockInLocation:{latitude:number|null;longitude:number|null;accuracy:number|null} };
type PayrollRow = { employee:string; hours:number; regularHours:number; overtimeHours:number; driverTipHours:number; tips:number; pickupTips:number; deliveryTips:number };
type PayrollPayload = { source:string; weekStart:string; weekEnd:string; rows:PayrollRow[]; tipDetails:Array<{time:string;orderId:string;orderType:string;originalTip:number;tipAfterFee:number;employee:string;splitCount:number;rule:string}> };
type ImportBatch = { id:string; reportType:string; fileName:string; rowCount:number; importedBy:string; importedAt:string };
type Account = { id:string; code:string; name:string; accountType:"Asset"|"Liability"|"Equity"|"Revenue"|"Expense" };
type AccountingPayload = { summary:{revenue:number;expenses:number;profit:number;assets:number;liabilities:number;equity:number}; accounts:Account[]; recent:Array<{id:string;entryDate:string;description:string;source:string;reference:string;amount:number}> };

async function messageFrom(response: Response) {
  const payload = await response.json().catch(() => null) as { error?: string } | null;
  return payload?.error || `Request failed (${response.status}).`;
}
function money(value:number) { return new Intl.NumberFormat("en-US", { style:"currency", currency:"USD" }).format(value || 0); }
function hours(value:number) { return Number(value || 0).toFixed(2); }
function previousMonday() { const date=new Date(); const since=(date.getDay()+6)%7; date.setDate(date.getDate()-since-7); return date.toISOString().slice(0,10); }

export default function OperationsPage() {
  const [session,setSession]=useState<SessionView|null>(null);
  const [tab,setTab]=useState<Tab>("overview");
  const [payrollBusiness,setPayrollBusiness]=useState<Business>("Corner Deli");
  const [accountingBusiness,setAccountingBusiness]=useState<Business>("Corner Deli");
  const [weekStart,setWeekStart]=useState(previousMonday());
  const [employees,setEmployees]=useState<Employee[]>([]);
  const [entries,setEntries]=useState<TimeEntry[]>([]);
  const [payroll,setPayroll]=useState<PayrollPayload|null>(null);
  const [imports,setImports]=useState<ImportBatch[]>([]);
  const [accounting,setAccounting]=useState<AccountingPayload|null>(null);
  const [busy,setBusy]=useState(false);
  const [notice,setNotice]=useState("");

  useEffect(() => { fetch("/api/auth/session",{cache:"no-store"}).then(r=>r.json()).then(setSession).catch(()=>setSession({authenticated:false,configured:false,missing:["Unable to reach server"]})); },[]);
  async function getJson<T>(path:string):Promise<T>{ const response=await fetch(path,{cache:"no-store"}); if(!response.ok) throw new Error(await messageFrom(response)); return response.json() as Promise<T>; }
  async function loadTime(){ const [a,b]=await Promise.all([getJson<{employees:Employee[]}>("/api/operations?area=employees&business=Tiki"),getJson<{entries:TimeEntry[]}>("/api/operations?area=time&business=Tiki")]); setEmployees(a.employees); setEntries(b.entries); }
  async function loadPayroll(){ const [a,b]=await Promise.all([getJson<PayrollPayload>(`/api/operations?area=payroll&business=${encodeURIComponent(payrollBusiness)}&weekStart=${weekStart}`),getJson<{imports:ImportBatch[]}>("/api/operations?area=imports&business=Corner%20Deli")]); setPayroll(a); setImports(b.imports); }
  async function loadAccounting(){ setAccounting(await getJson<AccountingPayload>(`/api/operations?area=accounting&business=${encodeURIComponent(accountingBusiness)}`)); }
  useEffect(()=>{ if(session?.authenticated) void Promise.all([loadTime(),loadPayroll(),loadAccounting()]).catch(e=>setNotice(e instanceof Error?e.message:String(e))); /* eslint-disable-next-line react-hooks/exhaustive-deps */ },[session?.authenticated]);
  useEffect(()=>{ if(session?.authenticated) void loadPayroll().catch(e=>setNotice(String(e))); /* eslint-disable-next-line react-hooks/exhaustive-deps */ },[payrollBusiness,weekStart]);
  useEffect(()=>{ if(session?.authenticated) void loadAccounting().catch(e=>setNotice(String(e))); /* eslint-disable-next-line react-hooks/exhaustive-deps */ },[accountingBusiness]);
  async function postJson(body:Record<string,unknown>){ const response=await fetch("/api/operations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}); if(!response.ok) throw new Error(await messageFrom(response)); return response.json(); }

  async function createEmployee(event:FormEvent<HTMLFormElement>){ event.preventDefault(); setBusy(true); setNotice(""); const form=new FormData(event.currentTarget); try{ await postJson({action:"employee-create",business:"Tiki",name:form.get("name"),pin:form.get("pin"),position:form.get("position"),roleGroup:form.get("roleGroup"),countsForTips:form.get("countsForTips")==="on",hourlyRate:form.get("hourlyRate"),tippedRate:form.get("tippedRate")}); event.currentTarget.reset(); await loadTime(); setNotice("Tiki employee created. Their five-digit PIN is ready."); }catch(e){setNotice(e instanceof Error?e.message:"Employee could not be created.");}finally{setBusy(false);} }
  async function toggleEmployee(employee:Employee){ setBusy(true); try{await postJson({action:"employee-update",id:employee.id,active:!employee.active}); await loadTime(); setNotice(`${employee.name} is now ${employee.active?"inactive":"active"}.`);}catch(e){setNotice(e instanceof Error?e.message:"Employee could not be updated.");}finally{setBusy(false);} }
  async function importRezku(event:FormEvent<HTMLFormElement>){ event.preventDefault(); setBusy(true); setNotice(""); const form=new FormData(event.currentTarget); form.set("action","rezku-import"); try{const response=await fetch("/api/operations",{method:"POST",body:form}); if(!response.ok) throw new Error(await messageFrom(response)); const result=await response.json() as {reportType:string;rowsRead:number;imported:number}; event.currentTarget.reset(); await loadPayroll(); setNotice(`Rezku ${result.reportType} processed: ${result.imported} new rows from ${result.rowsRead} read.`);}catch(e){setNotice(e instanceof Error?e.message:"Rezku report could not be imported.");}finally{setBusy(false);} }
  async function createJournal(event:FormEvent<HTMLFormElement>){ event.preventDefault(); setBusy(true); setNotice(""); const form=new FormData(event.currentTarget); try{await postJson({action:"journal-create",business:accountingBusiness,entryDate:form.get("entryDate"),description:form.get("description"),reference:form.get("reference"),kind:form.get("kind"),accountCode:form.get("accountCode"),amount:form.get("amount")}); event.currentTarget.reset(); await loadAccounting(); setNotice("Accounting entry posted.");}catch(e){setNotice(e instanceof Error?e.message:"Accounting entry could not be posted.");}finally{setBusy(false);} }
  async function logout(){await fetch("/api/auth/session",{method:"DELETE"}); window.location.href="/";}

  const openPunches=entries.filter(e=>!e.clockOut);
  const payrollTotals=useMemo(()=>payroll?.rows.reduce((t,r)=>({hours:t.hours+Number(r.hours||0),overtime:t.overtime+Number(r.overtimeHours||0),tips:t.tips+Number(r.tips||0)}),{hours:0,overtime:0,tips:0})||{hours:0,overtime:0,tips:0},[payroll]);
  if(!session) return <main className="centered"><div className="loginCard"><h1>Loading Corner Ops</h1></div></main>;
  if(!session.authenticated) return <main className="centered"><section className="loginCard"><p className="eyebrow">Owner access required</p><h1>Sign in first</h1><p className="muted">The operating system uses the same owner password as the document vault.</p><a className="primary" href="/">Return to sign-in</a></section></main>;
  const accountingAccounts=accounting?.accounts.filter(a=>a.accountType==="Revenue"||a.accountType==="Expense")||[];

  return <main className="shell">
    <aside className="sidebar"><div><p className="eyebrow">Internal operations</p><h1>Corner Ops</h1></div><nav>
      <button className={`navItem ${tab==="overview"?"active":""}`} onClick={()=>setTab("overview")}>Overview</button>
      <button className={`navItem ${tab==="time"?"active":""}`} onClick={()=>setTab("time")}>Tiki time clock</button>
      <button className={`navItem ${tab==="payroll"?"active":""}`} onClick={()=>setTab("payroll")}>Payroll & tips</button>
      <button className={`navItem ${tab==="accounting"?"active":""}`} onClick={()=>setTab("accounting")}>Accounting</button>
      <a className="navItem" href="/">Documents</a><a className="navItem" href="/clock">Employee clock</a>
    </nav><div className="sidebarFooter"><p>{session.email}</p><button className="textButton neutral" onClick={logout}>Sign out</button></div></aside>
    <section className="content"><header className="topbar"><div><p className="eyebrow">Business operating system</p><h2>{tab==="overview"?"Command center":tab==="time"?"Tiki people and time":tab==="payroll"?"Payroll and tip processing":"Accounting ledger"}</h2></div><a className="secondary" href="/clock">Tiki clock link</a></header>
    {notice&&<div className="notice opsNotice">{notice}</div>}

    {tab==="overview"&&<><section className="stats fourStats"><article><span>Active Tiki employees</span><strong>{employees.filter(e=>e.active).length}</strong></article><article><span>Open Tiki punches</span><strong>{openPunches.length}</strong></article><article><span>Deli Rezku imports</span><strong>{imports.length}</strong></article><article><span>Current profit</span><strong>{money(accounting?.summary.profit||0)}</strong></article></section><section className="opsGrid">
      <article className="panel moduleCard"><p className="eyebrow">Tiki</p><h3>PIN time clock</h3><p>Five-digit employee PINs, GPS capture, rates, roles, and weekly hours.</p><button className="secondary" onClick={()=>setTab("time")}>Manage time</button></article>
      <article className="panel moduleCard"><p className="eyebrow">Corner Deli</p><h3>Rezku payroll engine</h3><p>Detailed Labor, Orders, and Transactions feed the existing tip rules.</p><button className="secondary" onClick={()=>setTab("payroll")}>Open payroll</button></article>
      <article className="panel moduleCard"><p className="eyebrow">Both businesses</p><h3>Accounting ledger</h3><p>Separate double-entry books, income totals, and balance-sheet balances.</p><button className="secondary" onClick={()=>setTab("accounting")}>Open accounting</button></article>
      <article className="panel moduleCard"><p className="eyebrow">Documents</p><h3>Private records</h3><p>The document vault remains available alongside actual operations.</p><a className="secondary" href="/">Open documents</a></article>
    </section></>}

    {tab==="time"&&<><section className="stats"><article><span>Active employees</span><strong>{employees.filter(e=>e.active).length}</strong></article><article><span>Currently clocked in</span><strong>{openPunches.length}</strong></article><article><span>Recent punch records</span><strong>{entries.length}</strong></article></section>
      <section className="panel"><div className="panelHeader"><div><p className="eyebrow">Tiki only</p><h3>Add employee</h3></div><a className="secondary" href="/clock">Open kiosk clock</a></div><form className="uploadForm opsForm" onSubmit={createEmployee}>
        <label>Name<input name="name" required maxLength={120}/></label><label>Five-digit PIN<input name="pin" inputMode="numeric" pattern="\d{5}" maxLength={5} required/></label><label>Position<input name="position" defaultValue="Bartender" required/></label><label>Role group<select name="roleGroup"><option>In-House</option><option>Driver</option><option>Ignore</option></select></label><label>Regular hourly rate<input name="hourlyRate" type="number" min="0" step="0.01" defaultValue="0"/></label><label>Tipped hourly rate<input name="tippedRate" type="number" min="0" step="0.01" defaultValue="0"/></label><label className="checkboxLabel"><input name="countsForTips" type="checkbox" defaultChecked/> Include in tip pools</label><button className="primary" disabled={busy}>Create employee</button>
      </form><div className="dataTableWrap"><table className="dataTable"><thead><tr><th>Employee</th><th>Position</th><th>Role</th><th>Rates</th><th>Status</th><th></th></tr></thead><tbody>{employees.map(e=><tr key={e.id}><td><strong>{e.name}</strong></td><td>{e.position}</td><td>{e.roleGroup}{e.countsForTips?" · tips":""}</td><td>{money(e.hourlyRate)} / {money(e.tippedRate)} tipped</td><td><span className={`badge ${e.active?"active":"archived"}`}>{e.active?"Active":"Inactive"}</span></td><td><button className="textButton neutral" disabled={busy} onClick={()=>toggleEmployee(e)}>{e.active?"Deactivate":"Reactivate"}</button></td></tr>)}</tbody></table></div></section>
      <section className="panel activityPanel"><div className="panelHeader"><div><p className="eyebrow">Punch review</p><h3>Recent Tiki time entries</h3></div></div><div className="dataTableWrap"><table className="dataTable"><thead><tr><th>Employee</th><th>Clock in</th><th>Clock out</th><th>Hours</th><th>Location</th><th>Status</th></tr></thead><tbody>{entries.map(e=>{const start=new Date(e.clockIn),end=e.clockOut?new Date(e.clockOut):null,total=end?(end.getTime()-start.getTime())/3600000:0;return <tr key={e.id}><td><strong>{e.employeeName}</strong><small>{e.position}</small></td><td>{start.toLocaleString()}</td><td>{end?end.toLocaleString():"Still clocked in"}</td><td>{end?hours(total):"Open"}</td><td>{e.clockInLocation.latitude===null?"Missing":`${Number(e.clockInLocation.accuracy||0).toFixed(0)} accuracy`}</td><td><span className={`badge ${e.status==="Complete"?"active":"needsreview"}`}>{e.status}</span></td></tr>})}</tbody></table></div></section></>}

    {tab==="payroll"&&<><section className="toolbarPanel"><div className="businessSwitch">{(["Corner Deli","Tiki"] as Business[]).map(name=><button key={name} className={payrollBusiness===name?"selected":""} onClick={()=>setPayrollBusiness(name)}>{name}</button>)}</div><label>Payroll week starting<input type="date" value={weekStart} onChange={(event:{target:{value:string}})=>setWeekStart(event.target.value)}/></label><button className="secondary" onClick={()=>void loadPayroll()}>Recalculate</button></section>
      <section className="stats"><article><span>Total hours</span><strong>{hours(payrollTotals.hours)}</strong></article><article><span>Overtime hours</span><strong>{hours(payrollTotals.overtime)}</strong></article><article><span>Tips after 3.5% fee</span><strong>{money(payrollTotals.tips)}</strong></article></section>
      {payrollBusiness==="Corner Deli"&&<section className="panel"><div className="panelHeader"><div><p className="eyebrow">Rezku source</p><h3>Import daily report</h3></div><span className="badge active">Email bridge next</span></div><form className="uploadForm opsForm" onSubmit={importRezku}><label>Report type<select name="reportType"><option value="">Detect from filename</option><option value="shifts">Detailed Labor / Shifts</option><option value="orders">Order Export</option><option value="transactions">Transaction Export</option></select></label><label>Excel report<input name="file" type="file" accept=".xlsx,.xls" required/></label><button className="primary" disabled={busy}>Import Rezku report</button></form><div className="ruleStrip"><span>3.5% deduction</span><span>Before 3 PM shared</span><span>Delivery to drivers</span><span>35-minute grace</span><span>Last-out fallback</span></div></section>}
      <section className="panel activityPanel"><div className="panelHeader"><div><p className="eyebrow">{payroll?.source||"Payroll source"}</p><h3>Employee payroll summary</h3></div></div><div className="dataTableWrap"><table className="dataTable"><thead><tr><th>Employee</th><th>Total hours</th><th>Regular</th><th>OT</th><th>Driver tipped hours</th><th>Pickup tips</th><th>Delivery tips</th><th>Total tips</th></tr></thead><tbody>{(payroll?.rows||[]).map(r=><tr key={r.employee}><td><strong>{r.employee}</strong></td><td>{hours(r.hours)}</td><td>{hours(r.regularHours)}</td><td>{hours(r.overtimeHours)}</td><td>{hours(r.driverTipHours)}</td><td>{money(r.pickupTips)}</td><td>{money(r.deliveryTips)}</td><td><strong>{money(r.tips)}</strong></td></tr>)}{payroll?.rows.length===0&&<tr><td colSpan={8}>No payroll records were found for this week.</td></tr>}</tbody></table></div></section>
      {payrollBusiness==="Corner Deli"&&<section className="opsGrid twoCols"><article className="panel"><div className="panelHeader"><div><p className="eyebrow">Import history</p><h3>Recent Rezku reports</h3></div></div><div className="compactList">{imports.slice(0,12).map(b=><div key={b.id}><strong>{b.fileName}</strong><span>{b.reportType} · {b.rowCount} rows · {new Date(b.importedAt).toLocaleString()}</span></div>)}{imports.length===0&&<div className="empty">No Rezku reports imported yet.</div>}</div></article><article className="panel"><div className="panelHeader"><div><p className="eyebrow">Audit detail</p><h3>Recent tip allocations</h3></div></div><div className="compactList">{(payroll?.tipDetails||[]).slice(0,20).map((d,i)=><div key={`${d.orderId}-${d.employee}-${i}`}><strong>{d.employee}: {money(d.tipAfterFee/d.splitCount)}</strong><span>{d.orderType||"Unknown order"} · {d.orderId} · {d.rule}</span></div>)}{payroll?.tipDetails.length===0&&<div className="empty">No tip allocations found.</div>}</div></article></section>}</>}

    {tab==="accounting"&&<><section className="toolbarPanel"><div className="businessSwitch">{(["Corner Deli","Tiki"] as Business[]).map(name=><button key={name} className={accountingBusiness===name?"selected":""} onClick={()=>setAccountingBusiness(name)}>{name}</button>)}</div></section><section className="stats fourStats"><article><span>Revenue</span><strong>{money(accounting?.summary.revenue||0)}</strong></article><article><span>Expenses</span><strong>{money(accounting?.summary.expenses||0)}</strong></article><article><span>Net profit</span><strong>{money(accounting?.summary.profit||0)}</strong></article><article><span>Cash / assets</span><strong>{money(accounting?.summary.assets||0)}</strong></article></section>
      <section className="opsGrid twoCols"><article className="panel"><div className="panelHeader"><div><p className="eyebrow">Double entry</p><h3>Post transaction</h3></div></div><form className="stackForm" onSubmit={createJournal}><label>Date<input name="entryDate" type="date" defaultValue={new Date().toISOString().slice(0,10)} required/></label><label>Type<select name="kind"><option>Revenue</option><option>Expense</option></select></label><label>Category<select name="accountCode" required>{accountingAccounts.map(a=><option key={a.id} value={a.code}>{a.code} · {a.name} ({a.accountType})</option>)}</select></label><label>Amount<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>Description<input name="description" required/></label><label>Reference<input name="reference" placeholder="Receipt, deposit, invoice, etc."/></label><button className="primary" disabled={busy}>Post entry</button></form></article><article className="panel"><div className="panelHeader"><div><p className="eyebrow">Balance sheet</p><h3>Current balances</h3></div></div><div className="accountingSummary"><div><span>Assets</span><strong>{money(accounting?.summary.assets||0)}</strong></div><div><span>Liabilities</span><strong>{money(accounting?.summary.liabilities||0)}</strong></div><div><span>Equity</span><strong>{money(accounting?.summary.equity||0)}</strong></div><div><span>Current earnings</span><strong>{money(accounting?.summary.profit||0)}</strong></div></div></article></section>
      <section className="panel activityPanel"><div className="panelHeader"><div><p className="eyebrow">General ledger</p><h3>Recent journal entries</h3></div></div><div className="dataTableWrap"><table className="dataTable"><thead><tr><th>Date</th><th>Description</th><th>Reference</th><th>Source</th><th>Amount</th></tr></thead><tbody>{(accounting?.recent||[]).map(e=><tr key={e.id}><td>{e.entryDate}</td><td><strong>{e.description}</strong></td><td>{e.reference||"—"}</td><td>{e.source}</td><td>{money(e.amount)}</td></tr>)}{accounting?.recent.length===0&&<tr><td colSpan={5}>No journal entries have been posted.</td></tr>}</tbody></table></div></section></>}
    </section>
  </main>;
}
