import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { getSession } from "@/lib/auth";
import { getSql } from "@/lib/db";
import { ensureOrderingMenuOverrideSchema } from "@/lib/ordering-menu-overrides";

const roles = new Set(["Owner", "Co-Owner", "Manager"]);
async function manager() {
  const session = await getSession();
  return session && roles.has(session.role) && session.businesses.includes("Corner Deli") ? session : null;
}

export async function GET(request:Request) {
  const session = await manager();
  if (!session) return NextResponse.json({ error: "Manager access required." }, { status: 403 });
  await ensureOrderingMenuOverrideSchema();
  const sql = getSql();
  const channel=new URL(request.url).searchParams.get("channel")==="web"?"web":"pos";
  const [categories, items, modifiers, variants, modifierOptions, availability] = await Promise.all([
    sql`SELECT c.id,c.name imported_name,COALESCE(ch.display_name,o.display_name,c.display_name,c.name) effective_name,c.parent_id imported_parent_id,c.sort_order imported_sort_order,ch.display_name,ch.parent_id,ch.parent_id_overridden,ch.sort_order,ch.visible FROM ordering_menu_categories c LEFT JOIN ordering_category_overrides o ON o.category_id=c.id LEFT JOIN ordering_category_channel_overrides ch ON ch.category_id=c.id AND ch.channel=${channel} WHERE c.business='Corner Deli' ORDER BY COALESCE(ch.sort_order,o.sort_order,c.sort_order),c.name`,
    sql`SELECT i.id,i.name imported_name,COALESCE(ch.display_name,o.display_name,i.name) effective_name,i.description imported_description,COALESCE(ch.description,o.description,i.description) effective_description,o.print_name effective_print_name,i.category_id imported_category_id,i.sort_order imported_sort_order,ch.display_name,ch.description,ch.category_id,ch.sort_order,ch.visible,media.id media_id,media.alt_text FROM ordering_menu_items i LEFT JOIN ordering_item_overrides o ON o.item_id=i.id LEFT JOIN ordering_item_channel_overrides ch ON ch.item_id=i.id AND ch.channel=${channel} LEFT JOIN LATERAL(SELECT * FROM ordering_menu_media m WHERE m.target_type='item' AND m.target_id=i.id ORDER BY uploaded_at DESC LIMIT 1)media ON TRUE WHERE i.business='Corner Deli' ORDER BY COALESCE(ch.sort_order,o.sort_order,i.sort_order),i.name`,
    sql`SELECT link.item_id,i.name item_name,g.id group_id,g.name group_name,g.min_selections,g.max_selections,p.context,p.parent_group_id,p.parent_option_ids,p.sort_order,p.print_order,p.header_modifier,p.suppress_default_on_ticket,p.presentation_style,p.component_key,p.component_label,p.component_order,p.dependency_scope FROM ordering_menu_item_modifier_groups link JOIN ordering_menu_items i ON i.id=link.item_id JOIN ordering_modifier_groups g ON g.id=link.group_id LEFT JOIN ordering_modifier_presentation_overrides p ON p.item_id=link.item_id AND p.group_id=link.group_id WHERE i.business='Corner Deli' ORDER BY i.name,COALESCE(p.component_order,p.sort_order,link.sort_order),g.name`,
    sql`SELECT variant.id,variant.item_id,variant.name imported_name,COALESCE(NULLIF(print.print_name,''),variant.name) effective_print_name,print.print_name FROM ordering_menu_item_variants variant JOIN ordering_menu_items item ON item.id=variant.item_id LEFT JOIN ordering_item_variant_print_overrides print ON print.variant_id=variant.id WHERE item.business='Corner Deli' AND variant.active=TRUE ORDER BY item.name,variant.sort_order,variant.name`,
    sql`SELECT link.item_id,option.group_id,option.id,option.name imported_name,COALESCE(NULLIF(print.print_name,''),option.name) effective_print_name,print.print_name,COALESCE(print.print_order,presentation.print_order,option.sort_order) print_order,print.print_section,print.suppress_when_default,print.print_only_when_changed,COALESCE(defaults.default_selected,FALSE) default_selected FROM ordering_menu_item_modifier_groups link JOIN ordering_menu_items item ON item.id=link.item_id JOIN ordering_modifier_options option ON option.group_id=link.group_id AND option.active=TRUE LEFT JOIN ordering_modifier_option_print_overrides print ON print.option_id=option.id LEFT JOIN ordering_modifier_presentation_overrides presentation ON presentation.item_id=link.item_id AND presentation.group_id=link.group_id LEFT JOIN ordering_menu_item_modifier_defaults defaults ON defaults.item_id=link.item_id AND defaults.option_id=option.id AND defaults.active=TRUE WHERE item.business='Corner Deli' ORDER BY item.name,COALESCE(print.print_order,presentation.print_order,option.sort_order),option.name`,
    sql`SELECT target_type,target_id::text,enabled,days_of_week,starts_at::text,ends_at::text,valid_from,valid_through FROM ordering_menu_availability_rules WHERE business='Corner Deli'`,
  ]);
  return NextResponse.json({ channel,categories,items,modifiers,variants,modifierOptions,availability });
}

export async function PATCH(request: Request) {
  const session = await manager();
  if (!session) return NextResponse.json({ error: "Manager access required." }, { status: 403 });
  await ensureOrderingMenuOverrideSchema();
  const body = await request.json() as { targetType?: string; targetId?: string; itemId?: string; field?: string; value?: unknown; reset?: boolean;channel?:string };
  const targetType = String(body.targetType || ""); const targetId = String(body.targetId || ""); const field = String(body.field || "");
  const sql = getSql();
  let previous: unknown = null;
  try {
    const channel=body.channel==="web"?"web":body.channel==="pos"?"pos":null;
    if(channel && targetType==="category"){
      const row=(await sql`SELECT * FROM ordering_category_channel_overrides WHERE category_id=${targetId} AND channel=${channel}`)[0]||{};previous=row[field];
      if(field==="display_name")await sql`INSERT INTO ordering_category_channel_overrides(category_id,channel,display_name,updated_by)VALUES(${targetId},${channel},${body.reset?null:String(body.value||"").trim()},${session.email})ON CONFLICT(category_id,channel)DO UPDATE SET display_name=EXCLUDED.display_name,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
      else if(field==="sort_order")await sql`INSERT INTO ordering_category_channel_overrides(category_id,channel,sort_order,updated_by)VALUES(${targetId},${channel},${body.reset?null:Number(body.value)},${session.email})ON CONFLICT(category_id,channel)DO UPDATE SET sort_order=EXCLUDED.sort_order,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
      else if(field==="visible")await sql`INSERT INTO ordering_category_channel_overrides(category_id,channel,visible,updated_by)VALUES(${targetId},${channel},${body.reset?null:Boolean(body.value)},${session.email})ON CONFLICT(category_id,channel)DO UPDATE SET visible=EXCLUDED.visible,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
      else if(field==="parent_id")await sql`INSERT INTO ordering_category_channel_overrides(category_id,channel,parent_id,parent_id_overridden,updated_by)VALUES(${targetId},${channel},${body.reset?null:String(body.value||"")||null},${!body.reset},${session.email})ON CONFLICT(category_id,channel)DO UPDATE SET parent_id=EXCLUDED.parent_id,parent_id_overridden=EXCLUDED.parent_id_overridden,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
      else throw new Error("Unsupported category field.");
    }else if(channel && targetType==="item"){
      const row=(await sql`SELECT * FROM ordering_item_channel_overrides WHERE item_id=${targetId} AND channel=${channel}`)[0]||{};previous=row[field];
      if(field==="display_name")await sql`INSERT INTO ordering_item_channel_overrides(item_id,channel,display_name,updated_by)VALUES(${targetId},${channel},${body.reset?null:String(body.value||"").trim()},${session.email})ON CONFLICT(item_id,channel)DO UPDATE SET display_name=EXCLUDED.display_name,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
      else if(field==="description")await sql`INSERT INTO ordering_item_channel_overrides(item_id,channel,description,updated_by)VALUES(${targetId},${channel},${body.reset?null:String(body.value||"").trim()},${session.email})ON CONFLICT(item_id,channel)DO UPDATE SET description=EXCLUDED.description,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
      else if(field==="print_name")await sql`INSERT INTO ordering_item_overrides(item_id,print_name,updated_by)VALUES(${targetId},${body.reset?null:String(body.value||"").trim()},${session.email})ON CONFLICT(item_id)DO UPDATE SET print_name=EXCLUDED.print_name,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
      else if(field==="sort_order")await sql`INSERT INTO ordering_item_channel_overrides(item_id,channel,sort_order,updated_by)VALUES(${targetId},${channel},${body.reset?null:Number(body.value)},${session.email})ON CONFLICT(item_id,channel)DO UPDATE SET sort_order=EXCLUDED.sort_order,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
      else if(field==="visible")await sql`INSERT INTO ordering_item_channel_overrides(item_id,channel,visible,updated_by)VALUES(${targetId},${channel},${body.reset?null:Boolean(body.value)},${session.email})ON CONFLICT(item_id,channel)DO UPDATE SET visible=EXCLUDED.visible,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
      else if(field==="category_id")await sql`INSERT INTO ordering_item_channel_overrides(item_id,channel,category_id,updated_by)VALUES(${targetId},${channel},${body.reset?null:String(body.value||"")||null},${session.email})ON CONFLICT(item_id,channel)DO UPDATE SET category_id=EXCLUDED.category_id,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
      else throw new Error("Unsupported item field.");
    }else
    if (targetType === "category") {
      const owned = await sql`SELECT id FROM ordering_menu_categories WHERE id=${targetId} AND business='Corner Deli'`; if (!owned.length) throw new Error("Category not found.");
      const row = (await sql`SELECT * FROM ordering_category_overrides WHERE category_id=${targetId}`)[0] || {}; previous = row[field];
      if (field === "display_name") await sql`INSERT INTO ordering_category_overrides(category_id,display_name,updated_by) VALUES(${targetId},${body.reset ? null : String(body.value || "").trim()},${session.email}) ON CONFLICT(category_id) DO UPDATE SET display_name=EXCLUDED.display_name,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
      else if (field === "parent_id") {
        const parentId = body.reset ? null : String(body.value || "") || null;
        if (parentId) { const validParent = await sql`SELECT id FROM ordering_menu_categories WHERE id=${parentId} AND business='Corner Deli' AND id<>${targetId}`; if (!validParent.length) throw new Error("Parent category not found."); }
        await sql`INSERT INTO ordering_category_overrides(category_id,parent_id,parent_id_overridden,updated_by) VALUES(${targetId},${parentId},${!body.reset},${session.email}) ON CONFLICT(category_id) DO UPDATE SET parent_id=EXCLUDED.parent_id,parent_id_overridden=EXCLUDED.parent_id_overridden,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
      }
      else if (field === "sort_order") await sql`INSERT INTO ordering_category_overrides(category_id,sort_order,updated_by) VALUES(${targetId},${body.reset ? null : Number(body.value)},${session.email}) ON CONFLICT(category_id) DO UPDATE SET sort_order=EXCLUDED.sort_order,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
      else if (field === "visible") await sql`INSERT INTO ordering_category_overrides(category_id,visible,updated_by) VALUES(${targetId},${body.reset ? null : Boolean(body.value)},${session.email}) ON CONFLICT(category_id) DO UPDATE SET visible=EXCLUDED.visible,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
      else throw new Error("Unsupported category field.");
    } else if (targetType === "item") {
      const owned = await sql`SELECT id FROM ordering_menu_items WHERE id=${targetId} AND business='Corner Deli'`; if (!owned.length) throw new Error("Item not found.");
      const row = (await sql`SELECT * FROM ordering_item_overrides WHERE item_id=${targetId}`)[0] || {}; previous = row[field];
      if (field === "display_name") await sql`INSERT INTO ordering_item_overrides(item_id,display_name,updated_by) VALUES(${targetId},${body.reset ? null : String(body.value || "").trim()},${session.email}) ON CONFLICT(item_id) DO UPDATE SET display_name=EXCLUDED.display_name,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
      else if (field === "description") await sql`INSERT INTO ordering_item_overrides(item_id,description,updated_by) VALUES(${targetId},${body.reset ? null : String(body.value || "").trim()},${session.email}) ON CONFLICT(item_id) DO UPDATE SET description=EXCLUDED.description,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
      else if (field === "print_name") await sql`INSERT INTO ordering_item_overrides(item_id,print_name,updated_by) VALUES(${targetId},${body.reset ? null : String(body.value || "").trim()},${session.email}) ON CONFLICT(item_id) DO UPDATE SET print_name=EXCLUDED.print_name,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
      else if (field === "category_id") {
        const categoryId = body.reset ? null : String(body.value || "") || null;
        if (categoryId) { const validCategory = await sql`SELECT id FROM ordering_menu_categories WHERE id=${categoryId} AND business='Corner Deli'`; if (!validCategory.length) throw new Error("Category not found."); }
        await sql`INSERT INTO ordering_item_overrides(item_id,category_id,updated_by) VALUES(${targetId},${categoryId},${session.email}) ON CONFLICT(item_id) DO UPDATE SET category_id=EXCLUDED.category_id,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
      }
      else if (field === "sort_order") await sql`INSERT INTO ordering_item_overrides(item_id,sort_order,updated_by) VALUES(${targetId},${body.reset ? null : Number(body.value)},${session.email}) ON CONFLICT(item_id) DO UPDATE SET sort_order=EXCLUDED.sort_order,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
      else if (field === "visible") await sql`INSERT INTO ordering_item_overrides(item_id,visible,updated_by) VALUES(${targetId},${body.reset ? null : Boolean(body.value)},${session.email}) ON CONFLICT(item_id) DO UPDATE SET visible=EXCLUDED.visible,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
      else throw new Error("Unsupported item field.");
    } else if (targetType === "modifier") {
      const itemId=String(body.itemId||""); const owned=await sql`SELECT 1 FROM ordering_menu_item_modifier_groups l JOIN ordering_menu_items i ON i.id=l.item_id WHERE l.item_id=${itemId} AND l.group_id=${targetId} AND i.business='Corner Deli'`; if(!owned.length) throw new Error("Modifier relationship not found.");
      const row=(await sql`SELECT * FROM ordering_modifier_presentation_overrides WHERE item_id=${itemId} AND group_id=${targetId}`)[0]||{}; previous=row[field];
      if(field==="context") { const value=body.reset?null:String(body.value||""); if(value && !["ordinary","combo_trigger","dependent","hidden"].includes(value)) throw new Error("Invalid context."); await sql`INSERT INTO ordering_modifier_presentation_overrides(item_id,group_id,context,updated_by) VALUES(${itemId},${targetId},${value},${session.email}) ON CONFLICT(item_id,group_id) DO UPDATE SET context=EXCLUDED.context,updated_by=EXCLUDED.updated_by,updated_at=NOW()`; }
      else if(field==="sort_order"||field==="print_order"||field==="component_order") await sql`INSERT INTO ordering_modifier_presentation_overrides(item_id,group_id,sort_order,print_order,component_order,updated_by) VALUES(${itemId},${targetId},${field==="sort_order"?(body.reset?null:Number(body.value)):null},${field==="print_order"?(body.reset?null:Number(body.value)):null},${field==="component_order"?(body.reset?null:Number(body.value)):null},${session.email}) ON CONFLICT(item_id,group_id) DO UPDATE SET sort_order=CASE WHEN ${field}='sort_order' THEN EXCLUDED.sort_order ELSE ordering_modifier_presentation_overrides.sort_order END,print_order=CASE WHEN ${field}='print_order' THEN EXCLUDED.print_order ELSE ordering_modifier_presentation_overrides.print_order END,component_order=CASE WHEN ${field}='component_order' THEN EXCLUDED.component_order ELSE ordering_modifier_presentation_overrides.component_order END,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
      else if(["header_modifier","suppress_default_on_ticket"].includes(field)) await sql`INSERT INTO ordering_modifier_presentation_overrides(item_id,group_id,header_modifier,suppress_default_on_ticket,updated_by) VALUES(${itemId},${targetId},${field==="header_modifier"?Boolean(body.value):false},${field==="suppress_default_on_ticket"?Boolean(body.value):true},${session.email}) ON CONFLICT(item_id,group_id) DO UPDATE SET header_modifier=CASE WHEN ${field}='header_modifier' THEN EXCLUDED.header_modifier ELSE ordering_modifier_presentation_overrides.header_modifier END,suppress_default_on_ticket=CASE WHEN ${field}='suppress_default_on_ticket' THEN EXCLUDED.suppress_default_on_ticket ELSE ordering_modifier_presentation_overrides.suppress_default_on_ticket END,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
      else if(["presentation_style","component_key","component_label","dependency_scope"].includes(field)) {const value=String(body.value||"").trim();await sql`INSERT INTO ordering_modifier_presentation_overrides(item_id,group_id,presentation_style,component_key,component_label,dependency_scope,updated_by) VALUES(${itemId},${targetId},${field==="presentation_style"?value:"grid"},${field==="component_key"?value:""},${field==="component_label"?value:""},${field==="dependency_scope"?value:"item"},${session.email}) ON CONFLICT(item_id,group_id) DO UPDATE SET presentation_style=CASE WHEN ${field}='presentation_style' THEN EXCLUDED.presentation_style ELSE ordering_modifier_presentation_overrides.presentation_style END,component_key=CASE WHEN ${field}='component_key' THEN EXCLUDED.component_key ELSE ordering_modifier_presentation_overrides.component_key END,component_label=CASE WHEN ${field}='component_label' THEN EXCLUDED.component_label ELSE ordering_modifier_presentation_overrides.component_label END,dependency_scope=CASE WHEN ${field}='dependency_scope' THEN EXCLUDED.dependency_scope ELSE ordering_modifier_presentation_overrides.dependency_scope END,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;}
      else if(field==="parent_group_id") await sql`INSERT INTO ordering_modifier_presentation_overrides(item_id,group_id,parent_group_id,updated_by)VALUES(${itemId},${targetId},${body.value?String(body.value):null},${session.email})ON CONFLICT(item_id,group_id)DO UPDATE SET parent_group_id=EXCLUDED.parent_group_id,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
      else if(field==="parent_option_ids") await sql`INSERT INTO ordering_modifier_presentation_overrides(item_id,group_id,parent_option_ids,updated_by)VALUES(${itemId},${targetId},${Array.isArray(body.value)?body.value.map(String):[]},${session.email})ON CONFLICT(item_id,group_id)DO UPDATE SET parent_option_ids=EXCLUDED.parent_option_ids,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
      else throw new Error("Unsupported modifier field.");
    } else if(targetType==="variant") {
      const owned=await sql`SELECT variant.id FROM ordering_menu_item_variants variant JOIN ordering_menu_items item ON item.id=variant.item_id WHERE variant.id=${targetId} AND item.business='Corner Deli'`;if(!owned.length)throw new Error("Variant not found.");
      if(field!=="print_name")throw new Error("Unsupported variant field.");
      await sql`INSERT INTO ordering_item_variant_print_overrides(variant_id,print_name,updated_by)VALUES(${targetId},${body.reset?null:String(body.value||"").trim()},${session.email})ON CONFLICT(variant_id)DO UPDATE SET print_name=EXCLUDED.print_name,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
    } else if(targetType==="modifier_option") {
      const owned=await sql`SELECT option.id FROM ordering_modifier_options option JOIN ordering_modifier_groups g ON g.id=option.group_id JOIN ordering_menu_item_modifier_groups link ON link.group_id=g.id JOIN ordering_menu_items item ON item.id=link.item_id WHERE option.id=${targetId} AND item.business='Corner Deli' LIMIT 1`;if(!owned.length)throw new Error("Modifier option not found.");
      if(field==="print_name")await sql`INSERT INTO ordering_modifier_option_print_overrides(option_id,print_name,updated_by)VALUES(${targetId},${body.reset?null:String(body.value||"").trim()},${session.email})ON CONFLICT(option_id)DO UPDATE SET print_name=EXCLUDED.print_name,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
      else if(field==="print_order")await sql`INSERT INTO ordering_modifier_option_print_overrides(option_id,print_order,updated_by)VALUES(${targetId},${body.reset?null:Number(body.value)},${session.email})ON CONFLICT(option_id)DO UPDATE SET print_order=EXCLUDED.print_order,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
      else if(field==="print_section")await sql`INSERT INTO ordering_modifier_option_print_overrides(option_id,print_section,updated_by)VALUES(${targetId},${String(body.value||"").trim()},${session.email})ON CONFLICT(option_id)DO UPDATE SET print_section=EXCLUDED.print_section,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
      else if(field==="suppress_when_default"||field==="print_only_when_changed")await sql`INSERT INTO ordering_modifier_option_print_overrides(option_id,suppress_when_default,print_only_when_changed,updated_by)VALUES(${targetId},${field==="suppress_when_default"?Boolean(body.value):null},${field==="print_only_when_changed"?Boolean(body.value):null},${session.email})ON CONFLICT(option_id)DO UPDATE SET suppress_when_default=CASE WHEN ${field}='suppress_when_default' THEN EXCLUDED.suppress_when_default ELSE ordering_modifier_option_print_overrides.suppress_when_default END,print_only_when_changed=CASE WHEN ${field}='print_only_when_changed' THEN EXCLUDED.print_only_when_changed ELSE ordering_modifier_option_print_overrides.print_only_when_changed END,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;
      else throw new Error("Unsupported modifier option field.");
    } else throw new Error("Unsupported override target.");
    await sql`INSERT INTO ordering_menu_override_audit(id,business,actor_id,target_type,target_id,field_name,previous_value,new_value) VALUES(${randomUUID()},'Corner Deli',${session.email},${targetType},${targetId},${field},${JSON.stringify(previous ?? null)}::jsonb,${JSON.stringify(body.reset ? null : body.value ?? null)}::jsonb)`;
    return NextResponse.json({ ok: true });
  } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Could not update menu override." }, { status: 400 }); }
}

export async function POST(){const session=await manager();if(!session)return NextResponse.json({error:"Manager access required."},{status:403});await ensureOrderingMenuOverrideSchema();const sql=getSql();await sql`INSERT INTO ordering_category_channel_overrides(category_id,channel,display_name,parent_id,parent_id_overridden,sort_order,visible,updated_by)SELECT c.id,'web',COALESCE(pos.display_name,shared.display_name),CASE WHEN pos.parent_id_overridden THEN pos.parent_id ELSE shared.parent_id END,pos.parent_id_overridden OR shared.parent_id_overridden,COALESCE(pos.sort_order,shared.sort_order,c.sort_order),COALESCE(pos.visible,shared.visible),${session.email} FROM ordering_menu_categories c LEFT JOIN ordering_category_overrides shared ON shared.category_id=c.id LEFT JOIN ordering_category_channel_overrides pos ON pos.category_id=c.id AND pos.channel='pos' WHERE c.business='Corner Deli' ON CONFLICT(category_id,channel)DO UPDATE SET display_name=EXCLUDED.display_name,parent_id=EXCLUDED.parent_id,parent_id_overridden=EXCLUDED.parent_id_overridden,sort_order=EXCLUDED.sort_order,visible=EXCLUDED.visible,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;await sql`INSERT INTO ordering_item_channel_overrides(item_id,channel,display_name,category_id,sort_order,visible,updated_by)SELECT i.id,'web',COALESCE(pos.display_name,shared.display_name),COALESCE(pos.category_id,shared.category_id,i.category_id),COALESCE(pos.sort_order,shared.sort_order,i.sort_order),COALESCE(pos.visible,shared.visible),${session.email} FROM ordering_menu_items i LEFT JOIN ordering_item_overrides shared ON shared.item_id=i.id LEFT JOIN ordering_item_channel_overrides pos ON pos.item_id=i.id AND pos.channel='pos' WHERE i.business='Corner Deli' ON CONFLICT(item_id,channel)DO UPDATE SET display_name=EXCLUDED.display_name,category_id=EXCLUDED.category_id,sort_order=EXCLUDED.sort_order,visible=EXCLUDED.visible,updated_by=EXCLUDED.updated_by,updated_at=NOW()`;await sql`INSERT INTO ordering_menu_override_audit(id,business,actor_id,target_type,target_id,field_name,previous_value,new_value)VALUES(${randomUUID()},'Corner Deli',${session.email},'presentation_copy','00000000-0000-0000-0000-000000000000','pos_to_web','null'::jsonb,'true'::jsonb)`;return NextResponse.json({ok:true})}
