import { randomUUID } from "node:crypto";
import { orderingActor } from "@/lib/ordering-route-auth";
import type { OrderingBusiness } from "@/lib/ordering-core";
import { getSql } from "@/lib/db";
import { addressForOrder, routeDeliveryAddress } from "@/lib/ordering-address";
import { saveOrderDeliveryAddress } from "@/lib/ordering-address-schema";
import { quoteDelivery } from "@/lib/ordering-delivery";
import { ensureOrderingAiSchema } from "@/lib/ordering-ai-schema";
import { dispatchSubmittedOrderPrintJobs } from "@/lib/ordering-auto-print";
import {
  AiToolError, auditAiTool, availabilityBundle, createAiDraft, customerLookup,
  deliveryQuote, futureSlots, holdDraft, itemInputs, menuCatalog, promotions,
  replaceAiDraft, requestedDate, sendDraft, serviceType,
} from "@/lib/ordering-ai-tools";

export const runtime = "nodejs";
export const AI_ORDERING_TOOL_NAMES = ["describe_capabilities","menu_browse","menu_search","ordering_availability","future_slots","promotions","customer_lookup","create_draft","update_draft","get_draft","attach_delivery_address","validate_delivery","hold","send"] as const;
export type AiOrderingToolName = typeof AI_ORDERING_TOOL_NAMES[number];

function business(value: unknown): OrderingBusiness { if(value==="Corner Deli"||value==="Tiki") return value; throw new AiToolError("INVALID_INPUT","Unknown business.","Use Corner Deli or Tiki explicitly; never infer cross-business context.",400); }
function bodySummary(args:Record<string,unknown>) { return { keys:Object.keys(args).sort(), orderId:args.orderId?String(args.orderId):undefined, itemCount:Array.isArray(args.items)?args.items.length:undefined, queryLength:typeof args.query==="string"?args.query.length:undefined }; }
function resultSummary(result:unknown) { const row=result&&typeof result==="object"?result as Record<string,unknown>:{}; return { orderId:String(row.id||(row.order&&typeof row.order==="object"?(row.order as Record<string,unknown>).id:"")||""), resultKeys:Object.keys(row).sort() }; }

async function orderForActor(orderId:string,businessValue:OrderingBusiness):Promise<Record<string,any>> { const rows=await getSql()`SELECT id,business,display_number,status,payment_status,service_type,timing_mode,scheduled_for,version,customer_id,first_name_snapshot,last_name_snapshot,phone_snapshot,subtotal_cents,discount_cents,tax_cents,tip_cents,delivery_fee_cents,total_cents,paid_cents,amount_due_cents,timing_message_snapshot FROM ordering_orders WHERE id=${orderId} AND business=${businessValue}`; if(!rows[0]) throw new AiToolError("NOT_FOUND","The order was not found.","Use an order ID from this business.",404); const lines=await getSql()`SELECT id,item_id,item_name_snapshot,variant_id,variant_name_snapshot,quantity,unit_price_cents,modifier_total_cents,combo_total_cents,line_total_cents,special_instructions FROM ordering_order_items WHERE order_id=${orderId} ORDER BY sort_order,created_at,id`; return {...(rows[0] as Record<string,unknown>),lines,pricingAuthority:"corner_ops_server",currency:"USD"}; }

export async function executeAiOrderingTool(tool:AiOrderingToolName,args:Record<string,unknown>,businessValue:OrderingBusiness,actor:NonNullable<Awaited<ReturnType<typeof orderingActor>>>) {
  switch(tool) {
    case "describe_capabilities": return { schemaVersion:"2026-08-21",business:businessValue,tools:AI_ORDERING_TOOL_NAMES,serviceTypes:["undecided","pickup","delivery","no_contact_delivery","dine_in","curbside","bar"],money:"All monetary fields are authoritative integer cents in USD.",safety:["Use only menu facts returned by this API.","Do not infer ingredients, allergens, dietary claims, availability, or prices.","HOLD validates a draft; SEND passes authoritative confirmation gates."] };
    case "menu_browse": return {business:businessValue,scheduledFor:(requestedDate(args.scheduledFor)||new Date()).toISOString(),categories:await menuCatalog(businessValue,requestedDate(args.scheduledFor)||new Date())};
    case "menu_search": { const query=String(args.query||"").trim(); if(query.length<2) throw new AiToolError("INVALID_INPUT","Menu search needs at least two characters.","Ask for the item name or browse the menu.",400); return {business:businessValue,query,categories:await menuCatalog(businessValue,requestedDate(args.scheduledFor)||new Date(),query)}; }
    case "ordering_availability": return availabilityBundle(businessValue,serviceType(args.serviceType||"pickup"),requestedDate(args.at)||new Date());
    case "future_slots": return {business:businessValue,date:String(args.date||""),slots:await futureSlots(businessValue,serviceType(args.serviceType||"pickup"),String(args.date||""))};
    case "promotions": return {business:businessValue,promotions:await promotions(businessValue)};
    case "customer_lookup": return {business:businessValue,customers:await customerLookup(businessValue,String(args.query||"")),privacy:"Caller ID and lookup matches are not proof of identity. Disclose only ordering-relevant fields."};
    case "create_draft": return createAiDraft({business:businessValue,actor,service:serviceType(args.serviceType||"undecided"),items:itemInputs(args.items),customerId:args.customerId?String(args.customerId):null,callerPhone:String(args.callerPhone||""),firstName:String(args.firstName||""),lastName:String(args.lastName||""),scheduledFor:requestedDate(args.scheduledFor)});
    case "update_draft": { const version=Number(args.expectedVersion); if(!Number.isInteger(version)||version<1) throw new AiToolError("INVALID_INPUT","expectedVersion is required.","Read the draft and send its current version to prevent lost updates.",400); return replaceAiDraft({business:businessValue,actor,orderId:String(args.orderId||""),expectedVersion:version,service:serviceType(args.serviceType||"undecided"),items:itemInputs(args.items),customerId:args.customerId?String(args.customerId):null,callerPhone:String(args.callerPhone||""),firstName:String(args.firstName||""),lastName:String(args.lastName||""),scheduledFor:requestedDate(args.scheduledFor)}); }
    case "get_draft": return orderForActor(String(args.orderId||""),businessValue);
    case "attach_delivery_address": { const orderId=String(args.orderId||""); const order=await orderForActor(orderId,businessValue); if(order.status!=="draft") throw new AiToolError("VALIDATION_REQUIRED","Addresses can only be attached to drafts.","Historical sent orders are immutable."); const entered=String(args.address||""); let address; try { address=addressForOrder(String(order.service_type) as any,String(args.validationToken||""),entered); } catch(error) { throw new AiToolError("VALIDATION_REQUIRED",error instanceof Error?error.message:"Validate the address.","Call the address validation interface, present any candidates to the customer, then attach its token."); } if(!address) throw new AiToolError("VALIDATION_REQUIRED","A validated delivery address is required.","Validate an address and attach its token."); const route=await routeDeliveryAddress(address); await saveOrderDeliveryAddress({orderId,address,line2:String(args.unit||""),customerAddressId:args.customerAddressId?String(args.customerAddressId):null,route}); const quote=await quoteDelivery({business:businessValue,distanceMiles:route.distanceMiles,merchandiseSubtotalCents:Number(order.subtotal_cents)}); await getSql()`UPDATE ordering_orders SET delivery_fee_cents=${quote.deliveryFeeCents},total_cents=GREATEST(0,subtotal_cents-discount_cents+tax_cents+tip_cents+${quote.deliveryFeeCents}),amount_due_cents=GREATEST(0,subtotal_cents-discount_cents+tax_cents+tip_cents+${quote.deliveryFeeCents}-paid_cents),version=version+1,updated_at=NOW() WHERE id=${orderId}`; return {order:await orderForActor(orderId,businessValue),delivery:quote,route:{distanceMiles:route.distanceMiles,durationSeconds:route.durationSeconds}}; }
    case "validate_delivery": return deliveryQuote(businessValue,Number(args.distanceMiles),Number(args.merchandiseSubtotalCents));
    case "hold": return holdDraft(String(args.orderId||""),businessValue);
    case "send": { const orderId=String(args.orderId||"");const result=await sendDraft(orderId,businessValue,actor);await dispatchSubmittedOrderPrintJobs(orderId,businessValue);return result; }
  }
}

export async function POST(request:Request) {
  await ensureOrderingAiSchema();
  const started=Date.now(); let businessValue:OrderingBusiness|undefined; let actor:Awaited<ReturnType<typeof orderingActor>>=null; let tool=""; let args:Record<string,unknown>={}; let requestId=""; let conversationId=""; let model="";
  try { const body=await request.json() as Record<string,unknown>; businessValue=business(body.business); actor=await orderingActor(businessValue); if(!actor) return Response.json({ok:false,error:{code:"NOT_AUTHORIZED",message:"An authenticated business-scoped employee session is required.",remedy:"Authenticate to the requested business before invoking AI tools."}},{status:401}); tool=String(body.tool||""); if(!AI_ORDERING_TOOL_NAMES.includes(tool as AiOrderingToolName)) throw new AiToolError("INVALID_INPUT","Unknown AI ordering tool.","Call describe_capabilities and use an exact tool name.",400); args=body.arguments&&typeof body.arguments==="object"?body.arguments as Record<string,unknown>:{}; requestId=String(body.requestId||randomUUID()).slice(0,160); conversationId=String(body.conversationId||"").slice(0,160); model=String(body.model||"").slice(0,120); const duplicate=await getSql()`SELECT tool_name,outcome,error_code FROM ordering_ai_tool_events WHERE business=${businessValue} AND request_id=${requestId} LIMIT 1`; if(duplicate[0]) throw new AiToolError("VERSION_CONFLICT","This requestId has already been processed.","Do not retry a mutation ambiguously. Fetch the current draft, then issue a new requestId with its current version.",409,{priorTool:duplicate[0].tool_name,priorOutcome:duplicate[0].outcome}); const result=await executeAiOrderingTool(tool as AiOrderingToolName,args,businessValue,actor); await auditAiTool({business:businessValue,requestId,conversationId,tool,actor,orderId:String(args.orderId||(result&&typeof result==="object"?(result as Record<string,unknown>).id:"")||"")||undefined,customerId:args.customerId?String(args.customerId):undefined,outcome:"success",inputSummary:bodySummary(args),resultSummary:resultSummary(result),durationMs:Date.now()-started,model}); return Response.json({ok:true,requestId,tool,result});
  } catch(error) { const known=error instanceof AiToolError?error:new AiToolError("INTERNAL_ERROR","The ordering tool could not complete safely.","Retry once with the same structured inputs, then hand off to an employee.",500); if(businessValue&&actor&&tool) { try { await auditAiTool({business:businessValue,requestId:requestId||randomUUID(),conversationId,tool,actor,orderId:args.orderId?String(args.orderId):undefined,customerId:args.customerId?String(args.customerId):undefined,outcome:known.status>=500?"error":"blocked",errorCode:known.code,inputSummary:bodySummary(args),resultSummary:{message:known.message},durationMs:Date.now()-started,model}); } catch { /* The primary deterministic error remains authoritative. */ } } return Response.json({ok:false,requestId:requestId||undefined,tool:tool||undefined,error:{code:known.code,message:known.message,remedy:known.remedy,details:known.details}},{status:known.status}); }
}
