import { randomUUID } from "node:crypto";
import { getSession } from "@/lib/auth";
import { getSql } from "@/lib/db";
import { ensureOrderingPromotionSchema } from "@/lib/ordering-promotion-schema";

const roles=new Set(["Owner","Co-Owner","Manager"]);
async function manager(){const session=await getSession();return session&&roles.has(session.role)&&session.businesses.includes("Corner Deli")?session:null}
function cents(value:unknown,label:string){const number=Math.trunc(Number(value||0));if(!Number.isSafeInteger(number)||number<0)throw new Error(`${label} must be non-negative integer cents.`);return number}
function ids(value:unknown){return Array.isArray(value)?[...new Set(value.map(String).filter(Boolean))]:[]}

export async function GET(){
  const session=await manager();if(!session)return Response.json({error:"Manager access required."},{status:403});await ensureOrderingPromotionSchema();const sql=getSql();
  const [promotions,categories,items,variants,modifierGroups]=await Promise.all([
    sql`SELECT id,name,customer_label,internal_description,promotion_type,priority,rule,adjustment,active,automatic,stackable,stackable_with_loyalty,exclusive_group,version,updated_at FROM ordering_promotions WHERE business='Corner Deli' ORDER BY priority DESC,name`,
    sql`SELECT id,name FROM ordering_menu_categories WHERE business='Corner Deli' AND active=TRUE ORDER BY name`,
    sql`SELECT id,name,category_id FROM ordering_menu_items WHERE business='Corner Deli' AND active=TRUE ORDER BY name`,
    sql`SELECT variant.id,variant.item_id,variant.name FROM ordering_menu_item_variants variant JOIN ordering_menu_items item ON item.id=variant.item_id WHERE item.business='Corner Deli' AND variant.active=TRUE ORDER BY item.name,variant.sort_order`,
    sql`SELECT DISTINCT groups.id,groups.name FROM ordering_modifier_groups groups JOIN ordering_menu_item_modifier_groups link ON link.group_id=groups.id JOIN ordering_menu_items item ON item.id=link.item_id WHERE item.business='Corner Deli' AND groups.active=TRUE ORDER BY groups.name`,
  ]);return Response.json({promotions,categories,items,variants,modifierGroups});
}

export async function PUT(request:Request){
  const session=await manager();if(!session)return Response.json({error:"Manager access required."},{status:403});
  try{await ensureOrderingPromotionSchema();const body=await request.json() as Record<string,unknown>,sql=getSql(),id=String(body.id||randomUUID()),type=String(body.promotionType||"");if(!["bundle","amount_off","percent_off"].includes(type))throw new Error("Unsupported promotion type.");
    if(!String(body.name||"").trim())throw new Error("Promotion name is required.");if(type==="percent_off"&&Number(body.percentBasisPoints)>10000)throw new Error("Percentage cannot exceed 100 percent.");if(body.startDate&&body.endDate&&String(body.endDate)<String(body.startDate))throw new Error("Promotion end date must be on or after its start date.");if(body.startTime&&body.endTime&&String(body.endTime)<String(body.startTime))throw new Error("Promotion end time must be after its start time.");
    const components=(Array.isArray(body.components)?body.components:[]).map((raw,index)=>{const row=raw as Record<string,unknown>,quantity=Math.trunc(Number(row.quantity||1));if(quantity<1)throw new Error("Component quantity must be at least one.");const component={id:String(row.id||`component-${index+1}`),quantity,itemIds:ids(row.itemIds),categoryIds:ids(row.categoryIds),variantIds:ids(row.variantIds)};if(!component.itemIds.length&&!component.categoryIds.length&&!component.variantIds.length)throw new Error("Each component needs at least one eligible item, category, or variant.");return component});if(!components.length)throw new Error("At least one promotion component is required.");
    for(const component of components){for(const itemId of component.itemIds)if(!(await sql`SELECT id FROM ordering_menu_items WHERE id=${itemId} AND business='Corner Deli'`)[0])throw new Error("Eligible item was not found.");for(const categoryId of component.categoryIds)if(!(await sql`SELECT id FROM ordering_menu_categories WHERE id=${categoryId} AND business='Corner Deli'`)[0])throw new Error("Eligible category was not found.");for(const variantId of component.variantIds)if(!(await sql`SELECT variant.id FROM ordering_menu_item_variants variant JOIN ordering_menu_items item ON item.id=variant.item_id WHERE variant.id=${variantId} AND item.business='Corner Deli'`)[0])throw new Error("Eligible variant was not found.")}
    const modifierAllowances=[] as Array<{groupId:string;quantity:number;intensity:string}>;for(const raw of Array.isArray(body.modifierAllowances)?body.modifierAllowances:[]){const row=raw as Record<string,unknown>,groupId=String(row.groupId||""),quantity=Math.trunc(Number(row.quantity||0)),intensity=row.intensity==="any"?"any":"regular";if(quantity<1)throw new Error("Modifier allowance quantity must be at least one.");const owned=await sql`SELECT groups.id FROM ordering_modifier_groups groups JOIN ordering_menu_item_modifier_groups link ON link.group_id=groups.id JOIN ordering_menu_items item ON item.id=link.item_id WHERE groups.id=${groupId} AND item.business='Corner Deli' LIMIT 1`;if(!owned[0])throw new Error("Modifier allowance group was not found.");modifierAllowances.push({groupId,quantity,intensity})}
    const adjustment={bundlePriceCents:cents(body.bundlePriceCents,"Bundle price"),amountOffCents:cents(body.amountOffCents,"Discount"),percentBasisPoints:cents(body.percentBasisPoints,"Percentage"),modifierAllowances};
    const rule={components,repeatable:body.repeatable!==false,daysOfWeek:ids(body.daysOfWeek).map(Number),startDate:body.startDate||null,endDate:body.endDate||null,startTime:body.startTime||null,endTime:body.endTime||null,serviceTypes:ids(body.serviceTypes),channels:ids(body.channels),includedDates:ids(body.includedDates),excludedDates:ids(body.excludedDates)};
    const existing=await sql`SELECT version FROM ordering_promotions WHERE id=${id} AND business='Corner Deli'`;const version=Number(existing[0]?.version||0)+1;
    await sql`INSERT INTO ordering_promotions(id,business,name,customer_label,internal_description,promotion_type,priority,rule,adjustment,active,automatic,stackable,stackable_with_loyalty,exclusive_group,created_by,version) VALUES(${id},'Corner Deli',${String(body.name||"").trim()},${String(body.customerLabel||body.name||"").trim()},${String(body.internalDescription||"").trim()},${type},${Math.trunc(Number(body.priority||0))},${JSON.stringify(rule)}::jsonb,${JSON.stringify(adjustment)}::jsonb,${body.enabled!==false},${body.automatic!==false},${Boolean(body.stackable)},${Boolean(body.stackableWithLoyalty)},${String(body.exclusiveGroup||"").trim()},${session.email},${version}) ON CONFLICT(id) DO UPDATE SET name=EXCLUDED.name,customer_label=EXCLUDED.customer_label,internal_description=EXCLUDED.internal_description,promotion_type=EXCLUDED.promotion_type,priority=EXCLUDED.priority,rule=EXCLUDED.rule,adjustment=EXCLUDED.adjustment,active=EXCLUDED.active,automatic=EXCLUDED.automatic,stackable=EXCLUDED.stackable,stackable_with_loyalty=EXCLUDED.stackable_with_loyalty,exclusive_group=EXCLUDED.exclusive_group,version=EXCLUDED.version,updated_at=NOW()`;
    await sql`INSERT INTO ordering_pos_audit_events(id,business,event_type,actor,reason,details) VALUES(${randomUUID()},'Corner Deli','promotion_configuration_changed',${session.email},'',${JSON.stringify({promotionId:id,version,name:String(body.name||"")})}::jsonb)`;
    return Response.json({id,version});
  }catch(error){return Response.json({error:error instanceof Error?error.message:"Could not save promotion."},{status:400})}
}
