"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { BOSS_ORDERS, EVENTS, GAME_TITLE, PIZZA_SIZES, PRIZE, STAGES, TOPPINGS } from "@/lib/pizza-gauntlet/config";
import { comboMultiplier, INITIAL_STATS, randomTicket, scorePizza } from "@/lib/pizza-gauntlet/engine";
import type { GauntletEvent, GauntletStats, PizzaBuild, PizzaSize, PizzaTicket, RunCheckpoint, Topping } from "@/lib/pizza-gauntlet/types";

type Screen="title"|"playing"|"stage"|"won"|"lost";
type Save={runId:string;token:string;screen:Screen;stage:number;stageOrders:number;stats:GauntletStats;activeSeconds:number;sequence:number;tickets:PizzaTicket[];savedAt:number};
const SAVE_KEY="corner-deli-pizza-gauntlet-v1";
const emptyBuild=(ticketId=""):PizzaBuild=>({ticketId,dough:0,sauceOz:0,cheeseOz:0,toppings:{},bakeSeconds:0,boxed:false});
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(n);

function beep(kind:string,muted:boolean){if(muted)return;const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx)return;const c=new Ctx(),o=c.createOscillator(),g=c.createGain();o.type=kind==="complaint"?"sawtooth":kind==="win"?"sine":"square";o.frequency.setValueAtTime(kind==="ticket"?620:kind==="complaint"?180:880,c.currentTime);g.gain.setValueAtTime(.07,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.22);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.22)}
declare global {interface Window{webkitAudioContext?:typeof AudioContext}}

export default function Game(){
 const [screen,setScreen]=useState<Screen>("title"),[stage,setStage]=useState(1),[stageOrders,setStageOrders]=useState(0),[stats,setStats]=useState({...INITIAL_STATS});
 const [tickets,setTickets]=useState<PizzaTicket[]>([]),[selected,setSelected]=useState(""),[build,setBuild]=useState<PizzaBuild>(emptyBuild());
 const [phase,setPhase]=useState<"prep"|"oven"|"cut"|"box">("prep"),[ovenStart,setOvenStart]=useState(0),[event,setEvent]=useState<GauntletEvent|null>(null),[message,setMessage]=useState("Choose a ticket to begin.");
 const [run,setRun]=useState<{runId:string;token:string}|null>(null),[activeSeconds,setActiveSeconds]=useState(0),[sequence,setSequence]=useState(0),[muted,setMuted]=useState(false),[reward,setReward]=useState<any>(null),[name,setName]=useState(""),[resume,setResume]=useState<Save|null>(null);
 const [placing,setPlacing]=useState<Topping|null>(null),pizzaRef=useRef<HTMLDivElement>(null),lastEvent=useRef<string[]>([]),current=STAGES[stage-1];
 const ticket=tickets.find(t=>t.id===selected)||null, recipe=ticket?PIZZA_SIZES[ticket.size]:null;
 useEffect(()=>{try{setResume(JSON.parse(localStorage.getItem(SAVE_KEY)||"null") as Save|null)}catch{setResume(null)}},[screen]);

 const save=useCallback(async(next?:Partial<Save>)=>{if(!run)return;const payload:Save={...run,screen,stage,stageOrders,stats,activeSeconds,sequence,tickets,savedAt:Date.now(),...next};localStorage.setItem(SAVE_KEY,JSON.stringify(payload));},[run,screen,stage,stageOrders,stats,activeSeconds,sequence,tickets]);
 useEffect(()=>{if(screen!=="playing")return;const timer=setInterval(()=>setActiveSeconds(v=>v+1),1000);return()=>clearInterval(timer)},[screen]);
 useEffect(()=>{if(screen==="playing")save()},[screen,stageOrders,stats.ordersCompleted,save]);
 useEffect(()=>{if(screen!=="playing")return;const timer=setInterval(()=>{setTickets(old=>{if(old.length>=current.concurrentTickets)return old;const next=[...old,randomTicket(stage,stats.ordersCompleted+old.length)];beep("ticket",muted);return next})},Math.max(3000,9000-stage*800));return()=>clearInterval(timer)},[screen,current.concurrentTickets,stage,stats.ordersCompleted,muted]);
 useEffect(()=>{if(phase!=="oven"||!ovenStart)return;const t=setInterval(()=>setBuild(b=>({...b,bakeSeconds:(Date.now()-ovenStart)/1000})),100);return()=>clearInterval(t)},[phase,ovenStart]);

 async function start(){const r=await fetch("/api/pizza-gauntlet/run",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"start",playerName:name})});const data=await r.json();if(!r.ok){setMessage(data.error);return}setRun(data);setScreen("stage");setTimeout(()=>beginStage(1),1000)}
 function load(){if(!resume)return;setRun({runId:resume.runId,token:resume.token});setScreen(resume.screen==="lost"||resume.screen==="won"?"playing":resume.screen);setStage(resume.stage);setStageOrders(resume.stageOrders);setStats(resume.stats);setActiveSeconds(resume.activeSeconds);setSequence(resume.sequence);setTickets(resume.tickets||[])}
 function beginStage(n=stage){setStage(n);setStageOrders(0);setTickets([randomTicket(n,0)]);setSelected("");setBuild(emptyBuild());setPhase("prep");setScreen("playing");setMessage("Choose a ticket. Then build exactly what it says.")}
 function chooseTicket(t:PizzaTicket){setSelected(t.id);setBuild(emptyBuild(t.id));setPhase("prep");setMessage(`${t.customer}'s ticket is on your table.`)}
 function portion(type:"sauce"|"cheese",amount:number){if(!ticket)return;setBuild(b=>({...b,[type==="sauce"?"sauceOz":"cheeseOz"]:Math.max(0,Number((b[type==="sauce"?"sauceOz":"cheeseOz"]+amount).toFixed(1)))}));beep("tap",muted)}
 function placeTopping(e:React.PointerEvent){if(!placing||!pizzaRef.current)return;const r=pizzaRef.current.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;if(Math.hypot(x-.5,y-.5)>.47)return;setBuild(b=>{const old=b.toppings[placing]||{count:0,spread:0};return{...b,toppings:{...b.toppings,[placing]:{count:old.count+1,spread:Math.min(100,old.spread+Math.round(8+Math.hypot(x-.5,y-.5)*8))}}}})}
 function oven(){if(!build.size||build.dough<50){setMessage("Stretch the dough and choose a size first.");return}setPhase("oven");setOvenStart(Date.now());setMessage("IN THE OVEN — watch the timer. You can still read the rail.")}
 function pull(){setBuild(b=>({...b,bakeSeconds:(Date.now()-ovenStart)/1000}));setOvenStart(0);setPhase("cut");setMessage("Cut it to match the ticket.")}
 function applyEffects(effects:GauntletEvent["effects"]){setStats(s=>{const n={...s};for(const [k,v] of Object.entries(effects))n[k as keyof GauntletStats]=Number(n[k as keyof GauntletStats])+Number(v);return{...n,sanity:Math.min(100,n.sanity),reputation:Math.min(100,n.reputation)}})}
 async function checkpoint(nextStats:GauntletStats,nextOrders:number,nextStage=stage,nextStageOrders=stageOrders+1){if(!run)return;const seq=sequence+1,cp:RunCheckpoint={runId:run.runId,stage:nextStage,stats:nextStats,activeSeconds,stageOrders:nextStageOrders,sequence:seq};const response=await fetch("/api/pizza-gauntlet/run",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"checkpoint",token:run.token,checkpoint:cp})});if(response.ok)setSequence(seq)}
 async function deliver(){if(!ticket||!build.boxed||!build.slices)return;const result=scorePizza(build,ticket),perfect=result.perfect,newCombo=perfect?stats.combo+1:0,mult=comboMultiplier(newCombo),earned=Number((PIZZA_SIZES[ticket.size].price*result.accuracy/100*mult).toFixed(2));
  const next:GauntletStats={...stats,profit:Number((stats.profit+earned-(result.accuracy<55?PIZZA_SIZES[ticket.size].price:0)).toFixed(2)),sanity:Math.max(0,stats.sanity-(result.accuracy<70?8:0)),reputation:Math.max(0,Math.min(100,stats.reputation+(result.accuracy>=90?2:-5))),accuracy:Math.round((stats.accuracy*stats.ordersCompleted+result.accuracy)/(stats.ordersCompleted+1)),ordersCompleted:stats.ordersCompleted+1,pizzasMade:stats.pizzasMade+1,combo:newCombo,highestCombo:Math.max(stats.highestCombo,newCombo),remakes:stats.remakes+(result.accuracy<55?1:0),waste:stats.waste+(result.accuracy<55?1:0)};
  setStats(next);setTickets(xs=>xs.filter(x=>x.id!==ticket.id));setSelected("");setBuild(emptyBuild());setPhase("prep");const count=stageOrders+1;setStageOrders(count);setMessage(`${result.accuracy}% accurate · ${money(earned)} earned${perfect?" · PERFECT!":""}`);beep(perfect?"win":"tap",muted);
  if(next.sanity<=0||next.reputation<=0||next.profit<=0){setScreen("lost");return}
  if(Math.random()<current.eventChance){const possible=EVENTS.filter(e=>e.minStage<=stage&&!lastEvent.current.includes(e.id)),ev=possible[Math.floor(Math.random()*possible.length)];if(ev){lastEvent.current=[...lastEvent.current.slice(-4),ev.id];setEvent(ev);applyEffects(ev.effects);if(ev.effects.unfairComplaints)setStats(s=>({...s,combo:0}))}}
  if(count>=current.ordersRequired){if(stage===STAGES.length){await checkpoint(next,next.ordersCompleted,stage,count);const r=await fetch("/api/pizza-gauntlet/run",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"complete",runId:run?.runId,token:run?.token})});const data=await r.json();setReward(data);setScreen("won");if(r.ok)localStorage.removeItem(SAVE_KEY)}else{await checkpoint(next,next.ordersCompleted,stage+1,0);setScreen("stage");setTimeout(()=>beginStage(stage+1),2500)}}else checkpoint(next,next.ordersCompleted);
 }
 const guidance=current.guidance!=="none"&&recipe;
 return <main className="gauntlet">
  {screen==="title"&&<section className="splash"><div className="neon">CORNER DELI</div><h1>{GAME_TITLE}</h1><p className="lede">A difficult, unfair, strangely educational pizza-kitchen campaign.</p><div className="prize">SURVIVE ALL SIX SHIFTS<br/><strong>EARN A FREE JUMBO CHEESE PIZZA</strong><small>{PRIZE.toppings}</small></div><input value={name} onChange={e=>setName(e.target.value)} maxLength={40} placeholder="Cook name (optional)"/><button className="primary" onClick={start}>Clock In</button>{resume&&<button onClick={load}>Resume Shift · Stage {resume.stage}</button>}<p className="fine">A full run is designed for multiple sessions. Progress saves automatically. Prize completion is validated on the server.</p></section>}
  {screen==="stage"&&<section className="stage-card"><span>STAGE {stage}</span><h1>{current.name}</h1><p>{current.subtitle}</p>{current.boss&&<div className="boss"><b>BOSS: {current.boss}</b><br/>{BOSS_ORDERS[current.boss as keyof typeof BOSS_ORDERS]?.note}</div>}<button className="primary" onClick={()=>beginStage(stage)}>Start Shift</button></section>}
  {(screen==="playing"||screen==="lost"||screen==="won")&&<>
   <header className="hud"><div className="brand">EARN YOUR JUMBO</div>{[["PROFIT",money(stats.profit)],["SANITY",`${stats.sanity}%`],["REP",`${stats.reputation}%`],["ACCURACY",`${stats.accuracy}%`],["COMBO",`${comboMultiplier(stats.combo)}×`]].map(x=><div className="hud-stat" key={x[0]}><small>{x[0]}</small><b>{x[1]}</b></div>)}<button onClick={()=>setMuted(!muted)}>{muted?"🔇":"🔊"}</button></header>
   <section className="rail"><div className="rail-label">TICKET RAIL · {current.name} · {stageOrders}/{current.ordersRequired}</div><div className="tickets">{tickets.map((t,i)=><button onClick={()=>chooseTicket(t)} className={`ticket ${selected===t.id?"active":""}`} key={t.id}><b>#{stats.ordersCompleted+i+101} · {t.customer}</b><span>{PIZZA_SIZES[t.size].label.toUpperCase()} {t.wellDone?"· WELL DONE":""}</span><span>{t.toppings.length?t.toppings.map(x=>TOPPINGS[x].label).join(", "):"CHEESE"}</span><span>CUT {t.slices}</span></button>)}</div></section>
   <div className="game-grid"><aside className="bins"><h2>MAKE LINE</h2><div className="size-buttons">{(Object.keys(PIZZA_SIZES) as PizzaSize[]).map(s=><button className={build.size===s?"chosen":""} onClick={()=>setBuild(b=>({...b,size:s,dough:Math.max(b.dough,35)}))} key={s}>{PIZZA_SIZES[s].label}<small>{PIZZA_SIZES[s].inches}″</small></button>)}</div><label>DOUGH <b>{Math.round(build.dough)}%</b><input type="range" min="0" max="125" value={build.dough} onChange={e=>setBuild(b=>({...b,dough:+e.target.value}))}/></label><div className="portion"><button onClick={()=>portion("sauce",-.5)}>−</button><b>SAUCE {guidance?`${build.sauceOz.toFixed(1)} / ${recipe.sauce} oz`:build.sauceOz?"added":"none"}</b><button onClick={()=>portion("sauce",.5)}>+</button></div><div className="portion"><button onClick={()=>portion("cheese",-.5)}>−</button><b>CHEESE {guidance?`${build.cheeseOz.toFixed(1)} / ${recipe.cheese} oz`:build.cheeseOz?"added":"none"}</b><button onClick={()=>portion("cheese",.5)}>+</button></div><h3>TOPPING BINS</h3><div className="topping-bins">{(Object.keys(TOPPINGS) as Topping[]).map(t=><button className={placing===t?"chosen":""} onClick={()=>setPlacing(t)} key={t}><i style={{background:TOPPINGS[t].color}}/>{TOPPINGS[t].label}<small>{build.toppings[t]?.count||0}</small></button>)}</div></aside>
    <section className="work"><div className={`pizza ${phase}`} ref={pizzaRef} onPointerDown={placeTopping}>{Object.entries(build.toppings).flatMap(([t,v])=>Array.from({length:Math.min(v.count,40)},(_,i)=><i key={`${t}-${i}`} style={{background:TOPPINGS[t as Topping].color,left:`${12+((i*29+t.length*7)%76)}%`,top:`${12+((i*43+t.length*11)%76)}%`}}/>))}<span>{ticket?phase==="oven"?build.bakeSeconds.toFixed(1)+"s":PIZZA_SIZES[ticket.size].inches+"″":"NO TICKET"}</span></div><p className="status">{message}</p><div className="station-actions">{phase==="prep"&&<button className="hot" onClick={oven}>Put In Oven</button>}{phase==="oven"&&<button className="hot" onClick={pull}>Pull From Oven</button>}{phase==="cut"&&<>{[6,8,10,12].map(n=><button className={build.slices===n?"chosen":""} onClick={()=>setBuild(b=>({...b,slices:n}))} key={n}>{n} slices</button>)}<button className="hot" onClick={()=>setPhase("box")}>Cut Pizza</button></>}{phase==="box"&&<button className="hot" onClick={()=>setBuild(b=>({...b,boxed:true}))}>{build.boxed?"✓ Boxed":"Box It"}</button>}{build.boxed&&<button className="deliver" onClick={deliver}>Match & Hand Off</button>}</div>{guidance&&<div className="coach">TRAINER: Target dough 100% · sauce {recipe.sauce} oz · cheese {recipe.cheese} oz · bake {recipe.bake+(ticket?.wellDone?3:0)} sec</div>}</section>
    <aside className="shift"><h2>SHIFT BOARD</h2><p>Orders <b>{stats.ordersCompleted}</b></p><p>Pizzas <b>{stats.pizzasMade}</b></p><p>Tips <b>{money(stats.tips)}</b></p><p>Remakes <b>{stats.remakes}</b></p><p>Waste <b>{stats.waste}</b></p><p>Complaints <b>{stats.complaints}</b></p><p>Best combo <b>{stats.highestCombo}</b></p><p>Active time <b>{Math.floor(activeSeconds/60)}m</b></p><button onClick={()=>save()}>Save Shift</button><button onClick={()=>{save();setScreen("title")}}>Clock Out</button></aside></div>
  </>}
  {event&&<div className="modal"><article><div className="alert">⚠ INCIDENT</div><h2>{event.title}</h2><p>{event.message}</p><div className="effects">{Object.entries(event.effects).map(([k,v])=><span key={k}>{k} {Number(v)>0?"+":""}{v}</span>)}</div><button className="primary" onClick={()=>setEvent(null)}>Keep Working</button></article></div>}
  {screen==="lost"&&<div className="modal"><article><h1>SHIFT CATASTROPHE</h1><p>The kitchen has won. Learn the portions, watch the oven, and try again.</p><button className="primary" onClick={()=>{localStorage.removeItem(SAVE_KEY);location.reload()}}>Start Fresh</button></article></div>}
  {screen==="won"&&<div className="modal win"><article><div className="neon">YOU SURVIVED THE CORNER DELI</div><h1>YOU EARNED A JUMBO</h1>{reward?.code?<><div className="reward-code">{reward.code}</div><p>{reward.prize_type}<br/>{PRIZE.toppings}</p></>:<p>{reward?.error||"Completion is being validated. Your saved run remains available."}</p>}<div className="final-stats"><span>Orders {stats.ordersCompleted}</span><span>Pizzas {stats.pizzasMade}</span><span>Accuracy {stats.accuracy}%</span><span>Sanity {stats.sanity}%</span><span>Complained anyway {stats.unfairComplaints}</span></div></article></div>}
 </main>
}
