"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import type { Business, SessionView } from "@/lib/types";
import "../control-center.css";

type Account = { code:string; name:string; accountType:string };
type Tx = { id:string; externalAccountId:string; transactionDate:string; merchantName:string; description:string; signedAmount:number; pending:boolean; category:string; accountCode:string; reviewStatus:string; posted:boolean; reconciled:boolean; splits:Array<{accountCode:string;amount:number;memo:string}> };
type Dashboard = { accounts:Account[]; bankAccounts:Array<{externalAccountId:string;institutionName:string;name:string;mask:string;currentBalance:number|null}>; transactions:Tx[]; reconciliations:Array<Record<string,unknown>>; monthly:Array<{month:string;revenue:number;expenses:number;profit:number}>; squareDepositMatches:Array<Record<string,unknown>>; squareDays:Array<Record<string,unknown>> };
type SquareDash = { configured:{signatureKey:boolean;notificationUrl:string;environment:string}; summary:{orders:number;sales:number;taxes:number;tips:number}; topItems:Array<{item:string;quantity:number;sales:number}>; inventory:Array<{catalogObjectId:string;name:string;sku:string;price:number;quantity:number}>; webhooks:Array<Record<string,unknown>> };

type SplitLine = { accountCode:string; amount:string; memo:string };
const dollars=(value:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(value||0);
const defaultDate=()=>new Date().toISOString().slice(0,10);
async function errorMessage(r:Response){const p=await r.json().catch(()=>null) as {error?:string}|null;return p?.error||`Request failed (${r.status}).`;}

export default function AccountingControlPage(){
  const [session,setSession]=useState<SessionView|null>(null); const [business,setBusiness]=useState<Business>("Corner Deli");
  const [data,setData]=useState<Dashboard|null>(null); const [square,setSquare]=useState<SquareDash|null>(null); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState(false);
  const [selected,setSelected]=useState<string[]>([]); const [splitTx,setSplitTx]=useState<Tx|null>(null); const [splitLines,setSplitLines]=useState<SplitLine[]>([{accountCode:"",amount:"",memo:""}]);
  useEffect(()=>{fetch("/api/auth/session",{cache:"no-store"}).then(r=>r.json()).then(setSession);},[]);
  async function load(active=business){setNotice("");const [a,s]=await Promise.all([fetch(`/api/accounting-control?business=${encodeURIComponent(active)}`,{cache:"no-store"}),fetch("/api/accounting-control?area=square",{cache:"no-store"})]);if(!a.ok)throw new Error(await errorMessage(a));setData(await a.json());if(s.ok)setSquare(await s.json());}
  useEffect(()=>{if(session?.authenticated)load(business).catch(e=>setNotice(e.message));},[session?.authenticated,business]);
  async function post(body:Record<string,unknown>){setBusy(true);setNotice("");try{const r=await fetch("/api/accounting-control",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw new Error(await errorMessage(r));const result=await r.json();await load();return result;}catch(e){setNotice(e instanceof Error?e.message:String(e));throw e;}finally{setBusy(false);}}
  const unposted=useMemo(()=>data?.transactions.filter(t=>!t.posted&&!t.pending)||[],[data]); const maxProfit=Math.max(1,...(data?.monthly||[]).map(m=>Math.max(0,m.profit)));
  function beginSplit(tx:Tx){setSplitTx(tx);setSplitLines(tx.splits.length?tx.splits.map(l=>({accountCode:l.accountCode,amount:String(l.amount),memo:l.memo})):[{accountCode:tx.accountCode||"",amount:String(Math.abs(tx.signedAmount)),memo:""}]);}
  async function saveSplit(){if(!splitTx)return;await post({action:"transaction-split",business,transactionId:splitTx.id,lines:splitLines.map(l=>({...l,amount:Number(l.amount)}))});setSplitTx(null);setNotice("Split saved and transaction approved.");}
  async function openingBalance(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await post({action:"opening-balance",business,entryDate:f.get("entryDate"),description:f.get("description"),reference:f.get("reference"),lines:[{accountCode:f.get("assetCode"),debit:Number(f.get("assetDebit")||0),credit:Number(f.get("assetCredit")||0)},{accountCode:f.get("offsetCode"),debit:Number(f.get("offsetDebit")||0),credit:Number(f.get("offsetCredit")||0)}]});e.currentTarget.reset();setNotice("Opening balance posted.");}
  async function reconcile(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const submitter=(e.nativeEvent as SubmitEvent).submitter as HTMLButtonElement|null;const finalize=submitter?.value==="finalize";const result=await post({action:"reconciliation-save",business,externalAccountId:f.get("externalAccountId"),statementStartDate:f.get("statementStartDate"),statementEndDate:f.get("statementEndDate"),beginningBalance:Number(f.get("beginningBalance")||0),endingBalance:Number(f.get("endingBalance")||0),transactionIds:selected,notes:f.get("notes"),finalize});setNotice(`Reconciliation ${result.status}. Difference: ${dollars(result.difference)}.`);}
  async function historyImport(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const f=new FormData(e.currentTarget);f.set("action","historical-import");f.set("business",business);f.set("postApproved",String(f.get("postApproved")==="on"));const r=await fetch("/api/accounting-control",{method:"POST",body:f});if(!r.ok)throw new Error(await errorMessage(r));const result=await r.json();await load();setNotice(`Imported ${result.imported} coded transactions; posted ${result.posted}.`);}catch(e){setNotice(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}
  if(!session)return <main className="controlPage"><p>Loading…</p></main>; if(!session.authenticated)return <main className="controlPage"><a href="/signin">Sign in to Corner Ops</a></main>;
  return <main className="controlPage">
    <header className="controlHeader"><div><p className="eyebrow">Accounting control</p><h1>{business} books</h1><p>Review, split, post, reconcile, and report without asking a spreadsheet to pretend it is a database.</p></div><div className="controlActions"><div className="businessPills">{(["Corner Deli","Tiki"] as Business[]).map(b=><button key={b} className={business===b?"active":""} onClick={()=>{setBusiness(b);setSelected([])}}>{b}</button>)}</div><button disabled={busy} onClick={()=>post({action:"post-approved",business}).then(r=>setNotice(`Posted ${r.filter((x:{ok:boolean})=>x.ok).length} approved transactions.`))}>Post all approved</button><a href="/ops">Operations</a></div></header>
    {notice&&<div className="noticeBar">{notice}</div>}
    <div className="controlGrid">
      <section className="controlCard"><div className="metricGrid"><div className="metric"><span>Imported transactions</span><strong>{data?.transactions.length||0}</strong></div><div className="metric"><span>Ready to post</span><strong>{unposted.filter(t=>t.reviewStatus==="Approved").length}</strong></div><div className="metric"><span>Posted</span><strong>{data?.transactions.filter(t=>t.posted).length||0}</strong></div><div className="metric"><span>Reconciled</span><strong>{data?.transactions.filter(t=>t.reconciled).length||0}</strong></div></div></section>
      <section className="controlCard"><p className="eyebrow">Bank feed to ledger</p><h2>Transactions</h2><div className="tableWrap"><table className="controlTable"><thead><tr><th></th><th>Date / payee</th><th>Amount</th><th>Coding</th><th>Status</th><th>Actions</th></tr></thead><tbody>{data?.transactions.map(tx=><tr key={tx.id}><td className="checkCell"><input type="checkbox" checked={selected.includes(tx.id)} disabled={tx.reconciled} onChange={e=>setSelected(v=>e.target.checked?[...v,tx.id]:v.filter(id=>id!==tx.id))}/></td><td><strong>{tx.merchantName||tx.description}</strong><small>{tx.transactionDate} · {tx.description}</small></td><td className={`amount ${tx.signedAmount>=0?"in":"out"}`}>{dollars(tx.signedAmount)}</td><td>{tx.splits.length?`${tx.splits.length} split lines`:tx.accountCode||"Uncoded"}<small>{tx.category}</small></td><td><span className={`badge ${tx.posted||tx.reconciled?"good":tx.reviewStatus==="Approved"?"warn":"bad"}`}>{tx.reconciled?"Reconciled":tx.posted?"Posted":tx.reviewStatus}</span></td><td><button onClick={()=>beginSplit(tx)} disabled={tx.posted}>Split</button> <button onClick={()=>post({action:"transaction-post",business,transactionId:tx.id}).then(()=>setNotice("Transaction posted."))} disabled={busy||tx.posted||tx.reviewStatus!=="Approved"}>Post</button></td></tr>)}</tbody></table></div></section>
      {splitTx&&<section className="controlCard modalish"><p className="eyebrow">Split transaction</p><h2>{splitTx.merchantName||splitTx.description} · {dollars(Math.abs(splitTx.signedAmount))}</h2><div className="splitRows">{splitLines.map((line,i)=><div className="splitRow" key={i}><select value={line.accountCode} onChange={e=>setSplitLines(v=>v.map((x,j)=>j===i?{...x,accountCode:e.target.value}:x))}><option value="">Choose account</option>{data?.accounts.map(a=><option key={a.code} value={a.code}>{a.code} · {a.name}</option>)}</select><input value={line.amount} type="number" step="0.01" placeholder="Amount" onChange={e=>setSplitLines(v=>v.map((x,j)=>j===i?{...x,amount:e.target.value}:x))}/><input value={line.memo} placeholder="Memo" onChange={e=>setSplitLines(v=>v.map((x,j)=>j===i?{...x,memo:e.target.value}:x))}/><button onClick={()=>setSplitLines(v=>v.filter((_,j)=>j!==i))}>Remove</button></div>)}</div><div className="controlActions"><button onClick={()=>setSplitLines(v=>[...v,{accountCode:"",amount:"",memo:""}])}>Add line</button><button className="primary" onClick={saveSplit} disabled={busy}>Save split</button><button onClick={()=>setSplitTx(null)}>Cancel</button></div></section>}
      <section className="controlCard half"><p className="eyebrow">Statement control</p><h2>Bank reconciliation</h2><form className="controlForm" onSubmit={reconcile}><label>Bank account<select name="externalAccountId" required><option value="">Choose account</option>{data?.bankAccounts.map(a=><option key={a.externalAccountId} value={a.externalAccountId}>{a.institutionName} · {a.name} •{a.mask}</option>)}</select></label><label>Selected transactions<input value={`${selected.length} selected`} readOnly/></label><label>Statement start<input name="statementStartDate" type="date" required/></label><label>Statement end<input name="statementEndDate" type="date" required/></label><label>Beginning balance<input name="beginningBalance" type="number" step="0.01" required/></label><label>Ending balance<input name="endingBalance" type="number" step="0.01" required/></label><label className="wide">Notes<textarea name="notes"/></label><div className="controlActions wide"><button type="submit">Save draft</button><button type="submit" name="mode" value="finalize" className="primary" disabled={busy}>Finalize</button></div></form><div className="list">{data?.reconciliations.slice(0,6).map((r:any)=><div className="listItem" key={r.id}><div><strong>{r.statementEndDate}</strong><span>{r.itemCount} items · difference {dollars(r.difference)}</span></div><span className={`badge ${r.status==="Finalized"?"good":"warn"}`}>{r.status}</span></div>)}</div></section>
      <section className="controlCard half"><p className="eyebrow">Starting point</p><h2>Opening balance</h2><form className="controlForm" onSubmit={openingBalance}><label>Date<input name="entryDate" type="date" defaultValue={defaultDate()} required/></label><label>Description<input name="description" defaultValue="Opening balances" required/></label><label>Debit account<select name="assetCode">{data?.accounts.map(a=><option key={a.code} value={a.code}>{a.code} · {a.name}</option>)}</select></label><label>Debit amount<input name="assetDebit" type="number" step="0.01"/></label><label>Credit account<select name="offsetCode">{data?.accounts.map(a=><option key={a.code} value={a.code}>{a.code} · {a.name}</option>)}</select></label><label>Credit amount<input name="offsetCredit" type="number" step="0.01"/></label><label className="wide">Reference<input name="reference"/></label><button className="primary" disabled={busy}>Post opening entry</button></form></section>
      <section className="controlCard half"><p className="eyebrow">History migration</p><h2>Import coded bookkeeping workbook</h2><form className="controlForm" onSubmit={historyImport}><label>Institution/source<input name="institutionName" defaultValue="Historical bookkeeping"/></label><label>Workbook<input name="file" type="file" accept=".xlsx,.xls,.csv" required/></label><label className="wide"><span><input name="postApproved" type="checkbox"/> Post imported approved rows immediately</span></label><button className="primary" disabled={busy}>Import history</button></form></section>
      <section className="controlCard half"><p className="eyebrow">18-month trend</p><h2>Monthly profit</h2><div className="chartBars">{data?.monthly.map(m=><div className="chartBar" key={m.month} title={`${m.month}: ${dollars(m.profit)}`}><i style={{height:`${Math.max(2,(Math.max(0,m.profit)/maxProfit)*180)}px`}}/><small>{m.month}</small></div>)}</div></section>
      {business==="Tiki"&&<><section className="controlCard"><div className="controlActions"><button className="primary" onClick={()=>post({action:"square-sync-full"}).then(r=>setNotice(`Square synced: ${r.orders} orders, ${r.catalog} catalog objects, ${r.inventory} inventory counts.`))} disabled={busy}>Full Square sync</button><a href="/api/square/connect">Reconnect with inventory access</a><button onClick={()=>post({action:"square-match-build"}).then(r=>setNotice(`Built ${r.created} deposit suggestions.`))}>Build deposit matches</button></div><div className="metricGrid"><div className="metric"><span>Square orders, 30 days</span><strong>{square?.summary.orders||0}</strong></div><div className="metric"><span>Sales</span><strong>{dollars(square?.summary.sales||0)}</strong></div><div className="metric"><span>Tax</span><strong>{dollars(square?.summary.taxes||0)}</strong></div><div className="metric"><span>Tips</span><strong>{dollars(square?.summary.tips||0)}</strong></div></div></section><section className="controlCard half"><p className="eyebrow">Deposit reconciliation</p><h2>Square matches</h2><div className="list">{data?.squareDepositMatches.map((m:any)=><div className="listItem" key={m.id}><div><strong>{m.transactionDate} · {dollars(m.bankAmount)}</strong><span>Square net {dollars(m.squareNet)} · variance {dollars(m.variance)}</span></div><div><span className={`badge ${m.status==="Matched"?"good":"warn"}`}>{m.status}</span> {m.status==="Suggested"&&<button onClick={()=>post({action:"square-match-status",id:m.id,status:"Matched"})}>Accept</button>}</div></div>)}</div></section><section className="controlCard half"><p className="eyebrow">Sales journal</p><h2>Square business days</h2><div className="list">{data?.squareDays.map((d:any)=><div className="listItem" key={d.businessDate}><div><strong>{d.businessDate} · {d.payments} payments</strong><span>{dollars(d.amount)} sales · {dollars(d.tips)} tips</span></div>{d.posted?<span className="badge good">Posted</span>:<button onClick={()=>post({action:"square-day-post",businessDate:d.businessDate})}>Post day</button>}</div>)}</div></section><section className="controlCard half"><p className="eyebrow">Best sellers</p><h2>Top items</h2>{square?.topItems.slice(0,12).map(i=><div className="topItem" key={i.item}><strong>{i.item}</strong><span>{i.quantity.toFixed(1)}</span><span>{dollars(i.sales)}</span></div>)}</section><section className="controlCard half"><p className="eyebrow">Inventory</p><h2>Lowest on-hand counts</h2>{square?.inventory.slice(0,15).map(i=><div className="topItem" key={i.catalogObjectId}><strong>{i.name||i.sku||i.catalogObjectId}</strong><span>{i.sku}</span><span className={i.quantity<=0?"dangerText":""}>{i.quantity}</span></div>)}</section></>}
    </div>
  </main>;
}
