import { activateGiftCard, adjustGiftCard, GiftCardError, lookupGiftCard, reloadGiftCard, replaceGiftCard } from "@/lib/ordering-gift-cards";
import type { OrderingBusiness } from "@/lib/ordering-core";
import { orderingActor } from "@/lib/ordering-route-auth";
import { apiError, unauthorized } from "@/lib/http";
export const runtime="nodejs";
const business=(value:unknown):OrderingBusiness=>{if(value==='Corner Deli'||value==='Tiki')return value;throw new GiftCardError('Unknown business.')};
export async function GET(request:Request){try{const url=new URL(request.url),scope=business(url.searchParams.get('business')),actor=await orderingActor(scope);if(!actor)return unauthorized();return Response.json(await lookupGiftCard({business:scope,cardNumber:url.searchParams.get('cardNumber')||'',pin:url.searchParams.get('pin')||undefined,includeHistory:actor.role!=='employee'}))}catch(error){if(error instanceof GiftCardError)return Response.json({error:error.message},{status:404});return apiError(error)}}
export async function POST(request:Request){try{const body=await request.json() as Record<string,unknown>,scope=business(body.business),actor=await orderingActor(scope);if(!actor)return unauthorized();return Response.json(await activateGiftCard({business:scope,initialLoadCents:Number(body.initialLoadCents),operationKey:String(body.operationKey||''),actor,pin:body.pin?String(body.pin):undefined}),{status:201})}catch(error){if(error instanceof GiftCardError)return Response.json({error:error.message},{status:error.message.includes('authorization')?403:409});return apiError(error)}}
export async function PATCH(request:Request){try{const body=await request.json() as Record<string,unknown>,scope=business(body.business),actor=await orderingActor(scope);if(!actor)return unauthorized();const common={business:scope,cardNumber:String(body.cardNumber||''),operationKey:String(body.operationKey||''),actor};let result;if(body.action==='reload')result=await reloadGiftCard({...common,amountCents:Number(body.amountCents),note:body.note?String(body.note):undefined});else if(body.action==='adjust')result=await adjustGiftCard({...common,deltaCents:Number(body.deltaCents),reason:String(body.reason||'')});else if(body.action==='replace')result=await replaceGiftCard({...common,newCardNumber:body.newCardNumber?String(body.newCardNumber):undefined,pin:body.pin?String(body.pin):undefined,reason:String(body.reason||'')});else throw new GiftCardError('Unknown gift card operation.');return Response.json(result)}catch(error){if(error instanceof GiftCardError)return Response.json({error:error.message},{status:error.message.includes('authorization')?403:409});return apiError(error)}}
