/**
 * A shift is one street, Paperboy style: it always lasts `time` seconds of
 * driving, `deliveries` houses on it have ordered, and you keep your job only
 * if at least `quota` of them get their food.
 */
export const DELIVERY_STAGES = [
  { day: "MONDAY", name: "Monday Lunch", deliveries: 14, quota: 9, speed: 150, time: 60 },
  { day: "TUESDAY", name: "Tuesday Dinner Run", deliveries: 16, quota: 11, speed: 175, time: 66 },
  { day: "WEDNESDAY", name: "Wing Wednesday", deliveries: 18, quota: 13, speed: 200, time: 72 },
  { day: "THURSDAY", name: "Deer O'Clock", deliveries: 20, quota: 15, speed: 225, time: 78 },
  { day: "FRIDAY", name: "Friday Night Rush", deliveries: 22, quota: 17, speed: 250, time: 84 },
] as const;

/** Leave empty to hide the "real page" link in the game. */
export const DELIVERY_FACEBOOK_URL = "https://www.facebook.com/ordercornerdeli/";

/**
 * Shifts run for a fixed amount of driving, so a run that checkpoints faster
 * than this (with a little slack for timer jitter) was not played in a browser.
 */
export function deliveryMinimumSeconds(throughStage: number) {
  return (
    DELIVERY_STAGES.slice(0, throughStage).reduce(
      (total, route) => total + route.time,
      0,
    ) * 0.95
  );
}

export function deliveryQuotaThrough(stage: number) {
  return DELIVERY_STAGES.slice(0, stage).reduce(
    (total, route) => total + route.quota,
    0,
  );
}

export const DELIVERY_FIRED = [
  "You finished the street with hungry customers behind you. Dispatch has asked you to return to the store and explain the shrubs.",
  "Too many porches got nothing but eye contact and a confident wave. You are now a former employee and a current Facebook topic.",
  "Several hedges on this route are now better fed than the customers. Management has reassigned you to the hedges.",
  "You returned to the deli with a bag full of subs and a phone full of voicemails. Shift over.",
  "The customers you missed have formed a group chat. It has more members than the deli has employees.",
] as const;

/** Every name here is fictional. */
export const DELIVERY_FACEBOOK_PEOPLE = [
  "Brenda K.",
  "Dale (Not That Dale)",
  "Concerned Ogdensburg Resident",
  "Tammy Lynn R.",
  "Gary From The Corner",
  "Deb S.",
  "Ron 'The Mayor' P.",
  "Kayleigh M.",
  "Big Steve",
  "Linda (Admin of 4 Groups)",
  "Chet W.",
  "Marge T.",
] as const;

/** Posted even when the sub landed perfectly. {item} {address} are filled in. */
export const DELIVERY_FACEBOOK_DELIVERED = [
  "Found a HAIR in my {item}. The cook is bald. The driver is bald. I have a chunk missing from the back of my head but that is unrelated and I resent the implication. 1 star.",
  "My {item} was perfect, which is how I know they're hiding something. Nobody is this good at sandwiches without a reason.",
  "The sub was cut in half. I asked for it whole. I then cut it in half myself because it was too long. Still mad.",
  "There was too much meat in my {item}. I had to eat it all. I have a doctor's appointment Thursday and I'll be bringing this up.",
  "The pickle was looking at me. I'm not saying it was alive. I'm saying it was looking at me.",
  "Got my {item} in 18 minutes. My last relationship lasted 14. I'm not ready to be this happy.",
  "They put mayo on it like I asked. I did not ask. I checked the receipt and I did ask. I'm leaving the review up anyway.",
  "The driver complimented my wreath. It's October. I don't have a wreath. Who's wreath did he see.",
  "Sub was hot. I ordered a cold sub. Then it got cold. Then I wanted it hot. Nobody at this deli thinks ahead.",
  "The bag was knotted so well I had to use the good scissors. My wife uses the good scissors for fabric only. My marriage is in trouble and the sub was great.",
  "The delivery guy said 'enjoy' like he knew something. I didn't enjoy it. I mean I did. But I didn't want to.",
  "Food was delicious but I can't find the receipt and I'm convinced it was delivered to my house by mistake. Keeping it.",
  "My {item} arrived exactly when the app said. That's never happened. I've already called my cousin in Massena to tell him nothing is real anymore.",
  "There was a hair in my food. It was mine. I'd like to know what the deli plans to do about it.",
  "I ordered extra onions. They gave me extra onions. Now my car smells like extra onions. Should've warned me.",
  "Delivered right to the porch. Problem is I was on the porch. The sub hit me. Still ate it. 2 stars.",
  "They spelled my name right on the bag. I didn't give them my name. 5 stars but I'm sleeping with the lights on.",
  "Got a free cookie I didn't ask for. Now I have to eat a cookie. Some of us are trying.",
  "The bread was so fresh it was still warm and I felt like it was judging my kitchen. Clean your own kitchen, bread.",
  "Perfectly fine sub. Wanted to leave a review anyway so the page knows I'm watching.",
  "My {item} arrived at {address} hot, on time, and correct. I have never been so suspicious in my life. Who is running this deli and what do they want.",
  "Driver threw my {item} onto the porch. It landed perfectly. Too perfectly. I watched the Ring footage 40 times and I believe he has done this before. 2 stars.",
  "Ordered a {item}. Received a {item}. Where is the surprise? Where is the adventure? Ogdensburg used to have spirit.",
  "The {item} came in a bag. I did not consent to a bag.",
  "Delivery was so fast I had not finished complaining about the wait yet. Now I have to complain about this instead.",
  "Driver did not wave. Driver was going 30 mph and throwing a sandwich. Still. Would have been nice.",
  "My {item} was delivered to the correct address which is fine but my neighbor got one too and nobody explained that to me.",
  "I asked for the sub to be left at the side door. It was left at the side door. The side door is not where I am. 1 star.",
  "{item} was excellent. Unfortunately I ordered it for my husband and he loved it, so now he is insufferable. Who do I contact.",
  "The sub landed on my welcome mat, which says WELCOME, so technically I invited it. I'd like to rescind that.",
  "Sub was great. The bread was so soft I worried about it. Is the bread okay. Is anyone checking on the bread.",
  "Arrived at {address} in under 20 minutes. My dog was not ready. My dog has never been ready.",
  "Tossed my {item} from a moving vehicle like a newspaper in a 1985 arcade game. Honestly the best thing that's happened on this street since the parade.",
  "The driver's car had a sub on the roof. I asked if that was mine. It was not mine. Now I want that one.",
  "My order arrived correctly and the receipt was stapled straight. Who is training these people. It's unsettling.",
  "I tipped in the app and the driver still threw it. I would like to know what tipping is FOR.",
  "Not a complaint, just want everyone to know I got a {item} and you didn't. Anyway 3 stars.",
  "Sub was delivered on time but in the general direction of my cat. The cat would like a word with management.",
  "Five stars for the food. One star because the delivery car is louder than my thoughts.",
  "The {item} landed on my porch. My porch is on the second floor. I need to know how.",
] as const;

/** Posted by the houses the driver missed. */
export const DELIVERY_FACEBOOK_MISSED = [
  "Ordered a {item} to {address} 45 minutes ago. Just watched the Corner Deli car drive past my house AT SPEED, holding my sub, making eye contact.",
  "Still waiting on my {item}. I can see it from my window. It's in the neighbor's hedge. Do I go get it? Is that legal?",
  "Driver blew right past {address}. Didn't even slow down. I'm not mad, I'm just going to post about it in five groups.",
  "My {item} never came. I'm sitting on the porch in a lawn chair like it's 1962 and I'm waiting for a ship.",
  "The car went by so fast my wind chimes are still going. No sub though. Just chimes.",
  "No {item}. Called the deli. They said the driver 'saw a goose.' We all saw a goose. We have been seeing that goose for three years.",
  "Waited an hour. Then I made a sandwich. Then I ate it angrily. Then I wrote this. Then I made another sandwich.",
  "Watched my dinner go by on Google Maps tracking like a satellite I could not reach.",
] as const;

/** Posted by houses that never ordered but got a sub anyway. */
export const DELIVERY_FACEBOOK_SAMPLES = [
  "A sandwich hit my porch tonight and I did not order it. Best sub of my life. 1 star because I feel like I'm being recruited.",
  "Someone threw a free sub at my house. I've been in the North Country 58 years and I know a bribe when I see one. It worked though.",
  "Is anyone else getting unsolicited subs?? Mine was a {item}. I want to know who's getting the steak ones.",
  "Free {item} landed on my lawn. Called the deli to report it. They asked if I wanted to order a drink with that. Bold.",
  "I don't live here, I'm house-sitting, and the house got a sub. Does the sub count as part of the house. Asking for legal reasons.",
  "Unordered sub on my steps. My Ring camera caught it all. Uploading in 4K, slow motion, with dramatic music.",
] as const;

/** For a shift where every single order landed. */
export const DELIVERY_FACEBOOK_PERFECT = [
  "Every house on my street got their order tonight and nobody's complaining. I don't trust it. Something is coming.",
  "Whole block got fed on time. Linda from the group says it's a scam. Linda has not said what the scam is.",
  "Corner Deli delivered to every house on the street. Even the house that's just a garage. The garage is thrilled.",
  "Flawless route tonight. The deer are regrouping. Mark my words.",
] as const;

/** Comments under the posts. {name} is another fictional person. */
export const DELIVERY_FACEBOOK_COMMENTS = [
  "Mine was perfect too. Disgusting.",
  "this is why I only order from the deli in person and then stand in the kitchen",
  "{name} you need to let it go, it's been since 2019",
  "Did anyone else see the goose",
  "My cousin's friend drives for them and says the subs are 'aerodynamically wrapped.' Make of that what you will.",
  "Following",
  "I had the Big Boss Sub and lost the ability to speak for 20 minutes. In a good way.",
  "{name} that's not even your street",
  "Shared to Ogdensburg Rants & Raves (Unfiltered) (No Politics) (Some Politics)",
  "The cow on River Rd has seen things.",
  "I don't understand the problem. You got a sub. Celebrate.",
  "Every time the delivery car goes by my dog thinks it's his birthday",
  "This is why my grandfather walked to the deli. Uphill. In the snow. Both directions.",
  "Not to brag but mine hit my mailbox and the flag went up",
  "Can confirm, I am the neighbor, the sub was delicious",
  "{name} please stop tagging me in these",
] as const;

/** The deli's deadpan replies. */
export const DELIVERY_FACEBOOK_REPLIES = [
  "We're so sorry the sandwich was correct. We'll look into it.",
  "Thank you for your feedback. We have forwarded it to the driver, who read it at 30 mph.",
  "We appreciate you! Please don't stand in the kitchen.",
  "The goose has been spoken to.",
  "Our drivers are trained to deliver to the porch. The porch moved. We're working with the porch.",
  "Thanks for reaching out! Your sub is in the hedge. It is still a good sub.",
  "We hear you. We are also scared of how good the bread is.",
  "Please DM us your address so we can deliver an apology sub at a more reasonable velocity.",
] as const;

export const DELIVERY_CAR_CRASHES = [
  "You hit a parked Pontiac that has not moved since the 1998 ice storm. Ogdensburg finally found a use for it: ending your shift.",
  "DPW only moves abandoned cars during a full moon. Unfortunately, you moved this one during a waxing gibbous and voided the warranty.",
  "You hit a car with no plates, no insurance, and a driver who somehow already knows your manager.",
  "The other car was double-parked on Ford Street. The city ruled that this made it a historic landmark, not an obstacle.",
  "You rear-ended the only vehicle in Ogdensburg with a working inspection sticker. Statistically incredible. Financially devastating.",
  "That Buick had been parked there since Ponderosa closed. The owner appeared in eleven seconds asking for cash.",
  "You found the one North Country car held together by structural road salt. It has returned to its natural powdered form.",
  "The collision report lists the cause as 'too much ambition near a Dollar General.' Route over.",
  "You hit a sedan outside Price Chopper. Three witnesses saw everything; all three gave directions to a different Price Chopper.",
  "The other driver said, 'I know the owner.' Nobody knows which owner, but your shift is still over.",
  "You attempted an Ogdensburg three-point turn. It became a nine-point insurance claim.",
  "That abandoned Impala was load-bearing. Half the block is now leaning toward Canada.",
  "You clipped a car near the bridge. Customs would like to know whether the bumper is declaring anything.",
  "The GPS said turn left. The parked minivan strongly disagreed and submitted photographic evidence.",
  "You hit a car whose hazard lights have been blinking since last Tuesday. They were not decorative after all.",
  "The owner says the dent was not there before. The twelve older dents have declined to comment.",
  "You tried to dodge an Ogdensburg pothole and discovered its support vehicle.",
  "You struck a snowbank containing a 2006 Chevy. Spring would have revealed it eventually.",
  "The road had two lanes. You invented a third one through somebody's Saturn.",
  "You sideswiped a car parked six feet from the curb. Local zoning calls that 'close enough.'",
  "The other vehicle was legally parked, spiritually abandoned, and mechanically deceased. Insurance still says you lose.",
  "You hit the unofficial city snow-measuring car. Judging by the roof, accumulation is one Equinox deep.",
  "A witness described your driving as 'Lisbon fast.' Dispatch has no idea what that means but fired you immediately.",
  "You crashed beside the entering-Lisbon sign. The sign has been updated to read LEAVING EMPLOYMENT.",
  "The parked truck had a plow wider than the street. You found the four inches it did not protect.",
  "You collided with a car outside Stewart's. Your sub survived and has been promoted to driver.",
  "That car was waiting for parts from Watertown. It now requires all of Watertown.",
  "You hit a vehicle with FOR SALE written in the window. The price just became one insurance deductible.",
  "The impact woke a car alarm nobody knew still worked. It is now Ogdensburg's loudest functioning public service.",
  "You bumped a parked car and six porch cameras uploaded the director's cut before you found reverse.",
  "The abandoned car was scheduled for removal right after Ogdensburg finished the other thing. No date was provided.",
  "You mistook a grey crossover for road texture. As the grey crossover driver, this defense has not impressed anyone.",
  "You hit a car while avoiding a squirrel. The squirrel stayed to exchange insurance information on your behalf.",
  "The collision occurred at North Country speed: somehow both too slow and wildly unsafe.",
  "You drove onto the curb and met a Chrysler whose parking strategy was already under federal review.",
  "That vehicle survived twenty-six winters, four transmissions, and one divorce. Your shift finally defeated it.",
  "You hit the neighbor's car. The customer still wants the sub and wants the crash excluded from delivery time.",
  "The other driver asked if the fries are okay before checking their bumper. This is now evidence.",
  "You struck a car hidden behind an enormous snow pile. The snow pile has denied any involvement.",
  "You clipped a mirror on State Street. It landed in a pothole and is now city property.",
  "Dispatch says you cannot classify a collision as an expedited curbside handoff.",
  "You hit a parked car, delivered the sub through its open window, and still received a wrong-address complaint.",
  "The police report says 'driver followed the glowing house directly through a Nissan.' The feature remains enabled.",
  "You encountered an Ogdensburg traffic jam: one moving car, two parked cars, and everyone claiming right of way.",
  "The bumper came off before impact, says the owner. You are being billed for improving its momentum.",
  "You crashed near the river. The seagulls formed an accident team and demand fries as a retainer.",
  "Your Equinox met another equinox. Astronomers expected it; management still fired you.",
  "You hit a car so quietly the customer complained you failed to knock. The adjuster heard it just fine.",
] as const;
export const DELIVERY_PRIZE = {
  name: "One Free Regular Sub",
  terms:
    "One regular cold or hot sub. Extras and premium upgrades regular price.",
  expiresDays: 30,
};
export const DELIVERY_COMPLAINTS = [
  "Customer found a hair in their sub. The cook is bald. The driver is bald. The customer is missing a patch of hair from the back of their head. Investigation closed; customer is still furious.",
  "Customer says the sub was 'too correct' and requests that next time we 'surprise them a little.'",
  "Customer reports the delivery was so fast it 'felt rushed' and the sub 'didn't get to know the neighborhood.'",
  "Customer wants a refund because the sub was better than their mother's. Their mother has been informed. Their mother agrees.",
  "Customer says the driver waved too enthusiastically and it 'set an expectation for the rest of the week.'",
  "Customer received exactly what they ordered and is demanding to know who told us.",
  "Customer says the bag was 'too easy to open' and they felt 'unchallenged.'",
  "Customer complained that the sub was cut on a diagonal 'at a political angle.'",
  "Customer says you never arrived. Route log: you stared at each other through the storm door for 2:07.",
  "Customer reports the sub was shaken. The road reports the customer owns a driveway made entirely of potholes.",
  "Customer asked for quiet delivery, then called because you did not knock.",
  "Customer says you were late. They entered the wrong address and remain furious at geography.",
  "Customer watched you approach through the blinds, waited for you to leave, then reported no delivery attempt.",
  "Customer says the bag was six inches left of where they expected it. Investigation ongoing.",
  "Customer requested FRONT DOOR. House contains seven doors and no visible front.",
  "Customer says the fries shifted during transit. Gravity has been notified.",
  "Customer claims the deer in their driveway is your employee and wants a manager.",
  "Customer says delivery was too fast and they weren't emotionally prepared for dinner.",
  "Customer has no teeth and is furious that nobody pre-chewed the sub. The online notes only said EXTRA ONIONS.",
  "Customer says the sandwich tastes too much like the sandwich they ordered. They expected us to understand the vibe.",
  "Customer demands a refund because the driver did not wave at their Ring camera with sufficient enthusiasm.",
  "Customer reports that the sub arrived horizontal. They wanted it delivered in portrait mode.",
  "Customer says you frightened their decorative porch goose. The goose has retained an attorney.",
  "Customer ordered a hot sub, waited 48 minutes to retrieve it, and has discovered thermodynamics.",
  "Customer claims the mayonnaise shifted to the west side of the sandwich during transit.",
  "Customer says the driver drove on the road and calls this extremely unprofessional.",
  "Customer insists 412 Jay Street is not 412 Jay Street on Tuesdays.",
  "Customer wanted contactless delivery but is upset you did not come inside and explain the specials.",
  "Customer says the bag made eye contact with them. They no longer feel safe in their own home.",
  "Customer reports the pickles were shaken emotionally, though physically they remain intact.",
  "Customer says the sub is too long for lunch but somehow not long enough for dinner.",
  "Customer's dog ate the order before the door closed. They would like to know what we plan to do about our accomplice.",
  "Customer says you delivered to the correct address suspiciously, as if you had been there before.",
  "Customer says delivery was too fast: there is no way this was made today. They believe it was cryogenically frozen at peak perfection last week and thawed to order. They ate 75% while investigating and now demand a full refund.",
] as const;
export const DELIVERY_ROUTE_SUCCESSES = [
  "Every sub reached the correct porch. Dispatch is checking whether you accidentally hired a competent driver.",
  "Nobody called to complain. The phone has been checked for a dial tone three times.",
  "Perfect route. One customer waved, smiled, and did not immediately request store credit. Management is shaken.",
  "All deliveries completed and only one porch goose witnessed the shortcuts. The goose can be bought.",
  "You returned with the car, the subs, and roughly the same number of mirrors you started with. Outstanding.",
  "The route was flawless. Ogdensburg has scheduled a parade pending funding, permits, and someone finding the parade.",
  "Every customer got dinner before asking where dinner was. A statistical event last recorded in 1998.",
  "You beat the quote time without cryogenically freezing anything. One customer remains suspicious.",
  "No remakes, no refunds, no deer depositions. Dispatch has framed the route sheet.",
  "The fries arrived hot. Scientists are requesting the Equinox for controlled trials.",
  "You found every address, including the house whose number was hidden behind a six-foot inflatable chicken.",
  "Route complete. The Ring cameras gave your performance four stars and one deeply invasive neighborhood montage.",
  "You delivered in Heuvelton without being trapped behind a tractor. Local historians demand your route data.",
  "You crossed the entire route without a single customer relocating their porch after ordering.",
  "All subs delivered. The mayonnaise remained geographically stable despite several North Country potholes.",
  "The customer said thank you and meant it. Management has preserved the audio in a climate-controlled vault.",
  "Perfect run through Morristown. Even the river seagulls respected your right of way.",
  "Every bag landed upright. Gravity has issued a correction and apologized for earlier routes.",
  "You returned early. Nobody believes you, but the odometer has reluctantly confirmed it.",
  "Successful Waddington run: zero livestock, zero claims, and only one aggressively judgmental lawn ornament.",
  "The last customer tipped. Dispatch briefly saw color for the first time in years.",
  "No one claimed the correct address was wrong today. Geography wins one.",
  "You survived the county roads, the unmarked driveways, and a mailbox shaped like a bass. Dinner prevailed.",
  "The delivery notes made sense. We have forwarded them to the Smithsonian as an unexplained object.",
  "Every order arrived intact. The subs would like to thank the suspension and decline further comment.",
  "The Equinox used roads for the entire route. Insurance has lowered its eyebrow by almost one millimeter.",
  "Route clear. A customer called back only to say it was good. Nobody knew which button to press.",
  "You completed the run with enough battery, dignity, and dipping sauce to return to the building.",
  "The Heuvelton tractor moved over. The driver nodded. You have peaked professionally.",
  "All deliveries successful. DPW will commemorate the occasion the next time there is a full moon and available overtime.",
] as const;
export const DELIVERY_COLLISION_FAILURES = {
  ebike: [
    "You clipped a kid on an e-bike doing 31 mph on the sidewalk, the road, and briefly a porch. He is fine. He is livestreaming. You are trending.",
    "The e-bike kid swerved into you, then asked if you were okay, then asked if you had any free subs. You had eleven. Now you have zero and a lawyer.",
    "A twelve-year-old on a 3,000-watt e-bike passed you on the right, the left, and spiritually through the middle. Insurance calls this an act of Gen Alpha.",
    "You hit an e-bike kid with no helmet, no lights, and a speaker playing music you are too old to identify. His mom has already posted on Facebook.",
  ],
  tarpcar: [
    "You hit the tarp-covered car. Nobody has seen what is under the tarp since 2011. The tarp has filed a claim on its own behalf.",
    "The blue tarp car absorbed the impact and released a family of raccoons, three hubcaps, and a 2009 Price Chopper receipt.",
    "You struck a car that is legally a car, structurally a tarp, and emotionally a family heirloom. The owner wants it 'restored to original condition.' Nobody knows the original condition.",
    "The tarp flew off. Under it was another tarp. Under that was a snowmobile. You are now in a long-term relationship with this family's attorney.",
  ],
  dog: [
    "You hit a dog. The dog is physically fine, emotionally furious, and has left a one-star review under three accounts.",
    "A dog intercepted the Equinox. Its owner arrived before the yelp finished and already had your manager on speaker.",
    "You struck the neighborhood dog. It has declined a biscuit and retained the porch goose's attorney.",
    "The dog walked away. Your route did not. Animal control has changed your contact photo to a traffic cone.",
    "The dog barked once and every porch camera on the block independently convicted you.",
    "You hit a dog named Meatball. Meatball is okay. The neighborhood Facebook group has mobilized artillery.",
    "The dog chased the Equinox, caught it, and is now listed as the registered owner.",
    "A loose lab mistook the bumper for a tennis ball. Insurance has classified the incident as fetch-related.",
    "The dog had a reflective vest, a union card, and seniority. You are the one being sent home.",
    "The customer said WATCH FOR DOG. You interpreted this as a collectible objective.",
    "The dog yelped, the owner screamed, and a Ring doorbell automatically uploaded your resignation.",
    "You clipped a dog that was crossing at a marked hydrant. The dog had right of way and excellent counsel.",
  ],
  deer: [
    "You hit a deer. It stood up, stared through your soul, and returned to the woods. Your insurance did not survive.",
    "A deer entered the road without signaling. It has witnesses, diplomatic immunity, and your front bumper.",
    "The deer collision ended the route. The deer has already told the story at a different restaurant.",
    "You found the North Country speed bump with antlers. The antlers are fine. Dispatch is not.",
    "The deer hit you, according to the deer. Its passenger deer and three woodland witnesses agree.",
    "You met a buck on Route 68. He has twelve points; you now have zero route-completion points.",
    "The deer froze in the headlights, then unfroze directly through the Corner Deli sign.",
    "You avoided the first deer. The second deer was apparently the regional manager.",
    "The antlers are lodged in a customer driveway. They want them removed and the sub remade.",
    "The deer left without exchanging insurance information. DEC says this is typical deer behavior.",
    "You struck a deer beside the WATCH FOR DEER sign. The sign would like credit for trying.",
    "The doe stood up and walked away while your front bumper requested hospice care.",
    "A deer crossed from Canada without declaring your grille at customs.",
  ],
  cow: [
    "You hit a cow outside Lisbon. The cow walked away. Your Equinox, employment, and relationship with agriculture did not.",
    "A Heuvelton cow disputed your right of way. The agricultural appeals court has ruled unanimously for the cow.",
    "You struck a cow near the county line. The cow now owns the route, the sub, and a controlling interest in the deli.",
    "That was not a large dog. It was a cow, and this distinction has become extremely expensive.",
    "The cow was in your lane because all lanes near Lisbon legally become cow lanes after dusk.",
    "You hit a Holstein. Its black-and-white pattern has been admitted as dash-cam camouflage.",
    "The cow barely moved. The Equinox has learned several new geometric shapes.",
    "A cow blocked the road and mooed. Dispatch translated it as YOUR SHIFT IS OVER.",
    "You sideswiped a dairy cow. The milk surcharge alone has exceeded the route's gross profit.",
    "The cow's ear tag contains more valid registration than the abandoned car you avoided.",
    "The herd has voted. You are no longer welcome within three silos of Heuvelton.",
    "You thought the cow would move. The cow thought the same thing about you and had more mass.",
    "The cow is unharmed and eating the delivery receipt. Accounting says that now counts as an audit.",
  ],
  person: [
    "You hit a pedestrian. They yelled OUCH; dispatch yelled several words not available in the family version.",
    "A pedestrian entered the route. The sub arrived before the ambulance, which is not the speed record we advertise.",
    "You struck a person while following the glowing address. The tutorial has been recalled nationwide.",
    "That was a person, not a bonus objective. Your route and driver's handbook have both been terminated.",
    "You hit a pedestrian carrying a sub from another restaurant. Somehow this has become a turf-war charge.",
    "The pedestrian said they were fine, then noticed the Corner Deli sign and remembered several symptoms.",
    "You followed the GPS onto a sidewalk. Google has marked the person as a temporary road closure.",
    "The pedestrian was wearing camouflage. The insurance adjuster did not accept this defense.",
    "You hit the one person in Ogdensburg who was actually using the crosswalk. Statistics have turned hostile.",
    "The person yelled OUCH, then asked whether the fries survived. This does not improve the report.",
    "You delivered the sandwich directly into a pedestrian. Dispatch says that is not contactless delivery.",
    "The pedestrian bounced. The lawsuit did not.",
  ],
  pothole: [
    "You hit a pothole deep enough to have its own Ogdensburg mailing address. The suspension is forwarding its mail.",
    "The pothole won. DPW has promoted it to assistant street superintendent.",
    "You entered the pothole with four wheels and exited with several strongly worded dashboard lights.",
    "That was not a pothole; it was an unfinished municipal basement with lane markings.",
    "The pothole contained standing water, two minnows, and a provisional Ogdensburg fishing license.",
    "You hit a pothole on State Street and briefly lost radio contact with the surface.",
    "The pothole was repaired yesterday. Yesterday has declined to provide documentation.",
    "Your front wheel entered the hole in September and is expected back after spring thaw.",
    "The pothole has expanded enough to qualify for its own school district.",
    "You drove around one pothole and into its larger, quieter spouse.",
    "The road ended without notifying the road paint. Your suspension discovered the discrepancy.",
    "DPW placed a cone beside the crater. You hit the crater, but the cone feels completely vindicated.",
    "The pothole swallowed the sub. The customer still wants to know if you can make the quoted time.",
  ],
  van: [
    "You hit a delivery van from another restaurant. The drivers exchanged menus and insurance despair.",
    "The van was double-parked with flashers on, which apparently grants diplomatic immunity.",
    "You rear-ended a white van containing seventeen unlabeled coolers. Nobody wants to complete this report.",
    "The van said FREE DELIVERY. The repair estimate has clarified what that did not include.",
    "You clipped a contractor van. Six ladders escaped and immediately formed a roadblock.",
    "The van stopped suddenly because its GPS found an address. Yours remains emotionally unavailable.",
    "You struck a parcel van. Your bumper is now scheduled for delivery between 8 AM and 9 PM.",
    "The other driver was also looking for 412 Jay Street. Neither of you found it.",
  ],
  mower: [
    "You hit an erratic lawnmower. The lawn is now striped, the Equinox is now perforated, and Hank is furious.",
    "The mower entered traffic at six miles per hour and still outmaneuvered you.",
    "You clipped a riding mower with a cup holder, headlights, and more road confidence than you.",
    "The mower launched one decorative rock through three separate layers of employment.",
    "A lawnmower crossed Main Street to finish one stripe. The stripe is perfect. Your route is not.",
    "The mower operator said they did not see you. They were driving backward while holding a sandwich.",
    "You hit a mower outside Heuvelton. The grass-cutting schedule now includes your bumper.",
    "The mower survived. Your delivery sign has been mulched into festive red confetti.",
  ],
  tent: [
    "You drove into an occupied roadside tent. Someone yelled OUCH; dispatch replaced your map with a coloring book.",
    "The tent was not a shortcut. It was housing, and your route review has become significantly more serious.",
    "You hit a tent beside the curb. The resident asked whether the sub was theirs before calling your manager.",
    "The tent collapsed, the person stood up, and your employment folded faster than both.",
    "You mistook a tent for decorative scenery. The person inside has clarified the difference at full volume.",
    "The tent had no reflective markers. It did have an occupant, witnesses, and your license plate number.",
  ],
  abandoned: [
    "You struck an abandoned car. It has not run since the 1998 ice storm, but its lawyer started immediately.",
    "DPW planned to move that car during the next full moon. You have interfered with the lunar schedule.",
    "The abandoned Buick was apparently load-bearing. Two porches and a satellite dish are now leaning.",
    "You hit a vehicle with no wheels. Its owner appeared instantly from a house three blocks away.",
    "That car had been there so long the city assessed it as waterfront property.",
    "The abandoned Impala crumbled into road salt and one aggressively valid insurance claim.",
  ],
  cat: [
    "The neighborhood cat started with nine lives and has filed paperwork showing you used six.",
    "You clipped a cat. It is fine, furious, and now sitting on the hood refusing mediation.",
    "The cat made no sound until the owner appeared. It then delivered testimony with suspicious precision.",
    "You hit a cat that absolutely had time to move and chose litigation instead.",
    "The cat survived and has become an administrator on the neighborhood Facebook page.",
    "A porch cat entered the road, stopped, and judged your braking technique in complete silence.",
  ],
  goose: [
    "A goose claimed the lane. You challenged its authority and lost the route, mirror, and appeal.",
    "The goose was unharmed. It removed your wiper blade personally.",
    "You hit a goose near the river. Forty-seven replacement geese have arrived for arbitration.",
    "The goose hissed before impact and continued hissing through the insurance interview.",
    "You attempted to intimidate a Canada goose. Canada has denied responsibility but kept the bumper.",
    "The goose crossed wherever it wanted because painted lines are a human problem.",
  ],
  raccoon: [
    "You hit a raccoon carrying half a garbage bag. It now has the sub and your registration.",
    "The raccoon rolled under the car, emerged unharmed, and stole the incident report.",
    "A raccoon entered the lane wearing what appeared to be a tiny management mask.",
    "The raccoon was inspecting a dumpster and has cited you for interrupting official business.",
    "You clipped a raccoon. Three more appeared from a storm drain to discuss compensation.",
    "The raccoon has reclassified your delivery vehicle as a mobile trash container.",
  ],
  squirrel: [
    "You tapped a squirrel. It is fine and has retained counsel on a contingency-acorn basis.",
    "The squirrel made a sound like a tire pop. You made a sound not approved for the family leaderboard.",
    "A squirrel changed lanes seven times. Your insurance still calls it an avoidable maneuver.",
    "The squirrel survived and buried your route score beside an acorn near Proctor Avenue.",
    "You hit the squirrel union steward. The oak trees have begun collective bargaining.",
    "The squirrel froze, moved, froze again, then selected exactly the square inch containing your tire.",
  ],
} as const;
export const DELIVERY_FAILURES = [
  "The neighborhood cat had nine lives. It has three left since you started driving. The cat's attorney is requesting your insurance information.",
  "Animal control asks whether you can stop hitting wildlife. This is a delivery route, not an extremely confused buffet.",
  "You hit so many squirrels that they have unionized and established a roadblock. Their demands include acorns and your immediate resignation.",
  "The deer was standing in the road illegally. Unfortunately, the deer has witnesses and you do not.",
  "You ran out of time while parked directly in front of the correct house. The customer watched the timer expire through the blinds.",
  "The delivery car is fine. The mailbox, decorative goose, recycling bin, and neighborhood association are less fine.",
  "Your route has been canceled after the GPS filed a hostile-work-environment complaint.",
  "Dispatch has reviewed the footage and would like to know why you attempted to pass a squirrel on the inside lane.",
  "The car is now shaped like a sub and the sub is shaped like an insurance claim.",
  "You have been removed from the route after describing three separate collisions as 'roadside customer engagement.'",
  "The clock expired while you were explaining to GPS that the river is not a shortcut. GPS remains unconvinced.",
  "You ran out of time behind a tractor doing twelve miles per hour and turning nowhere for eleven miles.",
  "The last customer called before the timer expired, which somehow caused the timer to expire faster.",
  "Route failed. You delivered every excuse to the correct address and none of the sandwiches.",
  "Dispatch found the car idling beside the glowing destination. You were waiting for the house to make the first move.",
  "You followed a DETOUR sign into another detour, then a third sign that simply said GOOD LUCK.",
  "The battery still has charge. The driver, route, and concept of punctuality do not.",
  "You spent six minutes looking for a house number hidden behind a decorative wagon wheel. The wagon wheel won.",
  "The customer called to ask where you were. You were in their driveway, but they rejected this evidence.",
  "You arrived after the quoted time because Ogdensburg added a pothole after the route was calculated.",
  "The bridge went up. There was no ship. Officials describe this as a confidence-building exercise.",
  "A train blocked the route long enough for the hot sub to complete a full cooling cycle and apply for retirement.",
  "You made excellent time to the wrong county. The GPS has awarded itself five stars.",
  "The route ended after three missed houses and one successful delivery to a shed containing no people.",
  "You stopped to read an address and the entire neighborhood renumbered itself out of spite.",
  "Time expired at a four-way stop where every driver kept waving everyone else through. They remain there.",
  "You reached the final porch with one second left. The customer required seventeen seconds to open the storm door.",
  "The sub is still hot, the address is correct, and the route has failed for reasons management calls 'the overall vibe.'",
  "You ran out of time after circling a block whose streets all become one-way only when you enter them.",
  "Dispatch says the route was mathematically possible. Mathematics was not driving through Heuvelton at dinner time.",
] as const;
