// The Corner Deli Facebook page parody: fictional people, their posts,
// comment threads and the deli's replies. Every name here is made up.
// Templates: {item} {address} fill from the order; {author} is whoever wrote
// the post; {prev} is the person who commented just above.

export const FB_PEOPLE = [
  "Brenda K.", "Dale (Not That Dale)", "Concerned Ogdensburg Resident", "Tammy Lynn R.",
  "Gary From The Corner", "Deb S.", "Ron 'The Mayor' P.", "Kayleigh M.", "Big Steve",
  "Linda (Admin of 4 Groups)", "Chet W.", "Marge T.", "Bev Ouellette-ish", "Skip D.",
  "Sharon From Bingo", "Donnie Two Trucks", "Carol A.", "Rick (Snowplow Rick)",
  "Patti J.", "Teddy B.", "Ashleigh-Lynn K.", "Uncle Moe", "Sue Ellen F.", "Jimbo L.",
  "Wanda P.", "Larry (Retired)", "Tina With Two N's", "Kevin Who Works Nights",
  "Mrs. Lafleur", "Nana Dot", "Chad (Canadian Side)", "Becky From Lisbon",
  "Heuvelton Hank", "Morristown Mike", "Denise R.", "Pastor Gene", "Crystal M.",
  "Bud (Bowl Regular)", "Shirley With The Goose", "Mike Who Fixes Phones",
  "Roxanne T.", "Earl G.", "Jolene P.", "Frank 'Franky Fries' D.", "Mandy B.",
] as const;

/** Posted even when the sub landed perfectly. */
export const FB_DELIVERED = [
  "My {item} arrived at {address} hot, on time, and correct. I have never been so suspicious in my life. Who is running this deli and what do they want.",
  "Driver threw my {item} onto the porch. It landed perfectly. Too perfectly. I watched the Ring footage 40 times and I believe he has done this before. 2 stars.",
  "Ordered a {item}. Received a {item}. Where is the surprise? Where is the adventure? Ogdensburg used to have spirit.",
  "The {item} came in a bag. I did not consent to a bag.",
  "Delivery was so fast I had not finished complaining about the wait yet. Now I have to complain about this instead.",
  "Driver did not wave. Driver was going 30 mph and throwing a sandwich. Still. Would have been nice.",
  "I asked for the sub to be left at the side door. It was left at the side door. The side door is not where I am. 1 star.",
  "{item} was excellent. Unfortunately I ordered it for my husband and he loved it, so now he is insufferable.",
  "The sub landed on my welcome mat, which says WELCOME, so technically I invited it. I'd like to rescind that.",
  "Sub was great. The bread was so soft I worried about it. Is the bread okay. Is anyone checking on the bread.",
  "Arrived at {address} in under 20 minutes. My dog was not ready. My dog has never been ready.",
  "Tossed my {item} from a moving vehicle like a newspaper in a 1985 arcade game. Honestly the best thing that's happened on this street since the parade.",
  "My order arrived correctly and the receipt was stapled straight. Who is training these people. It's unsettling.",
  "I tipped in the app and the driver still threw it. I would like to know what tipping is FOR.",
  "Not a complaint, just want everyone to know I got a {item} and you didn't. Anyway 3 stars.",
  "Five stars for the food. One star because the delivery car is louder than my thoughts.",
  "The {item} landed on my porch. My porch is on the second floor. I need to know how.",
  "Found a HAIR in my {item}. The cook is bald. The driver is bald. I have a chunk missing from the back of my head but that is unrelated and I resent the implication.",
  "Got diarrhea after my {item}. Unrelated: I was at The Bowl till close doing tequila shots. Still blaming the sub.",
  "Called to say nothing was wrong with my {item}. Still think they're idiots. Just wanted it on record.",
  "Food arrived too fast. I wasn't wearing pants. Now the driver knows things.",
  "Asked for my {item} pre-chewed. They said no. In this economy?",
  "The pickle was looking at me. I'm not saying it was alive. I'm saying it was looking at me.",
  "Got my {item} in 18 minutes. My last relationship lasted 14. I'm not ready to be this happy.",
  "They put mayo on it like I asked. I did not ask. I checked the receipt and I did ask. Leaving the review up anyway.",
  "The driver complimented my wreath. It's October. I don't have a wreath. Whose wreath did he see.",
  "Sub was hot. I ordered a cold sub. Then it got cold. Then I wanted it hot. Nobody at this deli thinks ahead.",
  "The bag was knotted so well I had to use the good scissors. My wife uses the good scissors for fabric only. My marriage is in trouble and the sub was great.",
  "The driver said 'enjoy' like he knew something. I didn't enjoy it. I mean I did. But I didn't want to.",
  "There was too much meat in my {item}. I had to eat it all. I have a doctor's appointment Thursday and I'll be bringing this up.",
  "I ordered extra onions. They gave me extra onions. Now my car smells like extra onions. Should've warned me.",
  "Delivered right to the porch. Problem is I was on the porch. The sub hit me. Still ate it. 2 stars.",
  "They spelled my name right on the bag. I didn't give them my name. 5 stars but I'm sleeping with the lights on.",
  "Got a free cookie I didn't ask for. Now I have to eat a cookie. Some of us are trying.",
  "Perfectly fine sub. Wanted to leave a review anyway so the page knows I'm watching.",
  "The {item} was so good my cat tried to unlock the fridge. The cat has never done that. I'm holding the deli responsible.",
  "Sub arrived wrapped tighter than my mother-in-law's perm. Took me 9 minutes to open. Ate it in 2. Fair trade? No.",
  "Driver parked in front of MY mailbox to deliver to MY house. Ask permission next time.",
  "The fries were in a separate bag. Why are my fries being segregated.",
  "Asked for no tomato. There was no tomato. Now I'm craving tomato. This is on you.",
  "My {item} was cut into two halves. I live alone. Who is the other half for. Answer me.",
  "Driver got here before my husband got home from work and my husband works across the street. Something's going on.",
] as const;

/** Posted by the houses the driver missed. */
export const FB_MISSED = [
  "Ordered a {item} to {address} 45 minutes ago. Just watched the Corner Deli car drive past my house AT SPEED, holding my sub, making eye contact.",
  "Still waiting on my {item}. I can see it from my window. It's in the neighbor's hedge. Do I go get it? Is that legal?",
  "Driver blew right past {address}. Didn't even slow down. I'm not mad, I'm just going to post about it in five groups.",
  "My {item} never came. I'm sitting on the porch in a lawn chair like it's 1962 and I'm waiting for a ship.",
  "The car went by so fast my wind chimes are still going. No sub though. Just chimes.",
  "No {item}. Called the deli. They said the driver 'saw a goose.' We all saw a goose. We have been seeing that goose for three years.",
  "Waited an hour. Then I made a sandwich. Then I ate it angrily. Then I wrote this. Then I made another sandwich.",
  "Watched my dinner go by on the tracking map like a satellite I could not reach.",
  "My mailbox flag was UP. The flag is the universal symbol for 'my sub goes here.' Read a book.",
  "The driver waved at me. While not stopping. While holding my {item}. That's not a wave, that's a taunt.",
  "My kids stood at the window for twenty minutes like it was Christmas Eve. Santa skipped us. Santa drives an Equinox.",
  "Still no {item} at {address}. If anyone on Proctor got an extra one, that's mine, I can tell by looking.",
  "Called to ask where my order was. The girl said 'on the way.' On the way where. To Canada?",
  "The car slowed down at my house, considered it, and kept going. I have never felt so judged by a vehicle.",
  "No sub. My dog has been sitting by the door since 5:30. He is not okay. Neither am I.",
  "My order went to the house next door. The house next door is vacant. A raccoon is eating my {item}. I can see him. He's enjoying it.",
  "Missed delivery. I'd complain more but I'm too hungry to type. 1 star. Typing hurts.",
  "Corner Deli car went past my house twice and neither time did it involve my food. Is this a game to you?",
] as const;

/** Posted by houses that never ordered but got a sub anyway. */
export const FB_SAMPLES = [
  "A sandwich hit my porch tonight and I did not order it. Best sub of my life. 1 star because I feel like I'm being recruited.",
  "Someone threw a free sub at my house. I've been in the North Country 58 years and I know a bribe when I see one. It worked though.",
  "Is anyone else getting unsolicited subs?? Mine was a {item}. I want to know who's getting the steak ones.",
  "Free {item} landed on my lawn. Called the deli to report it. They asked if I wanted to order a drink with that. Bold.",
  "I don't live here, I'm house-sitting, and the house got a sub. Does the sub count as part of the house. Asking for legal reasons.",
  "Unordered sub on my steps. My Ring camera caught it all. Uploading in 4K, slow motion, with dramatic music.",
  "Got a mystery {item} on my porch. Ate it. Didn't order it. Didn't pay. Still feel like I owe somebody money.",
  "Sub came flying out of nowhere and landed on my patio chair. My husband thinks it's a sign. He's ordering every night now.",
  "A free sandwich showed up and my mother says it's a scam. My mother has never been offered a sandwich in a scam.",
  "Found a {item} on my porch with no note. Called the police non-emergency line. They asked if I was going to eat it. I was.",
  "Somebody yeeted a free sub at my house during Jeopardy. Missed Final Jeopardy. Gained a sub. Net positive.",
  "If the Corner Deli is giving away free subs on my street I need to know the schedule because I will be on the porch.",
] as const;

/** For a shift where every single order landed. */
export const FB_PERFECT = [
  "Every house on my street got their order tonight and nobody's complaining. I don't trust it. Something is coming.",
  "Whole block got fed on time. Linda from the group says it's a scam. Linda has not said what the scam is.",
  "Corner Deli delivered to every house on the street. Even the house that's just a garage. The garage is thrilled.",
  "Flawless route tonight. The deer are regrouping. Mark my words.",
  "Every porch on the block got a sub tonight. Looked like a parade, if the parade threw sandwiches at you. Better than the actual parade.",
  "Not one missed delivery on our street. My wife says I'm not allowed to complain about this. I'm complaining about not being allowed.",
  "Driver hit every porch tonight. EVERY porch. Somebody check on him, that's not normal behavior.",
  "Perfect delivery night on our street. Enjoy it. Next week a goose will be in charge.",
] as const;

/** Comments under a post. */
export const FB_COMMENTS = [
  "Mine was perfect too. Disgusting.",
  "this is why I only order from the deli in person and then stand in the kitchen",
  "{author} you need to let it go, it's been since 2019",
  "Did anyone else see the goose",
  "My cousin's friend drives for them and says the subs are 'aerodynamically wrapped.' Make of that what you will.",
  "Following",
  "I had the Big Boss Sub and lost the ability to speak for 20 minutes. In a good way.",
  "{author} that's not even your street",
  "Shared to Ogdensburg Rants & Raves (Unfiltered) (No Politics) (Some Politics)",
  "The cow on River Rd has seen things.",
  "I don't understand the problem. You got a sub. Celebrate.",
  "Every time the delivery car goes by my dog thinks it's his birthday",
  "This is why my grandfather walked to the deli. Uphill. In the snow. Both directions.",
  "Not to brag but mine hit my mailbox and the flag went up",
  "Can confirm, I am the neighbor, the sub was delicious",
  "{author} please stop tagging me in these",
  "{author} did you call them or just post here",
  "{author} is this the same thing you posted about the Dollar General",
  "{author} my cousin works there and says you tip in quarters",
  "Is this the same {author} who complained about the fireworks being too colorful",
  "{author} same thing happened to me except it was great and I'm still mad",
  "{author} screenshotting this for the group",
  "{author} we all saw your car at The Bowl last night, sit down",
  "{author} you okay hun? DM me",
  "{author} this is the third post this week, are you their landlord",
  "{prev} nobody asked",
  "{prev} this you?",
  "{prev} I wasn't talking to you but you're right",
  "{prev} preach",
  "{prev} my thoughts exactly but louder",
  "{prev} you said the same thing about the bridge",
  "{prev} isn't that your sister's house",
  "Who is this deli and why does my whole feed smell like Italian dressing now",
  "I'd like to file a complaint about this complaint",
  "First time I ever agreed with a Facebook post. Feels weird.",
  "Corner Deli has been doing this since before your mom was born and she'd tell you the same thing",
  "I'm just here for the comments",
  "Where's the original post, I want to see the porch",
  "Do they deliver to Heuvelton because I would like to be complained at too",
  "Watching this thread instead of the Bills game. Better offense.",
  "It's a sandwich, Brenda. Oh wait wrong thread.",
  "Someone tell Gary it's not 1994 anymore",
  "I ordered the same thing and got the same thing and I'm thrilled. Is that allowed here?",
  "Bring back the pierogi special",
  "My uncle says they put love in the subs. My uncle is not well.",
  "Can we get a mod in here",
  "Commenting so I get notifications when this gets good",
  "The real question is who's throwing the subs. I'd like to hire him for my wedding.",
  "Ring camera footage or it didn't happen",
  "Honestly the driver deserves a raise for dealing with this street",
  "Has anyone tried NOT complaining? Asking for the town.",
  "This is the most Ogdensburg thing I've ever read and I watched the bridge get painted",
] as const;

/** The deli's deadpan replies, addressed to the person who posted. */
// The deli's replies, by what the post was about, so an answer always fits
// the complaint it's under. Each one is addressed to the post's author.
const ANY_REPLY = [
  "Thank you for your feedback, {author}. We have forwarded it to the driver, who read it at 30 mph.",
  "{author}, the goose has been spoken to.",
  "{author}, your complaint has been laminated and hung by the register.",
  "{author}, we've named a sub after you. It's the one with the most complaints.",
  "{author}, thanks for the feedback! We've passed it along to management, who is also the cook, who is also bald.",
  "{author}, we appreciate every review. Even this one. Especially this one. It's on the fridge.",
  "{author}, a free cookie is not a threat. It's a cookie.",
  "Hi {author}, the deer has been unavailable for comment.",
] as const;
export const FB_REPLIES = {
  delivered: [
    ...ANY_REPLY,
    "{author}, we're so sorry the sandwich was correct. We'll look into it.",
    "{author}, we appreciate you! Please don't stand in the kitchen.",
    "We hear you, {author}. We are also scared of how good the bread is.",
    "{author}, we cannot pre-chew. We tried once. HR got involved.",
    "{author}, nothing was wrong, which we've noted in your file next to the word 'idiots.'",
    "{author}, our cook is bald. Our driver is bald. We've started a hair investigation.",
    "{author}, The Bowl called. They'd like their tequila back.",
    "Thank you {author}! We've added 'too fast' to our list of things to work on, right under 'too good.'",
    "{author}, we're so glad you enjoyed it. We're also sorry. Both are true.",
    "{author}, we'll be sure to make it worse next time.",
    "{author}, the pickle has been reassigned.",
    "{author}, we're working on a 'slower but sadder' delivery option. Stay tuned.",
    "{author}, we checked, and yes, the bag was in fact a bag.",
    "{author}, come in tomorrow and we'll do it all again, exactly the same, on purpose.",
    "{author}, the driver says the porch was 'right there' and 'begging for it.'",
  ],
  missed: [
    ...ANY_REPLY,
    "Our drivers are trained to deliver to the porch, {author}. The porch moved. We're working with the porch.",
    "Thanks for reaching out, {author}! Your sub is in the hedge. It is still a good sub.",
    "{author}, please DM us your address so we can deliver an apology sub at a more reasonable velocity.",
    "{author}, the sub you saw go by was someone else's. Yours is still being made with love and mild panic.",
    "{author}, we're sorry for your loss. Of patience.",
    "{author}, the driver says he waved. He says that counts as a delivery in Canada.",
    "{author}, your sub is safe. It is on a tour of the North Country and will return a changed sandwich.",
    "{author}, we've checked the map. Your house is there. The driver disagrees. We're mediating.",
    "{author}, a replacement sub is on the way. Please stand on the porch and wave something bright.",
    "{author}, the driver says there was a goose. There is always a goose.",
  ],
  sample: [
    ...ANY_REPLY,
    "{author}, that was a free sample. You're welcome. Please stop calling it 'an attack.'",
    "{author}, we've reviewed the footage. The sub was fine. You were the one who dropped it.",
    "{author}, the driver says hi. He also says duck next time.",
    "{author}, we have no idea how it got on the second floor either.",
    "{author}, free food is a gift. Being hit by free food is a bigger gift.",
    "{author}, our marketing department is one guy in a car with a strong arm. We stand by him.",
    "{author}, you can't 'return to sender' a sub. We checked with the post office.",
  ],
} as const;
export type FbReplyKind = keyof typeof FB_REPLIES;
