import {createHash,randomBytes,randomUUID} from "node:crypto";
import {getSql} from "@/lib/db";
import {DELIVERY_PRIZE,DELIVERY_STAGES} from "./config";
let schema:Promise<void>|null=null;
const digest=(s:string)=>createHash("sha256").update(s).digest("hex");
export function ensureDeliverySchema(){if(!schema)schema=(async()=>{const sql=getSql();await sql`CREATE TABLE IF NOT EXISTS delivery_boy_runs(id UUID PRIMARY KEY,token_hash TEXT NOT NULL,player_name TEXT NOT NULL DEFAULT 'Anonymous Driver',status TEXT NOT NULL DEFAULT 'active',stage INTEGER NOT NULL DEFAULT 1,sequence INTEGER NOT NULL DEFAULT 0,active_seconds INTEGER NOT NULL DEFAULT 0,score INTEGER NOT NULL DEFAULT 0,delivered INTEGER NOT NULL DEFAULT 0,missed INTEGER NOT NULL DEFAULT 0,hits INTEGER NOT NULL DEFAULT 0,checkpoints JSONB NOT NULL DEFAULT '[]'::jsonb,started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),completed_at TIMESTAMPTZ)`;await sql`CREATE TABLE IF NOT EXISTS delivery_boy_rewards(id UUID PRIMARY KEY,run_id UUID NOT NULL UNIQUE REFERENCES delivery_boy_runs(id),code TEXT NOT NULL UNIQUE,prize_type TEXT NOT NULL,terms JSONB NOT NULL,completion_stats JSONB NOT NULL,issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),expires_at TIMESTAMPTZ,redeemed_at TIMESTAMPTZ,redeemed_by TEXT,redemption_note TEXT NOT NULL DEFAULT '')`;})();return schema}
export async function startDeliveryRun(name:string){await ensureDeliverySchema();const id=randomUUID(),token=randomBytes(32).toString("base64url");await getSql()`INSERT INTO delivery_boy_runs(id,token_hash,player_name)VALUES(${id},${digest(token)},${name.trim().slice(0,40)||"Anonymous Driver"})`;return{runId:id,token}}
async function auth(id:string,token:string){await ensureDeliverySchema();return(await getSql()`SELECT * FROM delivery_boy_runs WHERE id=${id} AND token_hash=${digest(token)} LIMIT 1`)[0]||null}
export async function checkpointDelivery(body:any,token:string){const run=await auth(String(body.runId),token);if(!run||run.status!=="active")throw new Error("Run is unavailable.");const stage=Number(body.stage),sequence=Number(body.sequence),active=Number(body.activeSeconds),score=Number(body.score),delivered=Number(body.delivered),missed=Number(body.missed),hits=Number(body.hits);if(sequence!==Number(run.sequence)+1||stage<Number(run.stage)||stage>Number(run.stage)+1||stage>DELIVERY_STAGES.length)throw new Error("Impossible route progression.");if(active<Number(run.active_seconds)||active-Number(run.active_seconds)>900||score<Number(run.score)||delivered<Number(run.delivered)||delivered-Number(run.delivered)>20||hits<Number(run.hits)||missed<Number(run.missed))throw new Error("Invalid route checkpoint.");const entry={at:new Date().toISOString(),stage,sequence,active,score,delivered,missed,hits};await getSql()`UPDATE delivery_boy_runs SET stage=${stage},sequence=${sequence},active_seconds=${active},score=${score},delivered=${delivered},missed=${missed},hits=${hits},checkpoints=checkpoints||${JSON.stringify([entry])}::jsonb,updated_at=NOW() WHERE id=${body.runId}`;return{ok:true}}
export async function completeDeliveryRun(id:string,token:string){const run=await auth(id,token);if(!run)throw new Error("Run credentials are invalid.");if(run.status==="won")return(await getSql()`SELECT code,prize_type,issued_at,expires_at FROM delivery_boy_rewards WHERE run_id=${id}`)[0];if(Number(run.stage)!==DELIVERY_STAGES.length||Number(run.delivered)<DELIVERY_STAGES.reduce((n,s)=>n+s.deliveries,0)||Number(run.sequence)<DELIVERY_STAGES.length)throw new Error("The full route is not complete.");const code=`SUB-${randomBytes(2).toString("hex").toUpperCase()}-${randomBytes(2).toString("hex").toUpperCase()}`,expires=new Date(Date.now()+DELIVERY_PRIZE.expiresDays*86400000).toISOString(),stats={score:run.score,delivered:run.delivered,missed:run.missed,hits:run.hits,activeSeconds:run.active_seconds};await getSql()`UPDATE delivery_boy_runs SET status='won',completed_at=NOW(),updated_at=NOW() WHERE id=${id}`;return(await getSql()`INSERT INTO delivery_boy_rewards(id,run_id,code,prize_type,terms,completion_stats,expires_at)VALUES(${randomUUID()},${id},${code},${DELIVERY_PRIZE.name},${JSON.stringify(DELIVERY_PRIZE)}::jsonb,${JSON.stringify(stats)}::jsonb,${expires}) RETURNING code,prize_type,expires_at`)[0]}
export async function findDeliveryRewards(query:string){await ensureDeliverySchema();const q=`%${query.trim()}%`;return getSql()`SELECT reward.*,run.player_name,run.active_seconds FROM delivery_boy_rewards reward JOIN delivery_boy_runs run ON run.id=reward.run_id WHERE ${query.trim()===""} OR reward.code ILIKE ${q} OR run.player_name ILIKE ${q} ORDER BY reward.issued_at DESC LIMIT 50`}
export async function redeemDeliveryReward(code:string,actor:string){await ensureDeliverySchema();const rows=await getSql()`UPDATE delivery_boy_rewards SET redeemed_at=NOW(),redeemed_by=${actor} WHERE code=${code.trim().toUpperCase()} AND redeemed_at IS NULL AND(expires_at IS NULL OR expires_at>NOW()) RETURNING *`;if(!rows[0])throw new Error("Code is invalid, expired, or already redeemed.");return rows[0]}
