"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {DELIVERY_COMPLAINTS,DELIVERY_PRIZE,DELIVERY_STAGES} from "@/lib/delivery-boy/config";
type Thing={id:number,type:"deer"|"dog"|"squirrel"|"car"|"pothole"|"boost";lane:number;y:number};
type Run={runId:string;token:string};
type Stats={score:number;delivered:number;missed:number;hits:number;combo:number;bestCombo:number};
const fresh:Stats={score:0,delivered:0,missed:0,hits:0,combo:0,bestCombo:0};
const icons:Record<Thing["type"],string>={deer:"🦌",dog:"🐕",squirrel:"🐿️",car:"🚗",pothole:"◉",boost:"⚡"};
const quips=["SUB SECURED","PORCH PERFECT","YEET DELIVERY","BREAD HAS LANDED","DINNER DEPLOYED","ABSOLUTELY DELIVERED"];
declare global{interface Window{webkitAudioContext?:typeof AudioContext}}
export default function DeliveryGame(){
 const [mode,setMode]=useState<"home"|"play"|"between"|"won"|"lost">("home"),[name,setName]=useState(""),[stage,setStage]=useState(1),[lane,setLane]=useState(1),[things,setThings]=useState<Thing[]>([]),[target,setTarget]=useState({y:-20,side:"left" as "left"|"right",active:false}),[routeDelivered,setRouteDelivered]=useState(0),[time,setTime]=useState(70),[health,setHealth]=useState(3),[stats,setStats]=useState(fresh),[toast,setToast]=useState(""),[complaint,setComplaint]=useState(""),[run,setRun]=useState<Run|null>(null),[sequence,setSequence]=useState(0),[reward,setReward]=useState<any>(null),[muted,setMuted]=useState(false),[boost,setBoost]=useState(0);
 const keys=useRef(new Set<string>()),last=useRef(0),spawn=useRef(0),deliveryGap=useRef(0),playerLane=useRef(1),state=useRef({mode:"home",time:70,health:3,stage:1,target:{y:-20,side:"left" as "left"|"right",active:false}}),audio=useRef<{ctx:AudioContext;gain:GainNode;timer:number;step:number}|null>(null),touch=useRef(0);
 const cfg=DELIVERY_STAGES[stage-1];
 useEffect(()=>{state.current={mode,time,health,stage,target}},[mode,time,health,stage,target]);
 useEffect(()=>{playerLane.current=lane},[lane]);
 const beep=useCallback((kind:"throw"|"hit"|"coin"|"start")=>{if(muted)return;const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const c=new A(),o=c.createOscillator(),g=c.createGain();o.type=kind==="hit"?"sawtooth":"square";o.frequency.setValueAtTime(kind==="coin"?900:kind==="throw"?440:kind==="start"?330:100,c.currentTime);o.frequency.exponentialRampToValueAtTime(kind==="hit"?45:kind==="coin"?1500:660,c.currentTime+.14);g.gain.setValueAtTime(.06,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.18);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+.2)},[muted]);
 function soundtrack(){if(audio.current)return;const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const ctx=new A(),gain=ctx.createGain();gain.gain.value=muted?0:.045;gain.connect(ctx.destination);const melody=[261.6,329.6,392,523.2,392,329.6,293.7,440,349.2,293.7,261.6,392],bass=[130.8,130.8,146.8,110];const s={ctx,gain,timer:0,step:0};s.timer=window.setInterval(()=>{const now=ctx.currentTime,urgent=Math.max(0,(20-state.current.time)/20),freq=melody[s.step%melody.length],o=ctx.createOscillator(),v=ctx.createGain();o.type=s.step%3?"square":"triangle";o.frequency.value=freq;v.gain.setValueAtTime(.42,now);v.gain.exponentialRampToValueAtTime(.001,now+.11);o.connect(v);v.connect(gain);o.start();o.stop(now+.12);if(s.step%3===0){const b=ctx.createOscillator(),bg=ctx.createGain();b.type="square";b.frequency.value=bass[Math.floor(s.step/3)%bass.length];bg.gain.setValueAtTime(.25,now);bg.gain.exponentialRampToValueAtTime(.001,now+.12);b.connect(bg);bg.connect(gain);b.start();b.stop(now+.13)}s.step++;if(urgent>.5)o.detune.value=(s.step%2)*100},135);audio.current=s}
 useEffect(()=>{if(audio.current)audio.current.gain.gain.setTargetAtTime(muted?0:.045,audio.current.ctx.currentTime,.05)},[muted]);
 useEffect(()=>()=>{if(audio.current){clearInterval(audio.current.timer);void audio.current.ctx.close()}},[]);
 function pop(message:string){setToast(message);window.setTimeout(()=>setToast(""),850)}
 const move=useCallback((d:number)=>setLane(v=>Math.max(0,Math.min(2,v+d))),[]);
 const deliver=useCallback(()=>{const t=state.current.target;if(state.current.mode!=="play"||!t.active)return;const sweet=t.y>=60&&t.y<=86;if(sweet){const perfect=t.y>=70&&t.y<=79;setTarget(x=>({...x,active:false}));setRouteDelivered(n=>n+1);setStats(s=>{const combo=s.combo+1,score=s.score+(perfect?1000:600)*Math.min(5,1+combo*.1);return{...s,delivered:s.delivered+1,combo,bestCombo:Math.max(s.bestCombo,combo),score:Math.round(score)}});pop(perfect?quips[Math.floor(Math.random()*quips.length)]:"DELIVERED-ish");beep("throw")}else{setStats(s=>({...s,score:Math.max(0,s.score-100),combo:0}));pop(t.y<60?"TOO EARLY! SUB IN SHRUB":"MISSED THE HOUSE!");beep("hit")}},[beep]);
 useEffect(()=>{const down=(e:KeyboardEvent)=>{keys.current.add(e.key);if(["ArrowLeft","a","A"].includes(e.key))move(-1);if(["ArrowRight","d","D"].includes(e.key))move(1);if([" ","Enter"].includes(e.key)){e.preventDefault();deliver()}};const up=(e:KeyboardEvent)=>keys.current.delete(e.key);window.addEventListener("keydown",down);window.addEventListener("keyup",up);return()=>{window.removeEventListener("keydown",down);window.removeEventListener("keyup",up)}},[deliver,move]);
 useEffect(()=>{if(mode!=="play")return;let raf=0;last.current=performance.now();const loop=(now:number)=>{const dt=Math.min(.04,(now-last.current)/1000);last.current=now;spawn.current+=dt;deliveryGap.current+=dt;const speed=(DELIVERY_STAGES[state.current.stage-1].speed+(boost>0?65:0))/100;if(spawn.current>Math.max(.36,1.05-state.current.stage*.09)){spawn.current=0;const types:Thing["type"][]=["deer","dog","squirrel","car","pothole","boost"],type=types[Math.random()<.12?5:Math.floor(Math.random()*5)];setThings(a=>[...a,{id:Date.now()+Math.random(),type,lane:Math.floor(Math.random()*3),y:-12}])}if(deliveryGap.current>Math.max(2.8,4.4-state.current.stage*.25)&&!state.current.target.active){deliveryGap.current=0;setTarget({y:-14,side:Math.random()>.5?"right":"left",active:true})}setThings(a=>{const next:Thing[]=[];for(const x of a){const n={...x,y:x.y+dt*speed*36};if(n.y>78&&n.y<91&&n.lane===playerLane.current){if(n.type==="boost"){setBoost(4);setStats(s=>({...s,score:s.score+350}));pop("TURBO PICKLE! +350");beep("coin");continue}setHealth(h=>Math.max(0,h-1));setStats(s=>({...s,hits:s.hits+1,combo:0}));pop(n.type==="deer"?"YOU HIT A DEER. THE DEER IS ANGRY.":`${n.type.toUpperCase()} INCIDENT!`);beep("hit");continue}if(n.y<112)next.push(n)}return next});setTarget(t=>{if(!t.active)return t;const y=t.y+dt*speed*28;if(y>108){setStats(s=>({...s,missed:s.missed+1,combo:0}));pop("CUSTOMER ALREADY CALLED");return{...t,y,active:false}}return{...t,y}});raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf)},[mode,boost,beep]);
 useEffect(()=>{if(mode!=="play")return;const id=setInterval(()=>{setTime(t=>Math.max(0,t-1));setBoost(b=>Math.max(0,b-1))},1000);return()=>clearInterval(id)},[mode]);
 useEffect(()=>{if(mode==="play"&&(health<=0||time<=0)){setMode("lost");beep("hit")}},[mode,health,time,beep]);
 useEffect(()=>{if(mode!=="play"||routeDelivered<cfg.deliveries)return;void finishRoute()},[routeDelivered,mode,cfg.deliveries]);
 async function start(){soundtrack();beep("start");const r=await fetch("/api/delivery-boy/run",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"start",playerName:name})}),d=await r.json();if(!r.ok){pop(d.error||"Could not start route");return}setRun(d);begin(1)}
 function begin(n:number){setStage(n);setRouteDelivered(0);setHealth(3);setTime(DELIVERY_STAGES[n-1].time);setThings([]);setTarget({y:-20,side:"left",active:false});setMode("play")}
 async function finishRoute(){setMode("between");const nextSeq=sequence+1,checkpoint={runId:run?.runId,stage,sequence:nextSeq,activeSeconds:DELIVERY_STAGES.slice(0,stage).reduce((n,s)=>n+s.time,0)-time,score:stats.score,delivered:stats.delivered,missed:stats.missed,hits:stats.hits};if(run){const r=await fetch("/api/delivery-boy/run",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"checkpoint",token:run.token,checkpoint})});if(r.ok)setSequence(nextSeq)}if(Math.random()<.72)setComplaint(DELIVERY_COMPLAINTS[Math.floor(Math.random()*DELIVERY_COMPLAINTS.length)])}
 async function nextRoute(){setComplaint("");if(stage<DELIVERY_STAGES.length){begin(stage+1);return}if(!run)return;const r=await fetch("/api/delivery-boy/run",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"complete",runId:run.runId,token:run.token})}),d=await r.json();setReward(d);setMode(r.ok?"won":"lost")}
 function touchEnd(e:React.TouchEvent){const dx=e.changedTouches[0].clientX-touch.current;if(Math.abs(dx)>35)move(dx>0?1:-1)}
 return <main className="delivery-boy">
  {mode==="home"&&<section className="delivery-home"><div className="delivery-brand">CORNER DELI PRESENTS</div><h1>CORNER<br/><i>DELIVERY BOY</i></h1><div className="van-hero">🥪<span>🚗</span><b>💨</b></div><p>Deliver subs. Dodge wildlife. Survive customer logic.</p><input value={name} onChange={e=>setName(e.target.value)} placeholder="Driver name"/><button onClick={start}>START THE CAR</button><small>← → or swipe to steer · SPACE or DELIVER to throw</small><div className="sub-prize">WIN: {DELIVERY_PRIZE.name.toUpperCase()}</div></section>}
  {mode==="play"&&<><header className="delivery-hud"><div><small>ROUTE {stage}</small><b>{cfg.name}</b></div><div><small>DELIVERED</small><b>{routeDelivered}/{cfg.deliveries}</b></div><div className={time<16?"hot":""}><small>TIME</small><b>{time}</b></div><div><small>SCORE</small><b>{stats.score}</b></div><div><small>COMBO</small><b>{stats.combo}×</b></div><button onClick={()=>setMuted(!muted)}>{muted?"🔇":"🔊"}</button></header><section className={`delivery-world ${time<16?"panic":""}`} onTouchStart={e=>touch.current=e.touches[0].clientX} onTouchEnd={touchEnd}>
   <div className="sky"><span>🏪</span><i>ROUTE {stage}</i></div><div className="road"><div className="lane-lines"/><div className="speed-lines"/>{target.active&&<div className={`house ${target.side} ${target.y>=60&&target.y<=86?"in-range":""}`} style={{top:`${target.y}%`}}><span>🏠</span><b>{target.y>=60&&target.y<=86?"DELIVER NOW!":"ORDER"}</b></div>}{things.map(x=><i className={`hazard ${x.type}`} key={x.id} style={{left:`${16.66+x.lane*33.33}%`,top:`${x.y}%`}}>{icons[x.type]}</i>)}<div className={`driver lane-${lane} ${boost?"boost":""}`}><span>🚙</span><b>🥪</b></div></div>{toast&&<div className="delivery-toast">{toast}</div>}<div className="hearts">{"❤️".repeat(health)}{"🖤".repeat(3-health)}</div><div className="touch-controls"><button onPointerDown={()=>move(-1)}>◀</button><button className="deliver" onPointerDown={deliver}>THROW SUB</button><button onPointerDown={()=>move(1)}>▶</button></div></section></>}
  {mode==="between"&&<section className="delivery-summary"><small>ROUTE {stage} CLEAR</small><h1>{complaint?"CUSTOMER FEEDBACK":"MIRACLE: NO COMPLAINT"}</h1><div className="complaint-card">{complaint||"Everything was great. This event has a 0.0004% historical occurrence rate."}</div><div className="route-stats"><b>{stats.score}<small>SCORE</small></b><b>{stats.delivered}<small>DELIVERED</small></b><b>{stats.hits}<small>ANIMAL/OBJECT INCIDENTS</small></b></div><button onClick={nextRoute}>{stage===DELIVERY_STAGES.length?"CLAIM FREE SUB":"NEXT ROUTE →"}</button></section>}
  {mode==="lost"&&<section className="delivery-summary"><h1>ROUTE FAILED</h1><div className="complaint-card">{reward?.error||"The subs survived. Your dignity did not."}</div><button onClick={()=>location.reload()}>DRIVE AGAIN</button></section>}
  {mode==="won"&&<section className="delivery-summary win"><small>YOU SURVIVED THE ROUTE</small><h1>FREE SUB EARNED</h1><div className="reward-code">{reward?.code}</div><p>{DELIVERY_PRIZE.terms}</p></section>}
 </main>
}
