#!/usr/bin/env node
import{randomUUID}from"node:crypto";import{localValidationEnv}from"./validation-env";localValidationEnv();
const ROLLBACK="rollback:barcode-validation";
async function main(){const{getSql,withTransaction}=await import("../src/lib/db");const{ensureOrderingBarcodeSchema}=await import("../src/lib/ordering-barcode-schema");const{identifyBarcodeFormat,resolveBarcode,saveBarcodeMapping}=await import("../src/lib/ordering-barcodes");const{KeyboardWedgeDetector,isHumanTextEntry}=await import("../src/lib/barcode-scanner");await ensureOrderingBarcodeSchema();const result:Record<string,boolean>={};try{await withTransaction(async()=>{const sql=getSql(),target=(await sql`SELECT item.id item_id,variant.id variant_id FROM ordering_menu_items item LEFT JOIN ordering_menu_item_variants variant ON variant.item_id=item.id AND variant.active=TRUE WHERE item.business='Corner Deli' AND item.active=TRUE ORDER BY variant.id NULLS LAST LIMIT 1`)[0];if(!target)throw new Error("Local menu fixture is required.");const actor={id:"barcode-test",name:"Barcode Test",type:"employee" as const,role:"manager" as const},employee={...actor,role:"employee" as const},suffix=randomUUID().replaceAll("-","").slice(0,10).toUpperCase(),first=`BC${suffix}`,second=`BD${suffix}`;
 const created=await saveBarcodeMapping({business:"Corner Deli",barcode:first,itemId:target.item_id,variantId:target.variant_id,actor});if(created.itemId!==target.item_id||created.variantId!==target.variant_id)throw new Error("Stable target resolution failed.");const resolved=await resolveBarcode("Corner Deli",first);if(resolved?.id!==created.id)throw new Error("Active mapping lookup failed.");await saveBarcodeMapping({business:"Corner Deli",barcode:second,itemId:target.item_id,variantId:target.variant_id,actor});result.multiplePerTarget=true;
 let duplicate=false;try{await saveBarcodeMapping({business:"Corner Deli",barcode:first,itemId:target.item_id,actor})}catch(error){duplicate=String(error).includes("already has an active mapping")}if(!duplicate)throw new Error("Duplicate active barcode was allowed.");result.duplicateActivePrevention=true;
 await saveBarcodeMapping({business:"Corner Deli",id:created.id,barcode:first,itemId:target.item_id,variantId:target.variant_id,active:false,actor});if(await resolveBarcode("Corner Deli",first))throw new Error("Inactive mapping resolved.");await saveBarcodeMapping({business:"Corner Deli",barcode:first,itemId:target.item_id,actor});result.activeInactive=true;
 let denied=false;try{await saveBarcodeMapping({business:"Corner Deli",barcode:`BE${suffix}`,itemId:target.item_id,actor:employee})}catch(error){denied=String(error).includes("authorization")}if(!denied)throw new Error("Employee changed a barcode mapping.");result.employeeDenied=true;
 const audits=await sql`SELECT action FROM ordering_barcode_audit WHERE mapping_id=${created.id} ORDER BY created_at`;if(audits.length<2||!audits.some(row=>row.action==="deactivated"))throw new Error("Mapping audit trail failed.");result.audit=true;
 if(identifyBarcodeFormat("12345678")!=="ean_8"||identifyBarcodeFormat("123456789012")!=="upc_a"||identifyBarcodeFormat("ABC-1234")!=="code_128_text")throw new Error("Configured barcode formats failed.");let formatDenied=false;try{identifyBarcodeFormat("bad space") }catch{formatDenied=true}if(!formatDenied)throw new Error("Unconfigured barcode pattern was accepted.");result.explicitFormats=true;
 const captures:string[]=[];const detector=new KeyboardWedgeDetector(capture=>captures.push(capture.value));for(const[key,time]of[["A",0],["B",10],["C",20],["1",30],["Enter",40]]as const)detector.key(key,time+100);if(captures[0]!=="ABC1")throw new Error("Rapid scan was not detected.");for(const[key,time]of[["H",1000],["i",1200],["Enter",1400]]as const)detector.key(key,time);if(captures.length!==1)throw new Error("Human typing was mistaken for a scan.");const input={tagName:"INPUT",isContentEditable:false}as HTMLElement;if(!isHumanTextEntry(input)||isHumanTextEntry({tagName:"DIV",isContentEditable:false}as HTMLElement))throw new Error("Text-entry guard failed.");result.keyboardWedge=true;throw new Error(ROLLBACK)})}catch(error){if(!(error instanceof Error)||error.message!==ROLLBACK)throw error}console.log(JSON.stringify(result,null,2))}
main().catch(error=>{console.error(error instanceof Error?error.stack||error.message:String(error));process.exitCode=1});
