#!/usr/bin/env node
import { execFileSync } from "node:child_process";
import { randomUUID } from "node:crypto";
import { loadEnvFile } from "node:process";
loadEnvFile("/opt/corner-ops/.env");
const address=execFileSync("docker",["inspect","corner-ops-postgres","--format","{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}"],{encoding:"utf8"}).trim();
if(process.env.LOCAL_DEVELOPMENT?.toLowerCase()!=="true"||!process.env.POSTGRES_PASSWORD||!/^172\.|^10\.|^192\.168\./.test(address))throw new Error("Gift-card validation requires the private local PostgreSQL container.");
process.env.DATABASE_DRIVER="postgres";process.env.DATABASE_URL=`postgresql://cornerops:${encodeURIComponent(process.env.POSTGRES_PASSWORD)}@${address}:5432/cornerops`;
const ROLLBACK="rollback:gift-card-validation";
async function main(){const{getSql,withTransaction}=await import("../src/lib/db");const{ensureOrderingGiftCardSchema}=await import("../src/lib/ordering-gift-card-schema");const{activateGiftCard,adjustGiftCard,lookupGiftCard,reloadGiftCard,replaceGiftCard,reverseGiftEntry}=await import("../src/lib/ordering-gift-cards");const{commitTender}=await import("../src/lib/ordering-payments");const{importGiftCards}=await import("../src/lib/ordering-gift-card-import");await ensureOrderingGiftCardSchema();const result:Record<string,unknown>={};try{await withTransaction(async()=>{const sql=getSql(),actor={id:"gift-card-test",name:"Gift Card Test",type:"employee" as const,role:"manager" as const},employee={...actor,role:"employee" as const},suffix=randomUUID().replaceAll("-","").slice(0,12),cardNumber=`TEST${suffix}`,operation=`gift-test-${suffix}`;
  const activated=await activateGiftCard({business:"Corner Deli",initialLoadCents:3000,operationKey:`${operation}:activate`,actor,pin:"2468",cardNumber});if(activated.balanceCents!==3000||!activated.maskedNumber.endsWith(cardNumber.slice(-4).toUpperCase()))throw new Error("Activation or masking failed.");const duplicate=await activateGiftCard({business:"Corner Deli",initialLoadCents:3000,operationKey:`${operation}:activate`,actor,pin:"2468",cardNumber});if(!duplicate.duplicate)throw new Error("Activation was not idempotent.");await reloadGiftCard({business:"Corner Deli",cardNumber,amountCents:1000,operationKey:`${operation}:reload`,actor});await adjustGiftCard({business:"Corner Deli",cardNumber,deltaCents:-500,operationKey:`${operation}:adjust`,reason:"Fixture correction",actor});let denied=false;try{await adjustGiftCard({business:"Corner Deli",cardNumber,deltaCents:1,operationKey:`${operation}:denied`,reason:"Not allowed",actor:employee})}catch{denied=true}if(!denied)throw new Error("Employee manager operation was allowed.");let negativeBlocked=false;try{await adjustGiftCard({business:"Corner Deli",cardNumber,deltaCents:-999999,operationKey:`${operation}:negative`,reason:"Must not overdraw",actor})}catch{negativeBlocked=true}if(!negativeBlocked)throw new Error("Negative balance was allowed.");const immutableTrigger=await sql`SELECT 1 FROM pg_trigger WHERE tgname='ordering_gift_card_ledger_immutable_trigger' AND tgenabled='O'`;if(!immutableTrigger[0])throw new Error("Immutable ledger trigger is missing.");
  const orderId=randomUUID();await sql`INSERT INTO ordering_orders(id,business,source,status,payment_status,service_type,display_number,created_by,first_name_snapshot,last_name_snapshot,phone_snapshot,total_cents,amount_due_cents) VALUES(${orderId},'Corner Deli','pos','sent_to_kitchen','unpaid','pickup',${`GC-${suffix}`},${actor.id},'Gift','Fixture','+13155550199',5000,5000)`;const gift=await commitTender({orderId,business:"Corner Deli",tenderType:"gift_card",amountTenderedCents:5000,giftCardNumber:cardNumber,giftCardPin:"2468",clientMutationId:`${operation}:pay-gift`,actor});if(Number(gift.order.amount_due_cents)!==1500||Number(gift.tenders.at(-1)?.amount_cents)!==3500)throw new Error("Partial gift-card redemption failed.");await commitTender({orderId,business:"Corner Deli",tenderType:"cash",amountTenderedCents:500,clientMutationId:`${operation}:pay-cash`,actor});const paid=await commitTender({orderId,business:"Corner Deli",tenderType:"card",amountTenderedCents:1000,clientMutationId:`${operation}:pay-card`,actor});if(paid.order.payment_status!=="paid")throw new Error("Gift + cash + credit did not settle the order.");const print=await sql`SELECT purpose FROM ordering_print_jobs WHERE order_id=${orderId}`;if(print.length!==3||print.some(row=>row.purpose!=="payment_update"))throw new Error("Payments generated a production ticket.");const redemption=(await sql`SELECT id FROM ordering_gift_card_ledger WHERE payment_transaction_id=${gift.tenders.at(-1)?.id}`)[0];await reverseGiftEntry({business:"Corner Deli",entryId:redemption.id,operationKey:`${operation}:reverse`,reason:"Fixture payment reversal",actor});const afterReverse=await lookupGiftCard({business:"Corner Deli",cardNumber,pin:"2468",includeHistory:true});if(Number(afterReverse.card.current_balance_cents)!==3500)throw new Error("Redemption reversal did not restore balance.");
  const replacementInput={business:"Corner Deli" as const,cardNumber,operationKey:`${operation}:replace`,reason:"Fixture damaged card",actor,pin:"1357"},replacement=await replaceGiftCard(replacementInput),replacementRetry=await replaceGiftCard(replacementInput);if(replacement.balanceCents!==3500||!replacementRetry.duplicate||replacementRetry.cardId!==replacement.cardId)throw new Error("Replacement or replacement idempotency failed.");const imported=`IMPORT${suffix}`,rows=[{sourceReference:`fixture-${suffix}`,cardNumber:imported,balanceCents:2500},{sourceReference:`fixture-${suffix}`,cardNumber:`DUP${suffix}`,balanceCents:1000}];const preview=await importGiftCards({business:"Corner Deli",rows,dryRun:true,batchKey:operation,actor});if(preview.ready!==1||preview.duplicates!==1)throw new Error("Import dry-run duplicate detection failed.");const applied=await importGiftCards({business:"Corner Deli",rows:[rows[0]],dryRun:false,batchKey:operation,actor});const retry=await importGiftCards({business:"Corner Deli",rows:[rows[0]],dryRun:false,batchKey:operation,actor});if(applied.imported!==1||retry.duplicates!==1)throw new Error("Import apply was not idempotent.");result.activation=true;result.maskedDisplay=true;result.pinVerifier=true;result.reloadAndAdjustment=true;result.employeePermissions=true;result.negativeBalanceBlocked=true;result.immutableLedger=true;result.partialRedemption=true;result.mixedTender=true;result.reversal=true;result.replacement=true;result.importDryRun=true;result.importIdempotency=true;result.paymentUpdateOnly=true;throw new Error(ROLLBACK)})}catch(error){if(!(error instanceof Error)||error.message!==ROLLBACK)throw error}console.log(JSON.stringify(result,null,2))}
main().catch(error=>{console.error(error instanceof Error?error.stack||error.message:String(error));process.exitCode=1});
