#!/usr/bin/env node
import { randomUUID } from "node:crypto";import{localValidationEnv}from"./validation-env";localValidationEnv();
const ROLLBACK="rollback:hardware-validation";
async function main(){const{getSql,withTransaction}=await import("../src/lib/db");const{ensureOrderingHardwareSchema}=await import("../src/lib/ordering-hardware-schema");const{saveHardware,hardwareDashboard,controlPrintJob,effectiveDeviceStatus}=await import("../src/lib/ordering-hardware");await ensureOrderingHardwareSchema();const result:Record<string,boolean>={};try{await withTransaction(async()=>{const sql=getSql(),suffix=randomUUID().slice(0,8),actor={id:"hardware-test",name:"Hardware Test",type:"employee" as const,role:"manager" as const},employee={...actor,role:"employee" as const};const location=await saveHardware({business:"Corner Deli",action:"save_location",body:{name:`Hardware ${suffix}`,locationKey:`hardware-${suffix}`},actor});const receipt=await saveHardware({business:"Corner Deli",action:"save_device",body:{locationId:location.id,name:`Receipt ${suffix}`,deviceKey:`receipt-${suffix}`,deviceType:"printer",role:"receipt_printer",adapterKey:"mock",adapterConfig:{}},actor});const kitchen=await saveHardware({business:"Corner Deli",action:"save_device",body:{locationId:location.id,name:`Kitchen ${suffix}`,deviceKey:`kitchen-${suffix}`,deviceType:"printer",role:"kitchen_printer",adapterKey:"mock",adapterConfig:{mockStatus:"online"}},actor});await saveHardware({business:"Corner Deli",action:"save_device",body:{locationId:location.id,name:`Terminal ${suffix}`,deviceKey:`terminal-${suffix}`,deviceType:"payment_terminal",role:"payment_terminal",adapterKey:"payment-placeholder",adapterConfig:{}},actor});await saveHardware({business:"Corner Deli",action:"save_device",body:{locationId:location.id,name:`Scanner ${suffix}`,deviceKey:`scanner-${suffix}`,deviceType:"barcode_scanner",role:"barcode_scanner",adapterKey:"unconfigured",adapterConfig:{}},actor});result.scopedDevices=true;
 let secretDenied=false;try{await saveHardware({business:"Corner Deli",action:"save_device",body:{locationId:location.id,name:"Bad",deviceKey:`bad-${suffix}`,deviceType:"printer",role:"receipt_printer",adapterKey:"mock",adapterConfig:{apiKey:"forbidden"}},actor})}catch(error){secretDenied=String(error).includes("Credentials")}if(!secretDenied)throw new Error("Device credentials were accepted.");result.credentialSafe=true;
 const unknown=await saveHardware({business:"Corner Deli",action:"probe_device",body:{id:receipt.id},actor}),online=await saveHardware({business:"Corner Deli",action:"probe_device",body:{id:kitchen.id},actor});if(unknown.status!=="unknown"||online.status!=="online"||effectiveDeviceStatus({active:true,reported_status:"online",last_seen_at:new Date(Date.now()-180000)})!=="offline")throw new Error("Truthful device status failed.");result.truthfulStatus=true;
 await saveHardware({business:"Corner Deli",action:"save_route",body:{locationId:location.id,printerId:kitchen.id,targetType:"station",targetId:"grill",priority:10},actor});result.routing=true;
 let denied=false;try{await saveHardware({business:"Corner Deli",action:"save_location",body:{name:"Denied",locationKey:`denied-${suffix}`},actor:employee})}catch(error){denied=String(error).includes("authorization")}if(!denied)throw new Error("Employee modified hardware.");result.authorization=true;
 const order=(await sql`SELECT id FROM ordering_orders WHERE business='Corner Deli' ORDER BY created_at DESC LIMIT 1`)[0];if(!order)throw new Error("A local order fixture is required.");const jobId=randomUUID(),idem=`hardware-${suffix}`;await sql`INSERT INTO ordering_print_jobs(id,business,order_id,purpose,status,actor_type,actor_id,error_message,payload,idempotency_key,location_id,device_id) VALUES(${jobId},'Corner Deli',${order.id},'paid_receipt','failed','employee',${actor.id},'Test failure','{}'::jsonb,${idem},${location.id},${receipt.id})`;const duplicate=await sql`INSERT INTO ordering_print_jobs(id,business,order_id,purpose,status,actor_type,actor_id,payload,idempotency_key) VALUES(${randomUUID()},'Corner Deli',${order.id},'paid_receipt','queued','employee',${actor.id},'{}'::jsonb,${idem}) ON CONFLICT DO NOTHING RETURNING id`;if(duplicate.length)throw new Error("Duplicate print idempotency key accepted.");await controlPrintJob({business:"Corner Deli",jobId,action:"retry",reason:"Fixture retry",actor});const reprint=await controlPrintJob({business:"Corner Deli",jobId,action:"reprint",reason:"Fixture reprint",actor});const jobs=await sql`SELECT status,retry_count,is_reprint,parent_job_id FROM ordering_print_jobs WHERE id IN (${jobId},${reprint.id}) ORDER BY is_reprint`;if(jobs.length!==2||jobs[0].status!=="queued"||Number(jobs[0].retry_count)!==1||jobs[1].is_reprint!==true||jobs[1].parent_job_id!==jobId)throw new Error("Print queue controls failed.");result.idempotentQueue=true;result.retryReprint=true;
 const dashboard=await hardwareDashboard("Corner Deli");if(!dashboard.devices.some(row=>row.id===kitchen.id)||!dashboard.jobs.some(row=>row.id===jobId))throw new Error("Queue visibility failed.");result.visibility=true;throw new Error(ROLLBACK)})}catch(error){if(!(error instanceof Error)||error.message!==ROLLBACK)throw error}console.log(JSON.stringify(result,null,2))}
main().catch(error=>{console.error(error instanceof Error?error.stack||error.message:String(error));process.exitCode=1});
