#!/usr/bin/env node
import { execFileSync } from "node:child_process";
import { randomUUID } from "node:crypto";
import { loadEnvFile } from "node:process";
loadEnvFile("/opt/corner-ops/.env");
const host=execFileSync("docker",["inspect","corner-ops-postgres","--format","{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}"],{encoding:"utf8"}).trim();
if(!process.env.POSTGRES_PASSWORD)throw new Error("POSTGRES_PASSWORD is required.");
process.env.DATABASE_DRIVER="postgres";process.env.DATABASE_URL=`postgresql://cornerops:${encodeURIComponent(process.env.POSTGRES_PASSWORD)}@${host}:5432/cornerops`;process.env.OPENAI_ORDERING_MCP_TOKEN=`validation-${randomUUID()}`;
async function main(){const [{getSql},{callerFromSipHeaders,registerOpenAiCall},{POST}]=await Promise.all([import("../src/lib/db"),import("../src/lib/openai-phone-ordering"),import("../src/app/api/openai/ordering/mcp/route")]);const sql=getSql(),callId=`rtc_${randomUUID()}`,authorization=`Bearer ${process.env.OPENAI_ORDERING_MCP_TOKEN}`;try{const caller=callerFromSipHeaders([{name:"From",value:'"Customer" <sip:+13155550188@example.test>'}]);await registerOpenAiCall(callId,caller);const invoke=(body:unknown,token=authorization)=>POST(new Request("http://localhost/api/openai/ordering/mcp",{method:"POST",headers:{authorization:token,"content-type":"application/json"},body:JSON.stringify(body)}));const unauthorized=await invoke({jsonrpc:"2.0",id:1,method:"tools/list"},"Bearer wrong"),initialized=await(await invoke({jsonrpc:"2.0",id:2,method:"initialize",params:{}})).json(),listed=await(await invoke({jsonrpc:"2.0",id:3,method:"tools/list"})).json(),called=await(await invoke({jsonrpc:"2.0",id:4,method:"tools/call",params:{name:"describe_capabilities",arguments:{callId}}})).json(),blocked=await(await invoke({jsonrpc:"2.0",id:5,method:"tools/call",params:{name:"send",arguments:{callId,orderId:randomUUID(),customerConfirmed:false}}})).json();const result={callerNormalized:caller==="3155550188",unauthorized:unauthorized.status===401,protocol:initialized.result?.protocolVersion==="2025-06-18",toolsListed:listed.result?.tools?.some((tool:{name:string})=>tool.name==="create_draft"),callBound:called.result?.content?.[0]?.text?.includes("pricingAuthority")||called.result?.content?.[0]?.text?.includes("serviceTypes"),unconfirmedSendBlocked:blocked.result?.isError===true};console.log(JSON.stringify(result,null,2));if(Object.values(result).some(value=>!value))throw new Error("OpenAI phone ordering validation failed.")}finally{await sql`DELETE FROM ordering_call_sessions WHERE three_cx_call_id=${callId}`}}
main().catch(error=>{console.error(error);process.exitCode=1});
