import { calculatePromotions, promotionScheduleMatches } from "../src/lib/ordering-promotions";
import { applyPromotionsToOrder } from "../src/lib/ordering-promotions";
import { ensureOrderingPromotionSchema } from "../src/lib/ordering-promotion-schema";
import { getSql } from "../src/lib/db";
import { randomUUID } from "node:crypto";
import { execFileSync } from "node:child_process";
import { loadEnvFile } from "node:process";

loadEnvFile("/opt/corner-ops/.env");
const databaseAddress=execFileSync("docker",["inspect","corner-ops-postgres","--format","{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}"],{encoding:"utf8"}).trim();
if(process.env.LOCAL_DEVELOPMENT?.toLowerCase()!=="true"||!process.env.POSTGRES_PASSWORD||!/^172\.|^10\.|^192\.168\./.test(databaseAddress))throw new Error("Promotion validation requires private local PostgreSQL.");
process.env.DATABASE_DRIVER="postgres";process.env.DATABASE_URL=`postgresql://cornerops:${encodeURIComponent(process.env.POSTGRES_PASSWORD)}@${databaseAddress}:5432/cornerops`;

const ids={pizza:"00000000-0000-4000-8000-000000000001",wings:"00000000-0000-4000-8000-000000000002",drink:"00000000-0000-4000-8000-000000000003"};
const lines=[
  {id:"line-pizza",item_id:ids.pizza,variant_id:null,category_id:"cat-pizza",quantity:1,unit_price_cents:2000,modifier_total_cents:200},
  {id:"line-wings",item_id:ids.wings,variant_id:null,category_id:"cat-wings",quantity:1,unit_price_cents:2000,modifier_total_cents:175},
  {id:"line-drink",item_id:ids.drink,variant_id:null,category_id:"cat-drink",quantity:1,unit_price_cents:350,modifier_total_cents:0},
];
const bundle={id:"promo-bundle",name:"Bundle",customer_label:"Pizza + Wings + 1L Deal",promotion_type:"bundle",priority:100,rule:{components:[{id:"pizza",quantity:1,itemIds:[ids.pizza]},{id:"wings",quantity:1,itemIds:[ids.wings]},{id:"drink",quantity:1,itemIds:[ids.drink]}],repeatable:true},adjustment:{bundlePriceCents:4000},active:true,automatic:true,stackable:false,stackable_with_loyalty:false,exclusive_group:"base",version:1};
const when=new Date("2026-08-13T17:00:00Z");
const applied=calculatePromotions([bundle],lines,when,"pickup","pos");
if(applied.length!==1||applied[0].discountCents!==350||applied[0].normalBaseSubtotalCents!==4350)throw new Error("Fixed bundle calculation failed.");
const finalWithModifiers=4350+375-applied[0].discountCents;if(finalWithModifiers!==4375)throw new Error("Paid modifiers were discounted by the bundle.");
if(calculatePromotions([bundle],lines.slice(0,2),when,"pickup","pos").length)throw new Error("Incomplete bundle remained applied.");
const doubled=lines.map(line=>({...line,quantity:2})),twice=calculatePromotions([bundle],doubled,when,"pickup","pos");if(twice.length!==2||twice.reduce((sum,row)=>sum+row.discountCents,0)!==700)throw new Error("Repeated bundle calculation failed.");
const consumed=new Map<string,number>();for(const result of twice)for(const allocation of result.allocations)consumed.set(allocation.lineId,(consumed.get(allocation.lineId)||0)+allocation.quantity);if([...consumed.values()].some(quantity=>quantity!==2))throw new Error("A line quantity was double-consumed.");
const thursday={...bundle,id:"promo-thursday",promotion_type:"amount_off",rule:{components:[{id:"jumbo",quantity:1,itemIds:[ids.pizza]}],repeatable:true,daysOfWeek:[4]},adjustment:{amountOffCents:300}};
const scheduledThursday=new Date("2026-08-13T16:00:00Z"),scheduledFriday=new Date("2026-08-14T16:00:00Z");if(!promotionScheduleMatches(thursday.rule,scheduledThursday,"pickup","pos")||promotionScheduleMatches(thursday.rule,scheduledFriday,"pickup","pos"))throw new Error("Scheduled business-day matching failed.");
const thursdayResult=calculatePromotions([thursday],[lines[0]],scheduledThursday,"pickup","pos");if(thursdayResult[0]?.discountCents!==300||2000+200-300!==1900)throw new Error("Fixed-dollar modifier preservation failed.");
const allocationTotal=applied[0].allocations.reduce((sum,row)=>sum+row.discountCents,0);if(allocationTotal!==applied[0].discountCents)throw new Error("Allocation drift detected.");
const allowanceBundle={...bundle,adjustment:{bundlePriceCents:4000,modifierAllowances:[{groupId:"toppings",quantity:1,intensity:"regular"}]}},allowanceLines=lines.map(line=>line.id==="line-pizza"?{...line,modifiers:[{groupId:"toppings",optionId:"pepperoni",priceCents:200,quantity:1,intensity:"regular"}]}:line),allowanceResult=calculatePromotions([allowanceBundle],allowanceLines,when,"pickup","pos");if(allowanceResult[0]?.discountCents!==550)throw new Error("Explicit modifier allowance failed.");
const exclusiveA={...thursday,id:"exclusive-a",priority:20,stackable:true,exclusive_group:"base"},exclusiveB={...thursday,id:"exclusive-b",priority:10,stackable:true,exclusive_group:"base"};if(calculatePromotions([exclusiveB,exclusiveA],[lines[0]],scheduledThursday,"pickup","pos").length!==1)throw new Error("Exclusive promotion group double-discounted a line.");
async function snapshotValidation(){await ensureOrderingPromotionSchema();const sql=getSql(),orderId=randomUUID(),promotionId=randomUUID(),lineIds=[randomUUID(),randomUUID(),randomUUID()];const menu=await sql`SELECT id,category_id,base_price_cents FROM ordering_menu_items WHERE business='Corner Deli' AND active=TRUE AND base_price_cents>0 LIMIT 3`;if(menu.length<3)throw new Error("Promotion snapshot fixtures need three menu items.");try{await sql`INSERT INTO ordering_orders(id,business,source,status,payment_status,service_type,display_number,created_by,subtotal_cents,total_cents,amount_due_cents) VALUES(${orderId},'Corner Deli','pos','draft','unpaid','pickup',${`PROMO-${Date.now()}`},'promotion-validator',${menu.reduce((sum,row)=>sum+Number(row.base_price_cents),0)},${menu.reduce((sum,row)=>sum+Number(row.base_price_cents),0)},${menu.reduce((sum,row)=>sum+Number(row.base_price_cents),0)})`;for(let index=0;index<3;index++)await sql`INSERT INTO ordering_order_items(id,order_id,item_id,item_name_snapshot,quantity,unit_price_cents,modifier_total_cents,line_total_cents,sort_order) VALUES(${lineIds[index]},${orderId},${menu[index].id},'Promotion fixture',1,${Number(menu[index].base_price_cents)},0,${Number(menu[index].base_price_cents)},${index})`;const normal=menu.reduce((sum,row)=>sum+Number(row.base_price_cents),0),price=Math.max(0,normal-100);await sql`INSERT INTO ordering_promotions(id,business,name,customer_label,promotion_type,priority,rule,adjustment,active,automatic,stackable,created_by,version) VALUES(${promotionId},'Corner Deli',${`Promotion validator ${promotionId}`},'Snapshot Deal','bundle',9999,${JSON.stringify({components:menu.map((row,index)=>({id:`c${index}`,quantity:1,itemIds:[String(row.id)]})),repeatable:false})}::jsonb,${JSON.stringify({bundlePriceCents:price})}::jsonb,TRUE,TRUE,FALSE,'promotion-validator',1)`;await applyPromotionsToOrder(orderId);const before=(await sql`SELECT promotion_version,label_snapshot,discount_cents,configuration_snapshot FROM ordering_order_promotion_applications WHERE order_id=${orderId}`)[0];if(Number(before?.discount_cents)!==100)throw new Error("Database promotion application failed.");await sql`UPDATE ordering_orders SET status='sent_to_kitchen' WHERE id=${orderId}`;await sql`UPDATE ordering_promotions SET version=2,customer_label='Changed Tomorrow',adjustment=${JSON.stringify({bundlePriceCents:0})}::jsonb WHERE id=${promotionId}`;await applyPromotionsToOrder(orderId);const after=(await sql`SELECT promotion_version,label_snapshot,discount_cents,configuration_snapshot FROM ordering_order_promotion_applications WHERE order_id=${orderId}`)[0];if(Number(after?.promotion_version)!==1||after?.label_snapshot!==before.label_snapshot||Number(after?.discount_cents)!==100)throw new Error("Sent-order promotion snapshot changed.");return true}finally{await sql`DELETE FROM ordering_orders WHERE id=${orderId}`;await sql`DELETE FROM ordering_promotions WHERE id=${promotionId}`}}
snapshotValidation().then(snapshotImmutable=>console.log(JSON.stringify({bundle:{grossBase:4350,dealBase:4000,discount:350,withPaidModifiers:4375},removeDrinkRemovesDeal:true,multipleApplications:twice.length,scheduledThursday:true,scheduledFriday:false,fixedDollarDiscount:300,integerAllocationExact:true,modifierAllowanceDiscount:allowanceResult[0].discountCents-350,exclusiveGroupPreventsDoubleDiscount:true,snapshotImmutable},null,2))).catch(error=>{console.error(error);process.exitCode=1});
