import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const root=process.cwd(),lib=readFileSync(`${root}/src/lib/ordering-voice-payment.ts`,"utf8"),mx=readFileSync(`${root}/src/lib/mx-merchant.ts`,"utf8"),route=readFileSync(`${root}/src/app/api/internal/voice-payment/route.ts`,"utf8"),proxy=readFileSync(`${root}/src/proxy.ts`,"utf8"),agi=readFileSync(`${root}/asterisk/voice-payment.py`,"utf8"),dialplan=readFileSync(`${root}/asterisk/extensions.conf.template`,"utf8"),prompt=readFileSync(`${root}/src/lib/openai-phone-prompt.ts`,"utf8");

assert.match(lib,/MX_ENVIRONMENT.*production/);
assert.match(mx,/Voice-card testing is locked to the MX sandbox/);
assert.match(route,/x-voice-payment-secret/);
assert.match(proxy,/\/api\/internal\/voice-payment/);
assert.doesNotMatch(lib,/card_number\s+TEXT|cvv\s+TEXT|expiry_month\s+TEXT/i);
assert.doesNotMatch(agi,/print\(|logging\.|logger\./);
assert.match(agi,/DEBUG_RECOGNITION=SANDBOX/);
assert.match(agi,/VOICE_PAYMENT_SANDBOX_RECOGNITION/);
assert.match(agi,/level>120/);
assert.doesNotMatch(agi,/for delay in \(0,0\.2\)/);
assert.match(agi,/card=expiry=cvv=zipcode=""/);
assert.match(dialplan,/EAGI_AUDIO_FORMAT=slin16/);
assert.match(dialplan,/corner-ops-voice-payment/);
assert.match(dialplan,/AI_CUSTOMER_PHONE=\$\{CUT\(AI_ROUTE,\|,3\)\}/);
assert.match(dialplan,/corner-ops-voice-payment,\$\{AI_CALL_ID\},\$\{AI_CUSTOMER_PHONE\}/);
assert.match(agi,/"callId":call_id/);
assert.match(lib,/call_id=\$\{callId\}/);
assert.match(agi,/def hear_card_number\(allow_full=True\)/);
assert.match(agi,/accepted_lengths=\[4,15,16\] if allow_full else \[4\]/);
assert.match(agi,/accepted_lengths=\[4,15,16\]/);
assert.match(agi,/def digit_search\(lengths\)/);
assert.match(agi,/chunk=audioop\.mul\(chunk,2,min\(6\.0,max\(1\.0,1800\.0\/level\)\)\)/);
assert.match(agi,/target=15 if card\.startswith\(\("34","37"\)\) else 16/);
assert.match(agi,/while len\(card\)<target/);
assert.match(agi,/group_size=6 if remaining==11 else 5 if remaining==5 else min\(4,remaining\)/);
assert.match(agi,/hear_digits\(group_size,group_size,prompt_name,accepted_lengths=\[group_size\]\)/);
assert.match(agi,/time\.monotonic\(\)-last_voice>2\.4/);
assert.match(agi,/def discard_prompt_echo\(\)/);
assert.match(agi,/import fcntl/);
assert.match(agi,/fcntl\.ioctl\(3,termios\.FIONREAD/);
assert.doesNotMatch(agi,/termios\.ioctl/);
assert.match(agi,/def _drain_audio\(stop\)/);
assert.match(agi,/threading\.Thread\(target=_drain_audio/);
assert.match(agi,/def playback\(command\)/);
assert.match(agi,/def say_digits\(value\)/);
assert.match(agi,/prompt\("confirm-ending"\);say_digits\(last4\)/);
assert.match(agi,/for card_attempt in range\(3\)/);
assert.match(agi,/hear_card_number\(allow_full=card_attempt==0\)/);
assert.match(agi,/def valid_luhn\(value\)/);
assert.match(agi,/not valid_luhn\(card\)/);
assert.match(agi,/debug_recognition\("card-validation"/);
assert.match(agi,/def hear_expiration\(\)/);
assert.match(agi,/1<=int\(value\[:2\]\)<=12/);
assert.match(agi,/debug_recognition\("card-confirmation"/);
assert.match(agi,/code":failure_stage/);
for(const stage of ["card_recognition_failed","card_confirmation_failed","expiration_recognition_failed","security_code_recognition_failed","billing_zip_recognition_failed","provider_payment_failed"])
  assert.match(agi,new RegExp(stage));
assert.match(lib,/Secure payment failed:/);
assert.match(lib,/state='ended'/);
assert.doesNotMatch(agi,/prompt\("welcome"\)/);
assert.match(dialplan,/AI_CUSTOMER_PHONE/);
assert.equal((dialplan.match(/Set\(AGISIGHUP=no\)/g) || []).length,2);
assert.match(readFileSync(`${root}/asterisk/Dockerfile`,"utf8"),/sox "\$\{source\}" -r 8000/);
assert.match(lib,/\?`tel:\$\{explicit\}`:explicit/);
assert.match(lib,/must be an explicit SIP URI for the local payment extension/);
assert.match(prompt,/must leave the AI audio and transcription path/);
assert.match(prompt,/Never ask for, repeat, infer, or transcribe a card number/);

console.log(JSON.stringify({sandboxLock:true,authenticatedInternalRoute:true,noSensitiveDatabaseColumns:true,noRecognizerLogging:true,aiTranscriptionBoundary:true,asteriskEagi:true},null,2));
