export const RIDICULOUS_MENU_ADS = [
  "JUMBO PIZZA: 16 INCHES OF CHEESE-BASED CONFLICT RESOLUTION.",
  "TRADITIONAL WINGS: BONES INCLUDED SO YOU KNOW WE DIDN'T 3D-PRINT THEM.",
  "BONELESS WINGS: CHICKEN WITH THE ADMINISTRATIVE BURDEN REMOVED.",
  "POUTINE: FRIES, GRAVY, AND CHEESE—YOUR FORK HAS BEEN WARNED.",
  "THE BIG BOSS SUB: MANAGEMENT EXPERIENCE YOU CAN EAT.",
  "CURLY FRIES: REGULAR FRIES THAT REFUSED TO FOLLOW DIRECTIONS.",
  "WAFFLE FRIES: STRUCTURAL ENGINEERING WITH NACHO-CHEESE CAPABILITY.",
  "JULIANNE SALAD: VEGETABLES WEARING ENOUGH MEAT TO PASS AS DINNER.",
  "PIZZA LOGS: PIZZA ACHIEVING ITS FINAL, MOST PORTABLE FORM.",
  "CHICKEN TENDER DINNER: BECAUSE FORKS ARE AN OPTIONAL EXPENSE.",
  "CHEESEBURGER: A SALAD WOULD NEVER DO THIS FOR YOU.",
  "COLD SUBS: TOASTED ONLY IF YOU ASK. JUDGED SILENTLY EITHER WAY.",
];
