"use client";
import{useEffect,useMemo,useState}from"react";
type Item={id:string;name:string;variants:Array<{id:string;name:string}>};type Mapping={id:string;barcode:string;barcodeFormat:string;itemId:string;variantId:string|null;itemName:string;variantName:string|null;active:boolean};
export default function BarcodeSettingsClient(){
 const[items,setItems]=useState<Item[]>([]),[mappings,setMappings]=useState<Mapping[]>([]),[barcode,setBarcode]=useState(""),[itemId,setItemId]=useState(""),[variantId,setVariantId]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const selected=useMemo(()=>items.find(item=>item.id===itemId),[items,itemId]);
 async function load(){const[mappingResponse,menuResponse]=await Promise.all([fetch("/api/ordering/barcodes?business=Corner%20Deli",{cache:"no-store"}),fetch("/api/ordering/menu?business=Corner%20Deli",{cache:"no-store"})]);const mappingBody=await mappingResponse.json(),menuBody=await menuResponse.json();if(!mappingResponse.ok)throw new Error(mappingBody.error||"Could not load barcode mappings.");setMappings(mappingBody.mappings||[]);setItems((menuBody.categories||[]).flatMap((category:{items:Item[]})=>category.items))}
 useEffect(()=>{void load().catch(error=>setMessage(error instanceof Error?error.message:"Could not load barcode mappings."))},[]);
 async function create(){if(!barcode||!itemId)return;setBusy(true);setMessage("");try{const response=await fetch("/api/ordering/barcodes",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({business:"Corner Deli",barcode,itemId,variantId:variantId||null})}),body=await response.json();if(!response.ok)throw new Error(body.error||"Could not save mapping.");setBarcode("");setItemId("");setVariantId("");setMessage("Barcode mapping saved and audited.");await load()}catch(error){setMessage(error instanceof Error?error.message:"Could not save mapping.")}finally{setBusy(false)}}
 async function toggle(mapping:Mapping){setBusy(true);setMessage("");try{const response=await fetch("/api/ordering/barcodes",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({business:"Corner Deli",id:mapping.id,barcode:mapping.barcode,itemId:mapping.itemId,variantId:mapping.variantId,active:!mapping.active})}),body=await response.json();if(!response.ok)throw new Error(body.error||"Could not update mapping.");setMessage(`Mapping ${mapping.active?"deactivated":"activated"}.`);await load()}catch(error){setMessage(error instanceof Error?error.message:"Could not update mapping.")}finally{setBusy(false)}}
 return <section className="posSettingsCard"><h2>Barcode mappings</h2><p>Manager-only merchandise mappings for USB or Bluetooth keyboard-wedge scanners. Inactive history is retained.</p>{message&&<p role="status">{message}</p>}<div className="posSettingsGrid"><label>Barcode<input value={barcode} onChange={event=>setBarcode(event.target.value)} autoComplete="off"/></label><label>Item<select value={itemId} onChange={event=>{setItemId(event.target.value);setVariantId("")}}><option value="">Choose item</option>{items.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Variant (optional)<select value={variantId} disabled={!selected?.variants.length} onChange={event=>setVariantId(event.target.value)}><option value="">No specific variant</option>{selected?.variants.map(variant=><option key={variant.id} value={variant.id}>{variant.name}</option>)}</select></label><button type="button" disabled={busy||!barcode||!itemId} onClick={()=>void create()}>ADD MAPPING</button></div><div>{mappings.map(mapping=><article key={mapping.id}><strong>{mapping.barcode}</strong> <span>{mapping.itemName}{mapping.variantName?` · ${mapping.variantName}`:""} · {mapping.barcodeFormat} · {mapping.active?"ACTIVE":"INACTIVE"}</span> <button type="button" disabled={busy} onClick={()=>void toggle(mapping)}>{mapping.active?"DEACTIVATE":"ACTIVATE"}</button></article>)}</div></section>
}
