"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type QueueRow={id:string;order_id:string;check_id?:string|null;display_number:string;first_name_snapshot:string;last_name_snapshot:string;service_type:string;total_cents:number;paid_cents:number;amount_due_cents:number;status:string;source_station_key:string;queued_at:string};
type Profile={name:string;station_key:string;station_mode:"payment"|"order_taker";receipt_printer_id?:string|null;payment_terminal_id?:string|null;gift_card_reader_id?:string|null};
const money=(cents:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(cents||0)/100);

export default function PaymentStationClient(){
  const router=useRouter(),[queue,setQueue]=useState<QueueRow[]>([]),[profile,setProfile]=useState<Profile|null>(null),[message,setMessage]=useState("");
  async function load(){const stationKey=localStorage.getItem("corner-ops-station-key")||"",response=await fetch(`/api/ordering/payment-stations?stationKey=${encodeURIComponent(stationKey)}`,{cache:"no-store"}),body=await response.json();if(!response.ok)throw new Error(body.error||"Could not load payment queue.");setQueue(body.queue||[]);setProfile(body.profile||null)}
  useEffect(()=>{void load().catch(error=>setMessage(error.message));const timer=window.setInterval(()=>void load().catch(()=>undefined),5000);return()=>window.clearInterval(timer)},[]);
  async function action(id:string,action:"claim"|"cancel"){const response=await fetch("/api/ordering/payment-stations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id,action})}),body=await response.json();if(!response.ok)throw new Error(body.error||"Payment queue update failed.");await load()}
  async function open(row:QueueRow){setMessage("");try{await action(row.id,"claim");localStorage.setItem("corner-ops-checkout-order",JSON.stringify({id:row.order_id,displayNumber:row.display_number,totalCents:Number(row.total_cents),deliveryFeeCents:0,timingMessage:"",kitchenTimingLabel:"",scheduledFor:null,promotions:[],loyalty:[],orderItemIds:[],checkoutOnly:true,checkId:row.check_id||null,paymentQueue:true}));router.push("/pos/deli")}catch(error){setMessage(error instanceof Error?error.message:"Could not open checkout.")}}
  if(!profile)return <main className="paymentStationPage"><h1>Payment station</h1><p>This device has not been assigned a station. A manager can assign it under Settings → Hardware.</p>{message&&<p role="alert">{message}</p>}</main>;
  return <main className="paymentStationPage"><header><div><span>{profile.station_mode==="payment"?"PAYMENT STATION":"ORDER-TAKING STATION"}</span><h1>{profile.name}</h1></div><button onClick={()=>void load()}>REFRESH</button></header>{profile.station_mode!=="payment"&&<p className="paymentWarning">This device is configured to take orders only. Open this queue on the designated payment station.</p>}{message&&<p role="alert">{message}</p>}<section className="paymentQueue"><h2>Waiting for payment <b>{queue.length}</b></h2>{queue.length===0?<p>No checks are waiting.</p>:queue.map(row=><article key={row.id}><div><strong>#{row.display_number}</strong><span>{`${row.first_name_snapshot||""} ${row.last_name_snapshot||""}`.trim()||"Walk-in"} · {row.service_type.replaceAll("_"," ")}</span><small>From {row.source_station_key||"unassigned station"} · {new Date(row.queued_at).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})}</small></div><div><strong>{money(row.amount_due_cents)} due</strong><button disabled={profile.station_mode!=="payment"} onClick={()=>void open(row)}>OPEN CHECKOUT</button><button className="secondary" onClick={()=>void action(row.id,"cancel").catch(error=>setMessage(error.message))}>CANCEL</button></div></article>)}</section></main>
}
